### ISSUE TITLE
Monitoring UXD

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1067]
We need quick wire skeletons of the UXD to get an idea of what data our monitoring APIs need incorporate.  This will help us complete issue #1065.

Notes of the VF2F on this topic is available at:
https://docs.google.com/document/d/1cWiuzqvAEL2jjBnUqbGV7o4bLLZZZRAmbNZHszTKsWU/edit

**Comment by sjcox-rh** [comment]
@chirino will work on a high level design this week!

**Comment by sjcox-rh** [comment]
@chirino Here are high level designs for Monitoring. Used a lot of placeholder content but hopefully you get a general idea of some of our thoughts for the user flow.

[Monitor_HighLevelDesign.pdf](https://github.com/syndesisio/syndesis/files/1647727/Monitor_HighLevelDesign.pdf)

Since this is high level, would love to start a discussion on priorities based on this wholistic view and we can iterate and drill down from there. Happy to set up a meeting!

@kcbabo @gashcrumb @amysueg @dongniwang @michael-coker @seanforyou23

**Comment by chirino** [comment]
Cool. I’ve got a bunch of feedback to give. :)
Please setup a meeting.

**Comment by KurtStam** [comment]
@sjcox-rh After meeting today with @deeleman a few questions come up about the metrics design:

1. For the 'system metrics'/dashboard. The 'top 5 integrations' is a widget that is already there, but it this ranked by #messages? and if so only, the 'last 30 days' means only message over the last 30 days? (This would be a problem as we don't yet capture messages over time), and the green check means what, no errors?

2. Another question on the 'system metrics'/dashboard' and not really about metrics; but still part of the dashboard page, can we ignore the 'message' widget? We have until now. It seems rather hard to make sure this displays any kind of useful information.

3. On the 'Integration page' the first metrics box in the design shows 'total' errors. Is this different from the errors shown in the 3rd box containing successful and error messages?

**Comment by sjcox-rh** [comment]
@KurtStam Answers below!

1. Yes the green checkmark means no errors for that specific integration were found. As for "last 30 days" we just added that as a footnote that these were the most used integrations during the last month. So you're saying because of how the widget is ranked, that statement would not be valid?

2. I think that's more of a question for @kcbabo? I saw in the Monitor requirements doc from the VF2F that messaging was suggested. That's why I added a message widget here alongside the message card. If it's not useful and offers little value, I don't see why we couldn't remove it. But i'll defer to Keith for that.

3. Do you happen to have an example of what a message would look like? I was assuming errors and messages were different but I could be wrong.

As for wireframes, this is the only wireframe that was included for the system metrics. PR #1252 .Since it's only adding a couple widgets and status cards to the home page, it's only one page. If we want to allow drill down on the status aggregate cards found at the top, we can meet and discuss type of content that will be shown there.

Thanks!

**Comment by KurtStam** [comment]
@sjcox-rh 

ad 1. I'm saying that at the moment we only capture the total number of message since first deployed (over the lifetime of the integration). So yeah 'in the last 30 days' is only connect 30 days after deployment ;).

ad 3. I'm referring to message payload, which is JSON formatted String. Which can contain an error is something went wrong. So then it would be a 'error' message. Total messages = successful messages + error messages. As displayed in the third box:

<img width="1024" alt="screen shot 2018-01-30 at 2 24 46 pm" src="https://user-images.githubusercontent.com/35576/35586708-9cbe45e2-05c9-11e8-8ee3-d463a020cf45.png">

So what's in the first box then? Are you maybe thinking errors in the logs? If so that would fall under logging I think.

syndesis.io/integration-id

**Comment by sjcox-rh** [comment]
@KurtStam Ahh good to know. So no need to show the  "in the last 30 days". We can remove that line since it doesn't apply after 30 days.

Also, would showing the number or errors in the logs be useful into @kcbabo?

**Comment by deeleman** [comment]
@sjcox-rh Where can I find the wireframes or final designs for the metrics widget at the Integrations detail page? Thx.

**Comment by paoloantinori** [comment]
Hi, I'm checking the stories currently still in Inbox column for Spring 24. https://github.com/syndesisio/syndesis/issues#boards?milestones=Sprint%2024%232018-02-16&repos=105563335

Do you have any update on this?

thank you

**Comment by amysueg** [comment]
@sjcox-rh  - per @deeleman's note, are there any additional designs to share here?
thanks!

**Comment by sjcox-rh** [comment]
@deeleman Here is a mock for the integration level metrics! For now there is no drill down behavior until more discussion is done around details of metrics we want to share. @amysueg  @paoloantinori 

![metrics](https://user-images.githubusercontent.com/16257540/36137252-34e0c582-1049-11e8-90e3-b512cb00cc0b.png)

**Comment by deeleman** [comment]
@sjcox-rh Thanks, but this also entails a change in the way the Integration detail page operates: Now we have a tabbed view, and split History and Logs into separate detail views, where they were currently presented as a sort of "list" all in one page.

How am I supposed to style the new history and Logs contents?

**Comment by sjcox-rh** [comment]
Sorry about the confusion, yes the integration details page introduces tabs now to accomodate all the additional information we want to share with the user. Here is the UX issue for the logs (now called Activity) and you will see the layout for the History page as well (details)

UX Design #1487 

Here is the PR for the designs #1488 

Let me know if you have any questions!
