### ISSUE TITLE
As an expert integrator, drill into technical integration monitoring

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1092]
As an expert integrator, I want the ability to drill down into the Camel HawtIO view of an integration directly from the Syndesis UI.  Ideally, a direct link to the HawtIO console would be provided on the same page as high-level metrics for an integration.

**Comment by chirino** [comment]
I just tested out to see if deep linking into the java console is possible and ran into issues.

Scenario 1:
In a new incognito session, when I log into openshift console and follow the link to HawtIO console. It works well. I can copy the resulting link and use it in a new tab and the hawtio console still loads up:

![openshift-jvm](https://user-images.githubusercontent.com/103255/35046552-50dbf714-fb65-11e7-9e9d-8e98c93813c5.jpg)

Scenario 2:
In a new incognito session, when I log into the syndesis console and then copy the HawtIO console link in a new tab, this is what loads up:

![banners_and_alerts_and_openshift-jvm](https://user-images.githubusercontent.com/103255/35046612-83dcd46c-fb65-11e7-9ab8-b574b46dd7fc.jpg)

It seems HawtIO data cannot be access because we are not logged into the openshift console yet in this browser session, and HawtIO does not force you to authenticate.

**Comment by gashcrumb** [comment]
So this is the link that's used from the openshift console, note the token is encoded in the document hash:

https://github.com/openshift/origin-web-console/blob/master/app/scripts/extensions/javalink/javaLink.js#L68-L79

So we'd need the openshift console URL + `/java/#<our auth token>?jolokiaUrl=<url encoded jolokia URL>&title=<container name>&returnTo=<previous page URL>`
