### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1119]
See also **https://issues.jboss.org/browse/ENTESB-11551**

As an expert integrator, I need the ability to backup and restore a Syndesis environment.  Ideally, a single UI or tool can be used to create the backup and restore from backup.  In the absence of a tool-driven approach, I need detailed instructions for the create and restore.

DoD:

- The backup captures all configuration, history, metrics, logs and any other data available in my Syndesis environment.  

- Restoring from a backup results in an environment that is identical to the environment the backup was created from.

- The feature owner has confirmed one of the following:
-- There is an initial draft of the user doc for this feature. 
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by gashcrumb** [comment]
Is this the same user story from #1118?

**Comment by kcbabo** [comment]
What the heck?  Seems like the same description ended up in both.  Fortunately, I have the user story save in a text editor as well. :-)  I will update now.

**Comment by kcbabo** [comment]
OK, description updated.

**Comment by rhuss** [comment]
@kcbabo The title is 'Backup & Restore', but the description is about upgrades. Is this intentional ? 

Not sure whether we actually ever discussed about backup & restore already.

**Comment by kcbabo** [comment]
GitHub did something really weird when I created the upgrade and backup issues.  It's almost like the issue description was cached when I created the individual issues as we also had the same issue with integration and infra upgrade issues.  Anyway, I just updated the description to be the original text I had.  Luckily, I still had it sitting around in a text editor tab.

**Comment by paoloantinori** [comment]
So this is tightly coupled with the upgrade stories, and no, we won't have any UI for the first implementation.

**Comment by heiko-braun** [comment]
@rhuss Do you know where we stand with this? Could you help break down the issue and assess the current state of things?

**Comment by rhuss** [comment]
There has no work done recently on the Backup/Restore story (although we already know how to backup & restore which is used for doing rollback on failed updates, its just not exposed as 'normal' backups).

Our idea is now that we have operators in place to implement Backup/Restore as part of the operator, as much as the the [ectd operator](https://github.com/coreos/etcd-operator#backup-and-restore-an-etcd-cluster) does backup and restore.

However, since we are currently working on the foundations, this story is not target for 7.1

The alternative would be to expose the way how we do backup/restore as part of the update process to dedicated CLI commands which could be used from the outside. We probably would have to throw away that work later on, but with some pressure could get it into 7.1 (although not until the end of this week).

**Comment by rhuss** [comment]
I think this issue needs to be part of a larger discussion of how we want to have backup & restore be implemented from a UX POV.

One possible solution would be:

* Extend the operator's CRD to hold a 'backup.schedule' field with a crontab expression and a `backup.pvc` with a reference to a pvc which should be used for storing the backup (plus other relevant entries like rotation and retention).
* Trigger at the schedule to perform a backup automatically
* Add the result of each backup to the CR's status field
* The backup it self should do the same (or similar) steps like the backup that we do for the update in shell script. But better implemented within Golang
* Restore should be an external script which does more or less the same steps that the update Pod does when doing a rollback because of a failed update step.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11551**
