### ISSUE TITLE
Consider generating typescript models from checked in swagger file.

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1126]
Currently the `model.ts` in the UI was previous generated using a customized version of [swagger-js-codegen](https://github.com/gashcrumb/swagger-js-codegen).  I took out the web client class the generator originally created as at the time we were using restangular and I just wanted models that were aligned with the swagger file.

The main drawback to this was that the code generator only creates one large typescript file with every model in it.

I did some investigation and came across [angular-swagger-client-generator](https://www.npmjs.com/package/angular-swagger-client-generator).  It does a nicer job of generating the models by generating 1 file per swagger definition, and it also generates a service definition that internally uses HttpClient to make calls.  

A generated model looks like:

```
import { OptionalInt } from './optionalint.model'
import { ConnectorGroup } from './connectorgroup.model'
import { ActionsSummary } from './actionssummary.model'
import { ConnectorAction } from './connectoraction.model'
import { Dependency } from './dependency.model'

export interface Connector {
  icon: string;
  description: string;
  connectorGroupId: string;
  componentScheme: string;
  connectorFactory: string;
  id: string;
  name: string;
  properties: any;
  configuredProperties: any;
  uses: OptionalInt;
  connectorGroup: ConnectorGroup;
  actionsSummary: ActionsSummary;
  actions: ConnectorAction[];
  dependencies: Dependency[];
}

```

The generated service requires `HttpClient` and you can optionally specify the root URL, then all the swagger methods are like: 

```
  public enrichWithMetadata(id: string, body: , id: string): Observable<ConnectorDescriptor> {
    let uri = `/connections/${id}/actions/${id}`;
    let headers = new HttpHeaders();
    let params = new HttpParams();
    return this.sendRequest<ConnectorDescriptor>('post', uri, headers, params, JSON.stringify(body));
  }
```

The methods are documented too with description elements from the swagger file.

Now a big caveat at the moment is that our swagger file kinda sux -> https://github.com/syndesisio/syndesis/issues/87

If we keep the swagger file in SCM it'd be easy to run the generator at build time *or* we could just run it when the swagger file is updated.  There's an issue about adding it to SCM -> https://github.com/syndesisio/syndesis/issues/1121

@deeleman @kahboom question is will this be useful and would it help getting us another step towards Redux?

@zregvart CC

**Comment by deeleman** [comment]
I am kinda biased here since, as I've openly stated several times already, I'm all against having automated processes generating type definitions for a front-end application, so I'm personally against this solution.

But first let me add a remark:

> would it help getting us another step towards Redux?

We do not need to take additional steps towards Redux: We already have a working  implementation in place for Redux on the Custom Api Connectors implementation: Open up the Google Dev console, go straight to a custom connector detail page, see how the network tab shows a Http request made to the API. Go then to the connectors list: No further Http requests made; then request another custom connector: no further Http requests made; delete an existing connector: no further GET request made aside the DELETE request... Yes sir: contrary to the rest of the app, the Api Custom Connectors domain is fully stateful from the clientside (and information is requested from the API only when needed).

Do another test: download the [Redux Dev Tools](http://extension.remotedev.io/) extension and then create a new custom connector. You'll see that there're only 2 requests made to the api connectors API during the creation process. The state of the request is handled clientside and persisted in the store as you move back and forth. Once the custom connector is successfully created, you'll see that an additional request to fetch a fresh graph of connectors is made. Neither the service nor the components do that, but the Redux logic which reacts to the `new connection` action.

Redux is an architecture model that formalizes a way to create stateful SPAs, thus has nothing to do with how you interact with an API, but standard practices usually will require us to inject some properties in the domain models to signal that async operations are taking place. In other words, auto-generating entity models will not prevent us from having to create our own models either way.

Some cons I see here:

- One model per file seems a burden to me.
- Models need to be created on a per domain basis, according to the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle) observed by Angular, rather than having aggregated files, as we currently have with that infamous `model.ts` file.
- This comes withotu saying that this prevents us from having models extending application-wide interfaces (errors, sync states).
- We have already implemented a wrapper around the `HttpClient` class that also abstracts the API host and endpoint information, providing support for parameters and multipart messaging. I am not emotionally attached to that class and in order to use it we'll still have to add the URL and the params placeholders to an API config file, so we're free to ditch it at any point. All in all, abstracting Angular's own `HttpClient` behind our own proxy class is always a good idea. If we ever have to change something, we'll have to update just one file and not each and every injectable service in the app.
- How will that cli-generated services handle multipart messages with not just one but several files attached to a PUT request?
- Generating models on build time can lead to build errors as soon as there is a mismatch in the swagger files definition between environments. Such error will shine through the Angular application and we'll have to track down the exception to the offending model. Chances are this will not be that always to find.

Some pros I see here:

- Having pre-cooked models at a hand, saving us from the effort of typing whatever comes from the backend.

Aside the above, and at the risk of coming off strong... That's it to me. ;)

### Corollary
The original discussion proposed by @zregvart (and correct me if I'm wrong) was more geared towards setting common contracts between API and UI, which we obviously need, but this is a complete different fight me thinks. Ultimately, this will still turn into bloated payloads sent back and forth from the API, and a frontend application consuming models dictated elsewhere. This makes sense to me when backenders and frontenders work siloed form each other, but we all know this is not the case. :)

**Comment by gashcrumb** [comment]
> We do not need to take additional steps towards Redux

Yeah, I mean we kinda have the rest of the app to worry about though too, that's all I meant.

> Generating models on build time can lead to build errors as soon as there is a mismatch in the swagger files definition between environments.

This can be viewed as a pro as well, i.e. the model changes, related UI code breaks and needs to be dealt with, ideally in the same PR that changed the model.  The hope is that discovery of the model change is sooner using this kind of workflow, but yeah, it's not a guarantee either.

> How will that cli-generated services handle multipart messages with not just one but several files attached to a PUT request?

Yeah, a valid concern and absolutely no idea, I would assume it probably doesn't :-)

> One model per file seems a burden to me.

Yeah, it's kind of a lot of files.  And I do kinda like the idea of keeping the models kinda along with the area of the app that deals with that particular aspect of the app, i.e. integration models in the integration module, etc.

This is all great feedback!

Maybe we should just create a task to go and break up `model.ts` out into separate files and move each relevant bit into it's appropriate domain instead?

**Comment by deeleman** [comment]
> Maybe we should just create a task to go and break up model.ts out into separate files and move each relevant bit into it's appropriate domain instead?

That's a good idea. I wanted to do the same with the API endpoints definition. Instead of maintaining a `api-endpoints-config.json` filet at the top with ALL the endpoints, we might set a convention and have a particular `<domain_name>.endpoints.json` file per domain, containing only the endpoints that are relevant to that domain. If at some point we phase out any given application module, all the config boilerplate will be ditched too.

We can leverage Angular's _multi_ provider capabilities for that, as [explained here](https://netbasal.com/better-code-organization-with-angular-di-multi-option-31f691918655).

**Comment by gashcrumb** [comment]
Sounds good to me!  Created issues for each of those.  Maybe #1141 we can tackle in parts as work is done in the relevant area in the app.  I'll add a checklist of the high-level items.

**Comment by gashcrumb** [comment]
I think I'm onboard with *not* generating typescript interfaces automatically now, so let's close this one.
