### ISSUE TITLE
Gather up the output data shapes from previous steps and provide as an input to the data mapper host component

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1135]
In `step-configure.component.ts` we currently only grab the first output data shape preceding the current step.  For the data mapper we need to supply all the output data shapes from previous steps that have them.

There's support already in the current flow service to get all previous data shapes, I would store this in a separate attribute to the `step-configure` component so we can also still support steps like the basic filter, which only supports the previous steps output data shape.

Related to #1110

Created from #1114

**Comment by gashcrumb** [comment]
[this comment](https://github.com/syndesisio/syndesis/issues/1114#issuecomment-358849707)

**Comment by igarashitm** [comment]
@gashcrumb as datamapper step is a special one consumes multiple data shapes, we can even add `CurrentFlow.getPreviousStepsWithOutputDataShape(position)` and let `data-mapper-host.component` directly call it instead of let `step-configure.component` perform as a middleman. Then the array index could be used for the Step index there. @gashcrumb WDYT?

**Comment by gashcrumb** [comment]
absolutely, can just remove the data shape inputs (you'll still need the position) from the datamapper host component and let that guy grab what it needs from `CurrentFlow`.

**Comment by gashcrumb** [comment]
@igarashitm might need to refactor this function out so that data shapes for extensions can be fetched when needed by the component that needs 'em?
