### ISSUE TITLE
Syntax Highlighting Option?

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1158]
Could we enhance the form builder so it support in addition to "type" : "textarea", perhaps add a "type":"code:{language-here}" type deal?  And then perhaps use this https://www.npmjs.com/package/ng4-codemirror to provide the editor?

**Comment by gashcrumb** [comment]
Yeah, I think we could do that, basically then in the form service we'd use a custom template for that particular field and pull in whatever rich text editor we want to use.

@seanforyou23 fancy a look at this when you get a chance?

**Comment by deeleman** [comment]
That npm package is a (pretty stale apparently) NG wrapper around [CodeMirror](http://codemirror.net/).

We should build our custom Pipe or Directive around it instead of adding another outdated, unstable dependency with downstream dependencies on Angular libraries that prevent us from upgrading our own core dependency graph. Otherwise we'll lock down this project to Angular 4 forever.
