### ISSUE TITLE
Add optional top level context override parameter to ApiHttpClient.setEndpointUrl

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1211]
For the off chance we might have calls that don't fall under `/api/v1` or whatever context the usual rest service resides at.

**Comment by deeleman** [comment]
I think we can operate in two ways here:

* Create a new `setMapEndpointUrl()` method at `ApiHttpService`, which basically implements the same functionality as `setEndpointUrl()`, but with targetting the mapper endpoint instead.
* Add support for an optional second `options: {...}` parameter, where we can inject a custom host, api endpoint, whatever...

I feel more inclined on the second option, given the flexibility it provides. We can define it as this:

```
options: {
  apiHost?: string;
  apiEndpoint?: string;
  useMapperEndpoint?: boolean;
  fallbackEndpoint?: string|string[];
}
```

Where the above properties are:

* `apiHost`: A custom `http://...` host for this call, other than the one defined at `config.json`.
* `apiEndpoint`: A custom API main endpoint host for this call, other than the one defined at `config.json`. Eg: `/mapper/v1`.
* `useMapperEndpoint`: A shortcut property to tell the service to use the value of `mapperEndpoint` rather than `apiEndpoint` from `config.json`.
* `fallbackEndpoint`: A string or strings array informing of fallback URLs in case the given one does not exists.

**Comment by gashcrumb** [comment]
+1 to an `options` object for sure...

**Comment by deeleman** [comment]
Let's also add an internal safety check that appends the missing slash between the apiHost+apiEndpoint and the endpoint/url we pass to `setApiEndpoint()` or `get/post/etc` should it's missing, so the final URL is always legal.

**Comment by gashcrumb** [comment]
@deeleman I think you implemented this, didn't you?  re-open if I'm wrong...
