### ISSUE TITLE
Add UX design for AMQP Connector for enMaase and AMQ7

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#1214]

**Comment by dhirajsb** [comment]
@dongniwang I can do a quick demo on bluejeans to show what I have so far, it's pretty much a copy of the AMQ connector, except for the `brokerUrl` field being replaced with `connectionUri`.

**Comment by amysueg** [comment]
Hi @dhirajsb -
Instead of a UX story here, since the change looks like it is limited to a single field label, can we offer to do a review once you have implemented the changes? I don't think we need to provide a UX here as it will simply be a copy of the AMQ connector design. Ok with you?
+ @dongniwang

**Comment by dongniwang** [comment]
Agreed that we can perform a UX review once the changes are implemented given that we are only changing one field label. Let us know what works best for you @dhirajsb.

**Comment by dhirajsb** [comment]
@amysueg @dongniwang just a UI review works for me. I'll send you an invite for a bluejeans demo for same.

**Comment by amysueg** [comment]
In addition to the review, we have a UX story to provide the icon for this connection. See #1257 @sjcox-rh

**Comment by sjcox-rh** [comment]
Icon svg and png added in story #1257

**Comment by paoloantinori** [comment]
Hi, I'm checking the stories currently still in Inbox column for Spring 24. https://github.com/syndesisio/syndesis/issues#boards?milestones=Sprint%2024%232018-02-16&repos=105563335

Do you have any update on this?

thank you

**Comment by amysueg** [comment]
@paoloantinori @dhirajsb - I've somehow lost track of this one.
@dhirajsb - 
We were going to do a UX review once the changes were implemented. If you created a demo video and can add the link here, we'll take a look. I suspect since there was just the one field that changed that this is fine and we can most likely close this item, but I wanted to check with you first @dhiraj - thanks.

**Comment by amysueg** [comment]
@sjcox-rh  - any thoughts on this one?

**Comment by sjcox-rh** [comment]
@amysueg agreed with Amy, if there is a demo video or screenshots we can reference, Im happy to review it!

**Comment by paoloantinori** [comment]
ping @dhirajsb what would be the best demo to help UX team with reviewing the UX for this feature?

**Comment by dongniwang** [comment]
@paoloantinori - we had a review meeting this Monday, and also opened issue #1683 to track the ux review action items. Thanks!

**Comment by paoloantinori** [comment]
thanks, then I'm closing this in favour of the other issue.
