### ISSUE TITLE
[extension] Step extension that is implemented using a camel component

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1249]
So extensions now let us create Connectors from camel components.  Awesome.
We can also define Step extension which are implemented using either a Bean or a SyndesisStepExtension.  What would be kinda next level meta would could you make it easy to create a a Step extension that's implements using a camel component!

If a connector does not take connector or connection level configuration, like say a 'timer' in a route, I don't think it make sense to have to create a connection for it.   Yes, I know you can't use a Step as the first item in an integration flow, but once we blur the distinction between steps and connections, that will go away. 

@rhuss @lburgazzoli @kcbabo what do you guys think?

**Comment by kcbabo** [comment]
The more flexible the better IMO.  My only question would be how much extra work this is so that we can prioritize it within our existing backlog.

**Comment by lburgazzoli** [comment]
@chirino this is a question I wanted to ask because I did try to create an extension wrapping the timer component and of course you need to create an empty connection to be able to add it as first step. About making it easy to make steps out of a camel component we have some idea but we still need to refine it.

About "connectionless" connector, the support is already there on integratin runtime side by [SimpleEndpointStepHandler](https://github.com/syndesisio/syndesis/blob/master/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/handlers/SimpleEndpointStepHandler.java) so it is mainly an ui/ux thing. 

Wondering if we should drop the concept of connector in favor of a good old endpoint :)

**Comment by lburgazzoli** [comment]
keep it open
