### ISSUE TITLE
developer handbook doesn't have the workflow content

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1266]
We added some additional content documenting developer workflow but it hasn't made it into doc.syndesis.io, not sure if there's a build error or do we need to deploy them manually?

**Comment by rhuss** [comment]
I've seen that @kahboom added the workflow to the end, but the content is messed up. I'm going to fix this today as I have to update the docs for `syndesis deploy` and `syndesis release` anyway.

BTW, you can always recreate the docs yourself locally by

```
syndesis doc
```

and then open it from `doc/sdh/output` (you need to have a running Docker daemon though so that the asciidoctor image can be loaded)

**Comment by rhuss** [comment]
fixed with #1274
