### ISSUE TITLE
Lets add version information for the UI

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1368]
Idea from https://github.com/syndesisio/syndesis/issues/1010#issuecomment-362237604 let's have a version.json that we package and can use to lookup versioning information for the UI.

**Comment by deeleman** [comment]
This is much needed. However, we should use `package.json` instead. 

As a rule of thumb in JavaScript UI projects and monorepos, maintainers will want to use the `version` property of `package.json` to inform of the what version the UI is. Bumping the UI version can be done automatically upon launching new releases of Syndesis by running `npm version` from the CI build script (it can be run by passing a specific semver string or just by using a semver noun: _major_, _minor_, _patch_). 

Given the nature of our monorepo, we can strive for:

- Keep both backend and frontend on the same version. This reinforces the coupling between the REST API and the consumer UI client, which has pros and cons from an UI architectural POV.
- Maintain a specific version for the UI, in parallel to the backend version This makes a lot of sense since such version will inform of breaking changes or new features now available on the UI which are not necessarily tied to changes in the REST API.

**Bonus**: The version information available from `package.json` can be injected into the app on build time as part of the Metadata information (we have already a Redux slice of state for metadata information which is waiting for being populated with ENV variables like this and will gain more importance in a near future). From that moment on it will be available for any new user downloading Syndesis. And this is a big deal, because if we modify the server headers to inform about the latest UI version on each Http call (which should be a trivial action since the backend can access package.json too), we can automatically notify the client whenever the UI version in use becomes outdated and needs to be refreshed. This will comes in handy when new important bugfixes are merged and the end user is consuming a cached version of Syndesis in a browser tab that has not been refreshed in a while. Think of the update notification mechanism of WhatsApp or Telegram web clients as an example.

More on the npm version command and why it does matters: https://docs.npmjs.com/cli/version
