### ISSUE TITLE
[Question] Where can I read the docs?

### ISSUE THREAD

**Issue by blaggacao** [syndesisio/syndesis#1399]
Not claiming to be ignorant, I might ask where to find the docs published in a readable format?
I want to write and deploy a transformation broker based on syndesis in production, if this is something which is already safely recommendable at this point in time...

/cc @marcusbiel

@davsclaus If I understand things right, you are the lead developer of Apache Camel and syndesis is basically build on top of the buzzwords that are presently listed on the apache camel homepage as the projects that can leverage apache camel. Is that about close to the reality?

**Comment by kahboom** [comment]
Hi @blaggacao - I can't comment on that being or not being safely recommendable at this point, but these may be what you're looking for (note: they need some work):

- [Syndesis Developer Handbook](https://doc.syndesis.io/)
- [Red Hat JBoss Fuse 7.0-TP Fuse Ignite Sample Integration Tutorial](https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/pdf/fuse_ignite_sample_integration_tutorial/Red_Hat_JBoss_Fuse-7.0-TP-Fuse_Ignite_Sample_Integration_Tutorial-en-US.pdf)
- [Syndesis Contribution Guidelines](https://syndesis.io/community/contributing/)

Not sure what you mean with your second question. Syndesis does leverage Camel for its integration services, but it's part of a platform that runs on OpenShift or Kubernetes. For instance, [ActiveMQ](http://camel.apache.org/activemq.html) is one of the supported Camel components known in Syndesis as a Connector (though, really, the term 'Web Service' seems more apt here), which, as configured entities, are referred to as Connections from the perspective of the user. These can later be used when creating Integrations between one or more Connections. Data transformation of the payload between these configured services/Connections can be set up when creating an Integration, should that be something the user is interested in. And, yes, Claus is indeed Mr. Camel. :)

Hope that wasn't an over-explanation and that it more or less addressed your question, otherwise, surely @rhuss can chime in. Good luck! 👍

**Comment by blaggacao** [comment]
As a stranger to the fuse/fabric/camel/syndesis continuum, I appreciate your answer.
I think, first and second link seems a hit.. I'll read through, get more involved and hopefully come back to the recommendations in the third link, soon.

I already did a local deployment with minishift but then I was like, "Ok looks nice, now what can I do with this?" - And now I think I've got a practical use case...

**Comment by davsclaus** [comment]
Good answer @kahboom 

@blaggacao yeah Syndesis uses Apache Camel as runtime for the integrations, but its much more than that as Rachel explains.

With Camel as the runtime you get the benefit from its huge community and 10+ years of existence and therefore a mature and hardened set of components/connectors.

**Comment by zregvart** [comment]
I'm closing this as answered.
