### ISSUE TITLE
"Edit" option does not work on Integration Dashboard

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1459]
The "Edit" Option does not work, in fact none of the options in this drop down box work.

![edit-button-fails](https://user-images.githubusercontent.com/8625482/35909550-efa64fc8-0c2e-11e8-993d-998abe41df21.png)

**Comment by honghuac** [comment]
Here is the trace from Google Chrome, https://gist.github.com/honghuac/ee438e250a4df5d44bd49e3bc06e2a10

No javascript errors. Only "502 Bad Gateway" and "Unexpected end of JSON input" errors.

**Comment by paoloantinori** [comment]
Hi @honghuac thanks for all your report. I will try my best to address them.
Before starting,  and to avoid to duplicate the same information everywhere could you answer to these questions?

Which deployment process are you following?
Are you using the `LATEST` docker images?
How often do you redeploy?
Are you planning to retest some of these notification yourselves ?(some of these might be fixed already as part of other stories, apparently unrelated to the what could seem the root cause of a problem)

Those answers will help me to understand where to verify if the issues are still there or already fixed, and also will give me hints about different self-debug tips I can give you.

thank you

paolo

cc @rhuss @aileenc @dsimansk

**Comment by gashcrumb** [comment]
This works on master, think this is environmental...
