### ISSUE TITLE
[Integrations] Make whole integration item area clickable 

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#1467]
Only the blue area is clickable but the whole item area is highlighted when hovered by mouse.
![listclickablearea](https://user-images.githubusercontent.com/8707251/35922958-478ebfe6-0c1f-11e8-85ca-1ca8a3250c74.png)

This problem exists also on **Home** and **Customizations** pages.
I can create the separate issues if the problem can't be solved at one place.

**Comment by seanforyou23** [comment]
@mastepan thanks for pointing this out. The entire area should be selectable, but this is a change needed at the patternfly-ng level, not with Syndesis UI specifically. I've raised an issue and linked it to this one. Once the fix is in place and we pull in latest patternfly-ng, we'll automatically receive the fix across the board, in the other places you mention (home, customizations, etc.) as it's a generic issue with the core component.

I'll close this issue and we can track progress via https://github.com/patternfly/patternfly-ng/issues/317

Thanks again.
