### ISSUE TITLE
`userMsg of null` error message appears

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1531]
![usermsg-null](https://user-images.githubusercontent.com/8625482/36106316-edb90daa-1051-11e8-9f8d-8f558283c567.png)

This error message appears during a API Client Connection setup process. Note the swagger document used is http://petstore.swagger.io/v2/swagger.json (a valid document without errors).

**Comment by zregvart** [comment]
Looks like an invalid or incomplete response was received from the backend. @honghuac can you peek into the developer tools and see in the network tab what response was given when you click on _Create Connector_ button?

**Comment by honghuac** [comment]
@zregvart No surprises here...the usual "502 Bad Gateway" error shows up in Developer Tools mode. BTW, it took a redeployment of the REST Pod to finally get the API Client Connector wizard to work smoothly

**Comment by zregvart** [comment]
Seems to me like the rest pod intermittently fails. I've seen this with the liveness probes, though not sure if it's something we need to fix on our end or if it's the environment (i.e. the OpenShift cluster Syndesis is running on). Since you seem to be able to reproduce this regularly perhaps we can start by eliminating probes or proving them to be the root cause by removing them.

You can do that by editing health checks the deployment of the rest pod:

![screenshot-2018-2-12 openshift web console 1](https://user-images.githubusercontent.com/1306050/36115175-97a74630-1032-11e8-826f-f7ff0ff4cd81.png)

And removing readiness check:

![screenshot-2018-2-12 openshift web console](https://user-images.githubusercontent.com/1306050/36115184-9e3a67d4-1032-11e8-8656-96dd565eaaea.png)

**Comment by honghuac** [comment]
@zregvart I have removed liveness probe. All seems to go well with tests, will keep monitoring.
