### ISSUE TITLE
[UI] Import integration multiple toast notifications

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1545]
I see too much enthusiasm here, for a single successful import operation

![screenshot from 2018-02-13 17-27-23](https://user-images.githubusercontent.com/1520602/36161180-55b8085c-10e3-11e8-8edc-86fb064be214.png)

**Comment by kahboom** [comment]
LOL @paoloantinori you crack me up

**Comment by deeleman** [comment]
I wonder wether I'm doing something wrong or not but I follow these steps:

1. I created an integration and exported in order to use as a blueprint for this issue. I removed the integration to start afresh then.
2. I got o the Integrations page and import the integration file
3. the integration is validated and imported. I click "Done"
4. Nothing happens. I get ZERO toast notifications.

Is there anything I'm missing out here? @paoloantinori @kahboom

**Comment by paoloantinori** [comment]
Just did the same on today's master branch, and I have seen the same behavior.

Integration was imported correctly, and I have been able to Publish it, but no feedback from the UI import operation in form of toast notifications.

@kahboom can you check this?

**Comment by gashcrumb** [comment]
This is fixed now.
