### ISSUE TITLE
UI: checkboxes doesn't seem to take into account default values

### ISSUE THREAD

**Issue by oscerd** [syndesisio/syndesis#1560]
![s3-poll](https://user-images.githubusercontent.com/5106647/36208137-624e7140-1198-11e8-964b-635352f3f9cd.png)

the checkbox showed in the screenshot has a default Value equal to false

https://github.com/syndesisio/syndesis/blob/master/app/connectors/connectors/aws-s3-connector/src/main/resources/META-INF/syndesis/connector/aws-s3.json#L247

but is checked anyway by default.

**Comment by gashcrumb** [comment]
Huh, thought we just fixed this, @seanforyou23 want to have a peek?

**Comment by oscerd** [comment]
My running syndesis is at this commit 90e1e38baf064b71ef5a1fcdb0581d4298a5c018

**Comment by oscerd** [comment]
I guess setting null as default value is really ugly. @lburgazzoli what do you think about this?

**Comment by lburgazzoli** [comment]
On backend side the definition of a property is all done using strings, so we can't really return a true boolean value. IMHO the UI should honor what the property definition gives and properly handle default values according to the type of the property. Going with null to mean false is a little ugly because then one could type "false" by mistake and the value will be interpreted as true ...

**Comment by gashcrumb** [comment]
Yeah, we could add an additional function to the form factory service on the UI side to massage the values appropriately according to the form configuration.  I had created this issue when I had to coax out `"null"` for unset fields, probably worth rolling this work into it also -> https://github.com/syndesisio/syndesis/issues/1250

**Comment by seanforyou23** [comment]
Ok cool, fair points all around. Thanks for the feedback everyone - I will update the UI to better handle these cases, just wanted to make sure we had proper reasoning before jumping in. Thanks!
