### ISSUE TITLE
When action doesn't have any parameters it's difficult to change it

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1587]
If I have an API connector based action in the integration, and want to change it for another action there is a timeout set on the last page of the wizard that inhibits me in doing so.

Looks like:
![issue](https://user-images.githubusercontent.com/1306050/36269692-11be7f26-127a-11e8-8425-b2d6454c9de3.gif)

**Comment by gashcrumb** [comment]
Maybe I should just take out that automatic transition and leave the info message there.

**Comment by gashcrumb** [comment]
@sjcox-rh @dongniwang ?

**Comment by michael-coker** [comment]
@gashcrumb we brought this up on our notif/uxd call today and agree that we should just remove the automatic transition. 

The same applies for the automatic transition in the integration editor work flow. For example, if you choose "twitter" as your start connection in an integration, and choose an action that has no configurable properties (like "Mention"), the output should read "There are no properties to configure for this action") (what's already there) and should have the "< Choose Action" and "Done" buttons below it, instead of automatically transitioning to the finish connection step.
