### ISSUE TITLE
DB to DB integration does not work.

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#1644]
Steps to reproduce:

1. Select Create Integration.
2. Select start connection PostgresDB.
3. Select action "Periodic SQL invocation" and specify query
4. Select finish connection PostgresDB.
5a. Select action "Ivoke SQL".
(alternative: 5b. Select action "invoke stored procedure")
6. add datamapper step
7. specify integration name and hit "publish" button.

at this point in **5a** alternative this error occurs at web console:
![dbtodberror1](https://user-images.githubusercontent.com/2714974/36547898-349b7074-17ef-11e8-8ea3-1b29641935e1.png)

[error1.log](https://github.com/syndesisio/syndesis/files/1748514/error1.log)

in **5b** alternative web console error looks like slightly different:
![dbtodberror2](https://user-images.githubusercontent.com/2714974/36547985-6b9115ac-17ef-11e8-83ab-d53de4686360.png)

[error2.log](https://github.com/syndesisio/syndesis/files/1748520/error2.log)

In both cases I don't see any errors on rest pod log.

**Comment by kahboom** [comment]
Could this be related to #1566 ?

**Comment by gashcrumb** [comment]
I think it's just an issue in the selector, but really the problem is the detail page itself is half redux and half not, and the not-redux part is a bit dodgy, in this case there's likely a race condition grabbing the integration ID from the angular router and the code fetching the metrics from the redux store.  We probably need to add the angular router to the redux store as well so that the selector for this view can have the router state available as well.

**Comment by gashcrumb** [comment]
Nope, I'm wrong, it's because when you first publish there's no metrics available so the backend returns nothing and the code is expecting to at least get back an empty object I think.
