### ISSUE TITLE
Drop dev and non restricted templates

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#1668]
As s2i is now reliably working we should remove dev and non restricted templates, @rhuss can you take a look ?

**Comment by lburgazzoli** [comment]
@rhuss I think we can close this right ?

**Comment by rhuss** [comment]
It's dropped for the s2i build. We need docker-only builds only for CI and release builds (that's why there is still a --docker).

However, the -dev template still does something which we are not yet included in the operator, like adding JAVA_DEBUG and setting the UI config to allow localhost access (wonder why @gashcrumb didn't already slapped me when using the operator approach as the local UI development probably doesn't work)

Let this open until #3202 is fixed.

**Comment by zregvart** [comment]
I think we can close this, `syndesis-dev.yml` no longer exists and the other issues can be addressed in #3202.
