### ISSUE TITLE
Follow up from UX review of AMQP connector

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#1683]
1. Add the icon for this connector. Icon delivered via #1257 

2. The field ordering on configuration pages is random. I believe that @seanforyou23 resolved this "globally" via another issue. Could that be applied here for the configuration pages associated with AMQP Connector?

3. The "Type" drop-down selector includes "No Type" and "Any Type". Investigate the difference between these two selections and describe via a tooltip associated with the "i" information icon.
UX should talk with @gashcrumb about this one.

4. Currently, on one of the configuration pages, there is a checkbox with text to the right "Persist". Look at adding a label for this checkbox as a field on the page (after Name and Description). The label should be "Persist Message" and the "i" information icon tooltip should describe that selecting this checkbox persists the message to the database thus guaranteeing message delivery (or something like that)

5. Message Selector field: The user can type in a complex expression. However, there is no way to validate the expression since there is no standard API to validate and the expression language is specific to the broker or provider. Therefore consider how to add some help to the page so that a user could theoretically go to another page for help. I'm concerned about where this would actually link. Linking to an external page can be problematic since we have no way of knowing whether the page exists... at any point in time. For example, "See amqp.org for more information about entering expressions in the Message Selector field" .... does that even make sense or could a user find what they need on that page? An alternative to that approach would be adding hint text underneath the field to show an example of some syntax, letting the user know that an expression is needed. And then the "i" information icon tip text should indicate that the expression is dependent on which message broker is used. This is not particularly user-friendly, but will at least be accurate. Thoughts?

I couldn't add the AMQP Epic to the "Epics" field perhaps because it is closed, but this is part of the Epic #1216

**Comment by dongniwang** [comment]
1. For icon, @gashcrumb, @seanforyou23, I'm not familiar with how we add icon, can you please help? 
![screen shot 2018-02-26 at 3 00 54 pm](https://user-images.githubusercontent.com/24943812/36692379-e5acdd26-1b05-11e8-9b68-a8d4f480132f.png)

2. The field ordering is shown in the screenshot below. Can we re-order the fields? Also, would it be possible to make both the certificate fields a multi-line entry fields? 
![screen shot 2018-02-26 at 3 02 22 pm](https://user-images.githubusercontent.com/24943812/36692478-25e20e8e-1b06-11e8-9613-47df84603a60.png)

3. The issue with "No Type" and "Any Type" - what's the difference between these two options? Any ideas? @gashcrumb Also, the "next" button on this screen should be "done" and on the previous screen, we should have "next" instead of "done" (I know this page is WIP, please let me know if you have any questions)
![screen shot 2018-02-26 at 3 04 54 pm](https://user-images.githubusercontent.com/24943812/36692596-89589d98-1b06-11e8-9841-54d2be73b443.png)

4. Screenshot for persistant 
![screen shot 2018-02-26 at 3 07 43 pm](https://user-images.githubusercontent.com/24943812/36692705-d21936e6-1b06-11e8-99b3-4a4c457d54e0.png)

5. Message selector screenshot:
![screen shot 2018-02-26 at 3 11 32 pm](https://user-images.githubusercontent.com/24943812/36692876-65385a24-1b07-11e8-8cbe-437c62d5da2c.png)

cc: @dhirajsb @amysueg @TovaCohen

**Comment by gashcrumb** [comment]
>The issue with "No Type" and "Any Type" - what's the difference between these two options? Any ideas? @gashcrumb Also, the "next" button on this screen should be "done" and on the previous screen, we should have "next" instead of "done" (I know this page is WIP, please let me know if you have any questions)

So 'no type' is that the connection has specified `none` for the input type, meaning that it doesn't accept an input I think.  'any type' means the connection doesn't specify any particular data shape as it's input.  Note actually this can mean input or output, this page shows up for either case depending on where the connection is in the flow.  As of right now the form exposes the data shape object as-is, so I kept the 'none' vs 'any' to avoid mucking up the underlying datashape object.  But I think in most cases 'none' can actually be hidden from that form, it's really only a valid choice for the input data shape for the start connection and the output data shape for the end connection.

Implementation wise, 'next' vs 'done' here has really gotten complicated, as each of these views don't really know if the user is actually done, or if there's more stuff that needs to happen after that view.  I kinda want to change all the buttons to say 'next' at the moment to be honest, at least until I work out how to have consistent state in the editor with all the various things that can happen when configuring a step.

> Can we re-order the fields? Also, would it be possible to make both the certificate fields a multi-line entry fields?

The form should be getting displayed in the order that comes back from the backend, we can also specify an order [client-side in the short term](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/connections/common/configuration/configuration.service.ts#L35-L42).  Ideally https://github.com/syndesisio/syndesis/issues/1204 would be implemented in some fashion.

To make the certificate fields multi-line the connector form config just needs to specify `textarea` instead of `string`.

**Comment by dhirajsb** [comment]
I created distinct issues to track individual progress for the following:

* Missing icon #1699 
* Field order #1696 
* Data shape page buttons #1700

**Comment by dongniwang** [comment]
I think #1699, #1696, and #1700 are all closed now. 

As for "No Type" and "Any Type" , if we don't have a way to dynamically display the options, can we at least add an "i" icon next to the field label for more information on these options. WDYT, @gashcrumb @dhirajsb

**Comment by dhirajsb** [comment]
Yeah, I don't have issues for persistent field label or message selector syntax hint, since those seem like general UI enhancements that would apply to all connectors. Do you want to create those as feature requests for UI team?

**Comment by dhirajsb** [comment]
Other issues from this review are done, I think we can close this issue now.

**Comment by amysueg** [comment]
per @dhirajsb closing
