### ISSUE TITLE
Metrics UI missing values

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1730]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
A number of metric values are not set in the UI and the UI is not refresh with the underlaying data changes.

## Screenshot
<img width="1315" alt="screen shot 2018-02-28 at 11 51 20 am" src="https://user-images.githubusercontent.com/35576/36800571-d53bde32-1c7d-11e8-9f0a-5b9521e0a983.png">

While the underlaying api says:
<img width="839" alt="screen shot 2018-02-28 at 11 52 58 am" src="https://user-images.githubusercontent.com/35576/36800815-714ea0d4-1c7e-11e8-8adc-1a9f66a2de2e.png">

The last process message should be populated, the uptime is wrong and the data is not refreshed. When hitting refresh myself the tab changes to the 'Description' tab.

**Comment by deeleman** [comment]
The implementation was done according to the data spec provided in the original issue linked above. The underlying API schema posted in this issue does not match [the "spec" provided](https://github.com/syndesisio/syndesis/issues/1065#issuecomment-358664317). The internal store is updated at constant intervals and replaces its current state by the new one that, unfortunately, now we learn it points to the wrong properties in the returned API message.

This proves how much we need to get better at documenting issues. Otherwise one suddenly discovers that our hard work has evolved to become a bug. And that is really frustrating.

> When hitting refresh myself the tab changes to the 'Description' tab.

Exactly. That component is not route-based and thus has no UI state implementation for its subviews, since this is not part of the original issue acceptance criteria. If subview persistence is required, please open a feature issue.

**Comment by KurtStam** [comment]
@deeleman so can you fix it?
