### ISSUE TITLE
Uptime given in integration summary shows 28 days

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1764]
## This is a...
<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

On the newly provisioned syndesis if a integration is published the integration summary shows 28 days. I think without any uptime we get uptime from the maximum retention.

## Expected behavior

I'd expect the uptime of a newly published integration to be 0.

## Screenshot

![screenshot-2018-3-1 syndesis](https://user-images.githubusercontent.com/1306050/36867128-84686ea4-1d94-11e8-8883-22592bd58ef1.png)

## Tasks involved / Steps to Reproduce
1. Create new integration
2. Publish
3. Examine integration summary

**Comment by KurtStam** [comment]
Yeah this is the same as: https://github.com/syndesisio/syndesis/issues/1764

**Comment by deeleman** [comment]
The reducer initialized the metrics graph as 0 (which was wrong anyways and now it is initialized with the local timestamp of the time that the metric is initialized in the UI store) in the hopes that the local persisted information would be soon squashed by the data coming from the API. Unfortunately, the data coming from the API lacks both the `start` and `lastProcessed` properties for all additional integrations, so that information is first wrongly displayed and then is reset to null.

```json
{
  "messages": 0,
  "errors": 0,
  "integrationDeploymentMetrics": [],
  "id": "-L6au7TYVq6u1sYX99S6"
}
```

I've introduced a change in the UI implementation (which will be pushed along with some changes required for #1764) to prevent this wrong initialization but the data graph needs to be fixed in the backend tho. Reassigning...

**Comment by KurtStam** [comment]
@zregvart are you seeing this when there are no integrations running yet?

@deeleman If happens when there are no integrations running then I would expect the uptime to be N/A. Which is why it's also missing from the API response..

**Comment by deeleman** [comment]
@KurtStam What should the UI render then? `n/a` or a timestamp?

**Comment by KurtStam** [comment]
@deeleman I think n/a until we have our first integration from then on it will be a timestamp.

**Comment by zregvart** [comment]
> @zregvart are you seeing this when there are no integrations running yet?

Yes, the integration is still publishing at this point.
