### ISSUE TITLE
Investigate simplifying adding steps to an integration (combine "step" & "connection")

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#1830]
## This is a...
<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When building an integration, currently the UI guides the citizen integrator to create starting and ending connections. Once she does, she must then decide whether to "add step" or "add connection".  Having to make this choice is potentially confusing to new users who may wonder what is the difference between a 'step' and a 'connection.'

## Expected behavior
Product management @kcbabo has requested that UX investigate design ideas for combining these into one action which would simply be adding a step. The user is then presented with a single set of cards from which she would choose. 

Design considerations:
1. Click "+" in the IVP to display tile view that includes connection cards as well as cards for log, filter, data mapper and other items currently referred to as "steps”
2. Icons will need to be created for each "out of the box" step
3. Provide a default icon for custom steps created using extensions; custom created steps would use this icon
4. Connections are considered a special type of step, so provide a way to filter by connections (only show connections)

## Screenshot

<img width="353" alt="screen shot 2018-03-05 at 3 32 57 pm" src="https://user-images.githubusercontent.com/31700119/36998705-da7e1452-208b-11e8-987f-ad797e297145.png">

## API Endpoints and Schemas

@TovaCohen @sjcox-rh @dongniwang @seanforyou23 @michael-coker

**Comment by TovaCohen** [comment]
In case this is helpful - 

- I updated the user doc to say that an integration is a set of steps. Each step operates on data. Some steps connect to applications or services and these are referred to as connections. Other steps operate on data between connections. 

- If terms are needed, then I suggest "connection step" and "inside step". 

- Currently, when we refer to custom steps we always mean a step that operates on data between connections. If we combine "inside steps" and "connection steps" into one set of things for the user to choose from, and the user filters for custom steps, would the user see connections that are created from custom connectors?

**Comment by amysueg** [comment]
Thanks @TovaCohen - a few comments here

"I updated the user doc to say that an integration is a set of steps. Each step operates on data. Some steps connect to applications or services and these are referred to as connections. Other steps operate on data between connections."

Perfect!

"If terms are needed, then I suggest "connection step" and "inside step"."

I'm not a fan of  "inside" step I think because the modifier refers to its position in the flow, but then connection steps can also be "inside" the flow, right?  Could we use something less "positional" and more about the function, but abstract enough to convey something? Perhaps "process step" or "activity step" or "task step"?

I'm not following the last bullet, can you send a link to the documentation for this part so I can get more context?

**Comment by gashcrumb** [comment]
What about *processing step*?

**Comment by amysueg** [comment]
i don't like "processing" because it could be construed as  or confused with "processing this step" - i'd prefer "process"

**Comment by TovaCohen** [comment]
All steps:
- are inside the flow
- operate on data
- process data
- perform tasks
- represent activities

From the POV of a user, the only thing that distinguishes them is that some steps happen inside Ignite and some steps happen outside Ignite. We might not need terms. You might find a way to design the UI to avoid the need. But if not, then maybe "between step" or "stitch step" or "bridge step" also might work. 

For the last issue I mentioned, I don't have doc that I can point you to. In TP3, when the user uploads an extension, it always defines a step that operates on data between connections. We refer to this as a custom step in the TP3 UI and doc. When the user is creating an integration, after adding the start and finish connections, the user clicks Add a Step and the custom step they added is in the list of available steps. In the Choose a Step page, the user can filter on Custom Steps so that the UI displays only custom steps. 

TP4 adds the ability to upload an extension that defines a custom connector. When a user creates a connection from a custom connector, it will be reasonable for the user to view that connection as a custom step, which happens to be a connection. 

In the description of this issue, under "Design Considerations" it sounds like you might decide to combine what we currently refer to as steps with connections. When the user wants to add a step to an integration we might present one set of things to choose from. That set contains both connections and also steps that operate on data between connections. If you decide to do that, and if there is a filter where the user can say that they want to see only custom steps, then I think that a user will expect to see connections that they created from custom connectors. I just want to point out that this should be considered in the design. In other words, I think it is reasonable for a user to think this way:
1. I uploaded an extension that defines a custom connector.
2. I created a connection from my custom connector. 
3. My connection is a custom step. 
4. I want to add a connection that I created from my custom connector.
5. I'll filter on custom steps to make it easier to select the connection I created from my custom connector. 

Does that help?

**Comment by sjcox-rh** [comment]
Here are the designs for combining the functionality of adding a step and connection in an integration: 
https://redhat.invisionapp.com/share/EWGS7DL3D68

Please review and leave comments, thanks!

@gashcrumb @amysueg @dongniwang @TovaCohen @kcbabo

**Comment by TovaCohen** [comment]
I added comments to the Invision designs on pages 4, 5, 7, 8, 11, and 12.
Option 1 does a better job of treating everything that happens in an integration as a step. 
Option 2 continues the separation of connection steps and between-connection steps, or whatever we decide to call them. 
I think that the term "Process Steps" is misleading because all steps do processing. I prefer a term such "Built-in Steps". 
If we use the term "Custom Steps" then we need to be clear about what it refers to. In particular, does it refer to a connection that a user creates from a custom connector?
Thanks for all the great ideas SJ!

**Comment by sjcox-rh** [comment]
Thanks for all the feedback @TovaCohen. Was very helpful getting your insight on more appropriate terminology to help differentiate the steps. Also, thanks for pointing out that API connectors wouldn't show up in this view by default unless connections were created using them. Will make all the updates once I get all the feedback!

@kcbabo For custom steps, would you assume that connections created using API connectors would be considered "custom" or would custom only refer to built-in steps created using tech extensions?

Also, @rhuss, any idea who would be the feature owner for this?

Thanks!

**Comment by sjcox-rh** [comment]
@gashcrumb @TovaCohen, thanks for all your feedback on the designs. Please review [Add to Integration - V2](
https://redhat.invisionapp.com/share/PWH14PWMCXE) which covers a couple big changes.

First, introducing the ability for the user to toggle view modes. Will show a mini card view by default to account for users with a large number of connections/steps.

Also, providing a different option 2 which utilizes tabs.

@kcbabo @paoloantinori, please feel free to review as well and let me know who should be included in this discussion as I'm not sure! Also, is there a feature owner assigned?

FYI, @amysueg @dongniwang

**Comment by paoloantinori** [comment]
Hi @sjcox-rh , until we release GA we are focusing only on bugs, not new development, so we won't have a Feature Owner assigned until after GA.

**Comment by kcbabo** [comment]
I vote option 1.

One change: we shouldn't separate built-in and custom steps.

**Comment by gashcrumb** [comment]
I'm super -1 to overloading the filter in the designs to narrow down the list to steps or connections like that.  I think it's going to bring some technical challenges *and* I don't think it's going to wind up being usable, the free-form text input becomes a select control when you select type, I hates it :-).

I think option 2 is maybe a better direction, but then I think by default we kinda want to show "all" kinds of steps?  But then the tab names get kinda clunky perhaps, i.e. "All", "Connections", "Processors (or whatever)"

As part of this we should really drive the "type" filtering based on some metadata in the objects *you know, like tags :-)* and make that a more obvious control to narrow down the list than tabs or the patternfly filter thingie.  But as I think of this, if we use this approach + tabs, I envision too many tabs fairly quickly.  In fact, if these categories are at all data-driven, we want something more list-y instead that could handle larger numbers of things.

Maybe break out the "type" filtering into it's own control using a bootstrap select kinda control so it's a separate thing from the name filter?

**Comment by sjcox-rh** [comment]
@gashcrumb Im going to update option 2 to include an all tab which will be default. I think this will be a combo of both designs and should work pretty well.

@kcbabo I'll combine Builtins and Custom Steps to one tab which will help reduce amount of tabs.  What do you think about the name "Processors" that Stan suggested above?

So well have three tabs:

- All (default)
- Connectors
- Processors

**Comment by kcbabo** [comment]
Sorry if I missed it in the thread, but what's the reason for using Processors instead of Steps?  That would keep the naming consistent with Step Extensions.

**Comment by sjcox-rh** [comment]
Ahh, makes sense. Processors was just a suggestion. I'll use Steps!

**Comment by sjcox-rh** [comment]
@TovaCohen That is no longer a requirement to filter by type, we will only support filter by name, based on version 3 of the designs.

@kcbabo @gashcrumb @paoloantinori @chirino Please review V3!

https://redhat.invisionapp.com/share/X6K0SKUWZFG

Design tracker is also updated

**Comment by TovaCohen** [comment]
I added comments on pages 3, 5, and 6 to suggest help text. 
In each tab, will the cards appear in alphabetical order by name?

If everyone else is happy with the **Choose a Step** page having three tabs:
**All**&nbsp;&nbsp;&nbsp;&nbsp;**Connections**&nbsp;&nbsp;&nbsp;&nbsp;**Steps**
Then I will back off. But I still think this is confusing. If I am on the page for adding a step,  it doesn't make sense to me that I can select a "Steps" tab. I would rather see no tabs. The user can filter on the name of the step. That seems less confusing and helpful enough to me. 

Can we show the three-tab design to someone who is not familiar with the UI and ask them what they think?

**Comment by amysueg** [comment]
@TovaCohen 
Thank you for the help text, it's great.
Yes, I believe the cards will appear in alphabetical order by name in each tab.

To your main point, I see what you are saying. I agree that it does seem strange to have "Add a Step" as the main action that drives this page from the Integration Visualization panel, and the resulting page title on the right side is "Choose a Step" -- and have a tab called "Steps". 
You are right - we've been staring at this for too long and miss some basic things.
I'm pretty sure that was the reason for coming up with a name other than "Step" for that third tab, thus "Processor" or "Process" or something, just not step.

@kcbabo If you follow this logic, and I think it makes sense, can you think of an acceptable term we could use to replace term "Step" as the label of the third tab?

Luckily, we have some time since I learned today that this work is not scheduled for 7.1. Therefore we could, in fact, do some "cafeteria" testing to get some feedback. 

@sjcox-rh @dongniwang let's discuss.

**Comment by amysueg** [comment]
Just for comparison, in Parabola.io there are 4 tabs: All, Sources, Transforms, and Destinations. Sources and Destinations are our "Connections" and Transforms are the kinds of actions that we currently also refer to as Steps.  I like the idea of giving an identity to the non-connection steps by using a name that has something to do with data manipulation or transformation. We can certainly wait for feedback but I think we could also get ahead of this issue so this is food for thought.
![parabolaexample](https://user-images.githubusercontent.com/31700119/41112250-731f732c-6a4c-11e8-88a5-14cff877b3cb.png)

**Comment by gashcrumb** [comment]
Had a chance to look through v3 finally, LGTM!

**Comment by chirino** [comment]
On day when we have extra cycles it would be cool to see how often users actually switch tabs.  I wonder if we could add some sort of analytics tracking to angular apps (kinda like google analytics).

**Comment by gashcrumb** [comment]
So just to reiterate, +1 from me.

One comment, looks like going forward the editor is the only place where there's circles around the icons now according to the designs.

**Comment by heiko-braun** [comment]
@sjcox-rh @kcbabo @gashcrumb Design ready and approved?

**Comment by sjcox-rh** [comment]
@amysueg @dongniwang These designs should be good to go. Took into consideration how the updates to the IVP designs would impact this and since these designs focus on changes within the content/config area, I think we are good to go.  When we get to the point where the IVP is updated, I can update these designs if needed to match.

@heiko-braun Designs are ready and approved, unless something has changed since @gashcrumb and @kcbabo signed off :]
