### ISSUE TITLE
Integration Detail: history/version listing is missing

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1880]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
History part of detail page is not showing and no sign of it in HTML code also.

## Expected behavior
https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md#no-draft

## Screenshot
![screen shot 2018-03-07 at 16 46 43](https://user-images.githubusercontent.com/5637792/37102045-3a1fef6a-2227-11e8-8fa4-55bfe00e489c.png)

**Comment by gashcrumb** [comment]
This commit nuked it -> https://github.com/syndesisio/syndesis/commit/3b290bf89a8886b9656f1bcc4eec21b479fd91fc#diff-0ced492a52fd0b9484ab4aa9677b55b2L71

@deeleman wonder, would that be a lot of work to add that section back in?

**Comment by deeleman** [comment]
@gashcrumb @dsimansk Short answer: Not at all. The only issue is that we need to clarify, from once and for all, what dow e want at that page, since the activity tab was [removed for a reason](https://github.com/syndesisio/syndesis/pull/1488#issuecomment-369005139).

Hopefully the new issue template, which forces feature owners to create a centralized source of truth in the form of a formalized _Definition of Done_ will help preventing this confusions in the future. TBH I do not know what's the way forward for this issue now.

**Comment by gashcrumb** [comment]
I suspect there may be a communication gap here, we have had designs that show the history tab and table, they're here ->

https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md

These were designed before the tabs were introduced but still relevant in that we need to provide a feature to allow the user to rollback to a previous known good deployment etc.  I suspect that the  history tab being omitted from the designs around activity/metrics was an oversight.

@sjcox-rh @dongniwang can you guys confirm the above?  Thanks!

**Comment by dongniwang** [comment]
@gashcrumb - yes! The integration details page should look like this (with 3 tabs): https://github.com/syndesisio/syndesis/blob/master/ux/designs/integrationactivity/img/integrationsummary.png

However, the behavior of the element in History section (Details Tab) should reference https://github.com/syndesisio/syndesis/blob/master/ux/designs/integration_details/integration_details_page.md

I will update the integration details page design so we have the latest 3 tabs design. Thanks for bringing this to my attention! @dsimansk @deeleman

**Comment by deeleman** [comment]
Do we have any update on the designs @dongniwang ?

**Comment by amysueg** [comment]
@deeleman - The UX team is looking into this today and will update this issue later. Thx.

**Comment by amysueg** [comment]
@deeleman -

Updates -- @dongniwang  is updating the Integration Details Page design and will create a PR once she completes that. 

It will show the  "history" table on the Details tab.

**Comment by deeleman** [comment]
Awesome @amysueg. In order to implement this issue, I'll appreciate that, aside from your PR, you formalize acceptance criteria for the feature and attach the related screenshots in an issue so we all can properly track down its progress and drive the conversation around doubts should they arise.

I'll flesh out that issue myself then with the details regarding the API endpoints involved.

// cc @paoloantinori

**Comment by amysueg** [comment]
@deeleman I'm trying to follow this:

"you formalize acceptance criteria for the feature and attach the related screenshots in an issue"

We describe the UI elements, behaviors, and interactions in the design InVision files, along with the screens, which should satisfy your request. If you are looking for something more formalized than that, then we should include @kcbabo, @rhuss, and @paoloantinori as well - AFAIK we do not have a more formalized process in place. 

fyi @dongniwang

**Comment by deeleman** [comment]
> We describe the UI elements, behaviors, and interactions in the design InVision files, along with the screens, which should satisfy your request. 

I just learned today that you guys produce interactive mocks with InVision. Not bad, bearing in mind that I've been around for 5+ months now. ;) The question now is: Where is such previous information located? Can I take a sneak peek on it? :)

In this case, and since this issue is pure UI-related, we can skip the formalities and bureaucracy and rely on whatever design mocks you guys have. My only concern tho is that the QE guys might need to have some sort of reference as well which is accessible for them.

This kinda comes in hand with the ongoing discussion at #2033. The scenario I'm advocating for each and every user story that I'm supposed to pick (and the rest of Ui folks too) is that we want o action on stuff which is crystal clear defined in the Gh issue itself, instad of referring to other resources, sites, repositories, or grouped issues elsewhere.

I'll edit this issue myself with the _Expected behavior_ and reference screenshot once you point me to where it is once available.

**Comment by deeleman** [comment]
Ups, I just spotted #1998 in this thread. All right, I'll take care of this issue once I figure out what is it all about...

**Comment by deeleman** [comment]
All right, so here we go again: This bug report refers to the missing activity listview in the integration details page. That listview rendered a [very basic table with very limited information](https://github.com/syndesisio/syndesis/commit/3b290bf89a8886b9656f1bcc4eec21b479fd91fc#diff-f3499958d81bcc595b78e3671d12bcbc) about the activity logs returned by the API.

However, the screenshots attached describe a way much broader functionality, which exceeds the scope of what we already had and what we already can deliver, definitely. 

FYI I will focus on restoring the original listview and then we will have to go through all the attached screenshots once we wrap up the code freeze period and formalize each one into a GitHub issue. 

Otherwise there's no way to action this by any means, not to mention providing a proper time estimate, track the progress made, spot deviations or provide the QE folks with a proper E2E reference framework.

**Comment by gashcrumb** [comment]
https://github.com/syndesisio/syndesis/issues/1069 was actually my original tracking issue the 2nd time around implementing the history table if it helps a bit...
