### ISSUE TITLE
Integration details - Add child routes for each tab for easy linking

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#1912]
## This is a...

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Currently the tabs on the integration detail page aren't linked to any routes in the URL so it's not possible to link to a specific tab from elsewhere in the app, also when you refresh the page when on the detail view it'll reset to whatever the default tab is.  This is required to implement what's discussed in #1847 

## Expected behavior

Ideally there should be child routes for each tab in the detail view and the URL in the location bar should be updated when the user switches to different tabs.

One thing to be mindful of is if we need to alter the URL layout too much as the integration editor with all of it's routes also exist underneath the URL that points to the integration detail page.

**Comment by deeleman** [comment]
Working on this ATM, but it's kinda of tricky. The reason why all those views were implemented as nested components is because the original coding in the integration detail view is so convoluted that  splitting it into parts and move it to other routed components (remember that router outlets cannot receive properties) was pretty difficult. Nested components could receive instead the logic from the parent IntegrationDetailComponent as an input parameter, so the original programming was left as is.

This will take some time I'm afraid. Again, handling state and generating objects within components is a huge anti-pattern for good reason.

**Comment by deeleman** [comment]
> One thing to be mindful of is if we need to alter the URL layout too much as the integration editor with all of it's routes also exist underneath the URL that points to the integration detail page.

Don't worry! the Angular router processes routes as they come. Leaving the `:integrationId/edit` block as the last route segment will ensure that those routes will be always available. ;)
