### ISSUE TITLE
Import integration enhancement needed

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#1928]
![integration_import](https://user-images.githubusercontent.com/14313995/37205251-6891f6d6-2394-11e8-9dcc-3dec692d1e33.png)

Long integration name overlaps status message.
"Import Result:" makes no sense as it is now.

If you have already integration with the same name as the one you are importing you will overwrite it.
This is definitely not what we want - we should give the option to rename integration before
actual importing happens or warn user about possible overwrite.

**Comment by michael-coker** [comment]
Are we no longer listing the uploaded integration names beside the success/error message? The drag and drop zone used to list each uploaded integration name with a success/error message beside it, and the filename associated with the `<input type="file">` input was cleared after the integration was uploaded.

**Comment by michael-coker** [comment]
@kahboom I re-enabled the listing of imported files in the drop zone, am clearing the `value` of the `input type="file"` element after import, and am not clearing the upload queue when an invalid file type is uploaded in this branch if you want to review. https://github.com/michael-coker/syndesis/tree/import-ui-updates

From what I can tell needs to be done still is

1. Enabling the alert error (from `getFileTypeError()`) in the drop zone on an invalid file type
1. Allowing invalid file types to be listed in the drop zone area
1. The "import results" area looks empty to me. I don't see the uploaded integrations there, I only see the text "Integration Name"

cc @chirino

**Comment by kahboom** [comment]
Hey @michael-coker - These are known issues that I'm working on and will be creating GH issues for. I'll ping you on them. Thanks for taking a look at this.

>Are we no longer listing the uploaded integration names beside the success/error message? The drag and drop zone used to list each uploaded integration name with a success/error message beside it, and the filename associated with the <input type="file"> input was cleared after the integration was uploaded.

The reason I removed it was because for normal file select it was displaying the file name and extension twice. I can take a screenshot to show you when I get the chance. We'll have to add some type of conditional there to determine when to show that text. Validation is definitely one of the outstanding items that needs work, both in the UI and the API.

The remaining work is as follows:

- Use the integration overview endpoint to reflect data that is returned from the API in the Review section.
- Multiple vs single, drag and drop vs select sometimes seem to conflict. Need to verify what is happening.
- Re-add toast notifications (removed per request, but designs still have them).
- Proper UI (file type, etc) and API validation.
- When there are multiple integrations, the review page still shows the first. It should just redirect you to the list page.

This issue will be closed thereafter since it needs to be a bit more granular.

**Comment by michael-coker** [comment]
@kahboom thanks! re:

> The reason I removed it was because for normal file select it was displaying the file name and extension twice. 

Doesn't like 86 in [integration-import.component.ts](https://github.com/michael-coker/syndesis/blob/import-ui-updates/app/ui/src/app/integration/import-export/import/integration-import.component.ts) address that after the file is added to the uploader queue?

> this.fileSelect.nativeElement['value'] = '';

**Comment by kahboom** [comment]
@michael-coker Sure, this was a late night demo-driven change.

**Comment by kahboom** [comment]
New issues:
- Review step: #1954 
- Drag & drop, file select for multi import conflicts: #1955 
- Toast notifications: #1956 
- Validation: #1957
