### ISSUE TITLE
Salesforce connection creation fails - regression

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#1949]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Salesforce connection creation fails with the following error:
https://gist.github.com/honghuac/05958dd0ed84348f8343111b65f342c3

## Expected behavior

The creation process should be successful, and the user must not be seeing this page (which loads after the failure) at all:
![ra](https://user-images.githubusercontent.com/8625482/37281498-36c03ab0-262c-11e8-9b03-31dab13540ae.png)

**Comment by zregvart** [comment]
I would wager that the root cause is the same as in #1948. Those WARN messages in the log could be irrelevant, we store some state in HTTP cookies that are named like `cred-o...`, if the OAuth flow doesn't succeed at some point those cookies can be left behind. On the next OAuth flow they should be cleared if they timeout.

We should make the log message a bit more straightforward and perhaps not print the stacktrace to make it a bit less alarming.

**Comment by paoloantinori** [comment]
It's been noted this might be related to the OOM related issues we are currently debugging.
