### ISSUE TITLE
Syndesis Maven Plugin duplicates dependencies

### ISSUE THREAD

**Issue by lhein** [syndesisio/syndesis#2075]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I created a custom step extension project and ran the build which triggers the syndesis maven plugin to generate the json file. When looking at the json file I discovered the dependency entry duplicated but with different versions....one which was already in the source version of the json and then the new version taken from the pom.xml by the plugin.

## Expected behavior
I would have expected that the existing dependencies are reused in the json. In my case the 1.3-SNAPSHOT dependency should have been overwritten with the 1.3.0.fuse-000014 version instead of duplicating that dependency which makes no sense at all.

## Screenshot
The generated JSON: https://gist.github.com/lhein/e745970c811cc60da043668fb7c9466f
The Project POM: https://gist.github.com/lhein/04771457354513dfc330c568f2fa3bb0
The original json in my project sources: https://gist.github.com/lhein/0356471d7aacedb3f8ae0290a107ba3c

## Request and Response Data
not applicable

## API Endpoints and Schemas
not appilicable 

## Tasks involved / Steps to Reproduce
1. create a step extension project and enter version 1.3-SNAPSHOT as shown in the gists
2. edit the pom.xml and change the syndesis version to 1.3.0.fuse-000014
3. run the build to regenerate the json file and build the jar
4. open the jar and check the json

**Comment by nicolaferraro** [comment]
@lhein if I understood it correctly, the maven dependency on extension-api was present in both the pom.xml and source json file.
Currently the plugin takes everything that is present in the source json as is and adds information from the pom.xml to generate the final json. That's why the dependency is duplicated.

This can be fixed. In case of duplicate dependency, only one of them should be left in the final json. We should just decide which one and why (pom doesn't always override source json in other cases).

Btw I expected maven dependencies being declared only in the pom.xml, is there a reason why you are adding them also to source json?

**Comment by lhein** [comment]
I took that from an example template. I will remove the json dependency entries from my source json but in any way the plugin should be clever enough to detect dupes and in this case I think the pom should be the leading source when it comes to dependency versions.

**Comment by nicolaferraro** [comment]
Yes, better that example and templates use only pom.xml to declare dependencies. But agree, I'll resolve duplicates in any case.
