### ISSUE TITLE
CSRF exploit using flash plugin

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2104]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
CSRF exploit using flash plugin.

## Expected behavior
3rd party pages not being able to use Syndesis APIs.

## Tasks involved / Steps to Reproduce

Reported by Andrej Vano.   He stated:

> "Basic" CSRF attempts are blocked by CORS, but this method is able to bypass the CORS settings using a remote server and one flash file.
> 
> Here is the example that can be used against Syndesis (case 2): https://www.geekboy.ninja/blog/exploiting-json-cross-site-request-forgery-csrf-using-flash/ .
> 
> For the demonstration I used only the json "{"name":"attacker"}" that was sent to https://app-proj232514.6a63.fuse-ignite.openshiftapps.com/api/v1/connections that ended up creating a new connector with name "attacker".
> see:  https://www.geekboy.ninja/blog/exploiting-json-cross-site-request-forgery-csrf-using-flash/

**Comment by chirino** [comment]
We should use some specific header that will be sent with each [request](https://security.stackexchange.com/questions/23371/csrf-protection-with-custom-headers-and-without-validating-token).  Angular already [has support](https://angular.io/api/http/CookieXSRFStrategy) for this.

**Comment by deeleman** [comment]
> Angular already [has support](https://angular.io/api/http/CookieXSRFStrategy) for this.

The linked resource was deprecated back in Angular 4.2, since all the valdiation is now performed in a generic way by the new Angular HttpClient for the entire application.  Requests make use of a custom `XSRF-TOKEN` cookie that needs to be set by the backend (at the OPTIONS handshake for instance) and will be returned in any call performed by the `HttpClient` class as a `X-XSRF-TOKEN`.

It will be up to the backend to define the cookie name and the header name where the reference will be attached on each request. The UI just requires those names, should they are customized.

Once done, this needs to be attached to the `AppModule` imports array:

```typescript
HttpClientXsrfModule.withOptions({
  cookieName: 'Syndesis-Xsrf-Cookie',
  headerName: 'Syndesis-Xsrf-Header',
})
```

Problem is that I have no idea how to apply this logic to Restangular ;P

**Comment by deeleman** [comment]
I spent a great deal of time trying to upgrade `ngx-restangular` itself to remove its internal dependency on the deprecated `@angular/http` module and replace it by the official `@angular/common/http` namespace so we could take advantage of the `HttpClientXsrfModule` module, but given the lack of tests of the upstream dependency it proved to be not possible.

This issue will be surrogated to remove Restangular first.

**Comment by deeleman** [comment]
@chirino I assume we will want to append the CSRF header on every request except for `GET` and `HEAD` requests, right?

On a side note, would we ever get `0` as a possible token?

**Comment by deeleman** [comment]
[This PR](https://github.com/syndesisio/syndesis/pull/2272) implements the UI parts required to implement CSRF watermarking on the XHR requests submitted by the UI. In summary:

- The server can now send a CSFR token cookie to the frontend. The name for the cookie is fully configurable.
- Such token will be fetched from said cookie and appended in a custom header on every outgoing request made to the API. The name for the header is fully configurable.
- If no CSRF cookie is sent to the client, no CSFR token header will be sent back.

**Please note:** The token header is NOT appended on non-mutating requests (GET, HEAD).

### How to inform the UI about the cookie name or customize the header name
The UI [environments](https://github.com/syndesisio/syndesis/tree/master/app/ui/src/environments) folder contains the development and production setting files that Angular will use to customize the application setup after compilation. There is a new `csrf` node in these files that contains two properties:

- `cookieName`: the name of the cookie saved by the browser containing the validation CSRF token.
- `headerName`: the name of the header contained the aforementioned token the server will expect.

@lburgazzoli @chirino  Feel free to edit the names provided as needed to match the ones you guys implement in the backend.

The parts required from UI here are done.

**Comment by chirino** [comment]
Does it hurt to put it on GET requests too?

**Comment by dsimansk** [comment]
@paoloantinori fyi this should be triaged and target for GA. Afaik the backend impl is needed to complete this issue.

**Comment by gashcrumb** [comment]
> Does it hurt to put it on GET requests too?

No reason to, the attack vector relies on posting JSON data in the request body, in the case of GET the request body *should* be ignored by the server.  I can't think of any case in our API where we do this.

**Comment by nicolaferraro** [comment]
Going to implement it.

I will set a *fixed* token into each request (according to [this](https://security.stackexchange.com/questions/23371/csrf-protection-with-custom-headers-and-without-validating-token) explanation, it should be sufficient).

I guess HEAD and GET requests should be left free because the client gets the token the first time it access a resource (usually by issuing a GET).

**Comment by igarashitm** [comment]
So it seems we want to do same for AtlasMap endpoints. As AtlasMap services resides in  syndesis-server pod, one thing left to do is sending this header from AtlasMap UI if it's running within syndesis, then the common spring-boot security handler can handle it, correct?

**Comment by gashcrumb** [comment]
Looks like the token comes back in the response header already to `/api/v1/atlas/json/inspect` so just a matter of getting the atlasmap UI to install the same HTTP interceptors I guess @nicolaferraro?

**Comment by igarashitm** [comment]
I think we can make those header name and token configurable in config.json (environment.ts?) as a part of datamapper namespace, then AtlasMap UI would send the header out only when those are configured. Then we can just put `datamapper.xsrsTokenHeaderName: "SYNDESIS_XSRF-TOKEN"` in config.json.

We might even want to do same thing for standalone, but not sure we can finish server side work and test at this very last minutes.

**Comment by gashcrumb** [comment]
> We might even want to do same thing for standalone, but not sure we can finish server side work and test at this very last minutes.

Yeah, probably worth deferring that bit...

**Comment by igarashitm** [comment]
Once #2455 is merged, AtlasMap should be able to work with ApiXsrfInterceptor and send out the protection token.

However currently there seems to be an issue around NgModule declaration in Syndesis, the interceptor is not enabled for AtlasMap HTTP call. This `withInterceptor()` returns DataMapperModule with AtlasMap version of ApiXsrfInterceptor:
https://github.com/atlasmap/atlasmap/blob/015d4ebc6771a5bd3965c8e9c4ad747e0ffe5ac3/ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts#L144
But if you use this in Syndesis instead of importing `DataMapperModule`, Syndesis http call starts to trigger this AtlasMap version of interceptor and send `ATLASMAP-XSRF-TOKEN` header. Even with that, AtlasMap http call doesn't emit that header.

**Comment by igarashitm** [comment]
BTW I think we don't have to use AtlasMap version of ApiXsrfInterceptor. If Syndesis version of ApiXsrfInterceptor is enabled in AtlasMap, then it will simply do the job.

**Comment by zregvart** [comment]
I think we should use a non-fixed value for the CSRF token. Having a fixed value makes us still vulnerable via vectors that can set HTTP headers for arbitrary sites, such as Flash.

**Comment by nicolaferraro** [comment]
I believe flash does not allow to set custom headers like `Syndesis-smth`. For this reason the fix uses a constant value, since also flash is not able to reproduce it.

Introducing a variable token can be painful, so I'd not do it if not required.

**Comment by zregvart** [comment]
Looking at this:

https://github.com/syndesisio/syndesis/blob/127c66d3be3df7cd4314e2e761ab5f468211f114/app/ui/src/app/api/providers/api-xsrf-interceptor.service.ts#L22-L23

It seems to me that the UI is ready for variable CSRF token.

On the server side we can take the encryption key that we use for secrets and derive a token from the username and the key using something like HMAC, should not be too difficult.

**Comment by zregvart** [comment]
WRT Flash, not sure if [this](https://www.exploit-db.com/papers/13170/) (from 2006) is still relevant.

**Comment by avano** [comment]
currently it is sufficient to use hard coded value for the token - AFAIK there should be no way to post custom headers in the requests, so I'll close this for now (unless you want to generate the token Zoran :wink: )
