### ISSUE TITLE
Datamapper: Done button changed to Next since 1.3.2 version

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#2109]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
For quiet some time the button in Datamapper UI was named `Done`, but now it's `Next`.

For the same integration steps DB (Periodic invoke) -> DB (Stored procedure) the button values are different between 1.3.2 and master.

This values seems to be dynamic based on `step.configuredProperties`. Was there some recent changed in incoming properties?

https://github.com/syndesisio/syndesis/blob/989e089fe7141af1d82a8975e08ea4c0bc7eb1c3/app/ui/src/app/integration/edit-page/step-configure/step-configure.component.html#L3-L16

## Screenshot

![screen shot 2018-03-21 at 14 24 14](https://user-images.githubusercontent.com/5637792/37712251-9850f326-2d13-11e8-9df5-2ab06bdf2b00.png)

![screen shot 2018-03-21 at 14 23 42](https://user-images.githubusercontent.com/5637792/37712252-98765b34-2d13-11e8-8333-5f978b5e6ff3.png)

## Expected behavior
Datamapper UI should be closed with `Done` button.

**Comment by gashcrumb** [comment]
Actually yes, it was the fix to #1149 that resulted in this.  Otherwise the datamapper configuration was immediately saved to the integration, causing this property to be set.  Now it's not set until you click the button.

The question is, I fail to see why the button would ever be `Next >` given that step configuration is currently limited to one page, unlike action configuration which can be multiple pages.

@dongniwang @sjcox-rh preference on this?  I'm thinking I'd change the button to always read `Done` which would affect mapper, basic filter, log/advanced filter and any extension page, but in all these cases there currently isn't a 'next' page other than the save or add step page.

**Comment by dsimansk** [comment]
@gashcrumb current state is:

- first time addition of Datamapper, Log etc. step has `Next` button to submit/finish step
- editing of this step afterwards has `Done` button, obviously indicated by presence of `configuredProperties `

It would be better to stick with `Done` to submit/finish any modification of step, otherwise it's just confusing.
