### ISSUE TITLE
Unable to use REST API Client Connector as Start Connection in an integration.

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2174]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I am unable to use the REST API Client Connector-based connection as Start Connection in an integration, because any REST API Client Connector-based connection fails to appear in the available connection list.

## Expected behavior

REST API Client Connector should appear in the list of available connections, when creating an integration

**Comment by zregvart** [comment]
This is by design, so this should be a feature request. To start from an API connector would be as if the API would invoke Syndesis -- we have support for that via [webhooks](https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-connector-webhook), or that the API is polled and we can do that via [timer](https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-connector-timer).
