### ISSUE TITLE
Swagger document of ToDo App rejected by API Client Connector wizard

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2193]
## This is a...

<pre><code>
[ ] Feature request
[X ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The To Do App [Swagger Document](https://gist.github.com/honghuac/01185f8179f6c28456c9e923f429da64)
is rejected by the API Client Connector wizard, using both Swagger document upload and URL method.

## Expected behavior

JSON 
The TO DO App Swagger Document should be error free / acceptable with the API Client Connector.

## Screenshot

![err-swagger](https://user-images.githubusercontent.com/8625482/38076281-c1d078fc-3367-11e8-87bc-b88ee4cfbf66.png)
![todo-swag](https://user-images.githubusercontent.com/8625482/38076477-4ee9498a-3368-11e8-91b8-9bd391343419.png)
![upload-swagger](https://user-images.githubusercontent.com/8625482/38076481-531a68ea-3368-11e8-91bf-b14cbf28a754.png)

## API Endpoints and Schemas

https://todo-fuse.fuse-3m76.apps.dev37.openshift.opentlc.com/

## Tasks involved / Steps to Reproduce

1. Attempt to upload the To Do App Swagger document to API Client Connector wizard
2. Attempt to assign this [URL](https://todo-fuse.fuse-3m76.apps.dev37.openshift.opentlc.com/) for the Swagger document to API Client Connector wizard

**Comment by zregvart** [comment]
I've tested with the Swagger file from the [gist](https://gist.github.com/honghuac/01185f8179f6c28456c9e923f429da64) and the TODO Swagger file [from staging](https://todo-syndesis-staging.b6ff.rh-idev.openshiftapps.com/swagger.json) into the staging environment without issues. I think this might be an issue with TLS certificates used to serve the TODO app, for instance if using between two environments or on in a environment that doesn't have the OpenShift Java keystore setup properly.
The issue at the last step (on Review/Edit Connector Details) page is probably due to unavailability of the `syndesis-server` pod, at that point the Swagger document has already been parsed, so it can't be an issue with it.
