### ISSUE TITLE
Improve responsive behavior of the Integrations page

### ISSUE THREAD

**Issue by amysueg** [syndesisio/syndesis#2227]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Resizing the browser results in a poor layout of web interface elements and renders the Integrations page unusable in many cases. On a mobile device, it's just as bad or worse. 

## Expected behavior
The page should resize elegantly using modern web design techniques. UXD team will define guidelines for responsive breakpoints and expected layouts and behaviors.

See #2216.

**Comment by michael-coker** [comment]
I'm addressing the integration details page with this issue. To address the create/edit process would require (IMO) a design spec to take into consideration the vertical navigation panel. I imagine that workflow is best done on desktop, especially considering anything involving the current data mapper UI.

Submitted a PR to better display cards on the metrics tab of an integration details in a small/narrow viewport.

Otherwise I've addressed the core issues on the details page and think it's OK as it is. The PF components on the page are behaving as they should. The spacing on some elements isn't ideal, but it's functional in narrow viewports. 

@amysueg do you want to take another look and let me know if you have any feedback?

**Comment by amysueg** [comment]
@michael-coker sure that would be great.
I completely agree with you that any change to the Integration Visualization (left vertical page element) will need a design spec. We would need input from PM @kcbabo regarding whether or not this is a priority since most "create/edit integration" use cases will likely occur on a desktop or laptop and not a smaller device/viewport.
