### ISSUE TITLE
Integration data mapper issue

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#2247]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Can't insert and edit data mapper step between twitter mention and salesforce create/update connections

## Expected behavior

I am able to add data mapper and edit it later.

## Tasks involved / Steps to Reproduce

1. Create integration from Twitter Mention to Salesforce
2. In salesforce select create or update record --> Contact -->TwitterScreenName
3. insert data mapper step with some random mapping, it does not matter what
4. save integration as draft
5. navigate to integrations list
6. select the integration and click on Edit integration
7. note that there is error present - no data mapping step even though there is data mapper
8. click on data mapper step - it shows error
9. delete that data mapper step and try to create new one - it is not possible

**Comment by gashcrumb** [comment]
Yep, so the issue here is that when going back into the editor, the input data shape for the salesforce connection doesn't look right, when the UI posts the object on save the `inputDataShape` on the salesforce action contains the `specification` attribute, but this is apparently lost when reloading, the response that comes back when the editor loads it just contains `kind` set to `json-schema` which is wrong.

Actually a regression, this was working fine previously.

**Comment by gashcrumb** [comment]
@paoloantinori This seems like a pretty serious regression BTW...

**Comment by igarashitm** [comment]
> the response that comes back when the editor loads it just contains kind set to json-schema

This is highly possibly to be a template data shape stored in the deployment.json, which means the metadata request {couldn't get | bypassed to get} dynamic data shape via syndesis-meta.

**Comment by dsimansk** [comment]
@mcada pls verifty that this issue is fixed and tests are working.

**Comment by mcada** [comment]
Verified, tests passed.
