### ISSUE TITLE
Enable option to rename integration when importing from file

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#2260]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Expected behaviour

Allow user to rename integration when importing. Importing integration which shares name with existing integration overrides the existing one and there is no option to rename the integration before importing. I think that it would be nice to first select file with integration to be imported and fill new name of the integration and then click on some button to actually do the import and then see result of imported integration.

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by gashcrumb** [comment]
@dongniwang @sjcox-rh FYI

Probably only possible for a single integration import, not sure how this would work for multiple imports.

Also what might complicate this is that the act of dropping the file initiates the import, i.e. on successful file upload the integration is imported, so the new name has to be entered before the upload is done.

This might also require a change on the API side as well to allow for the UI to specify a name along with the file data.

**Comment by sjcox-rh** [comment]
@gashcrumb Makes feature makes sense. Easy if user selects the chooses file button. Since that opens a file folder, we can allow the user to change the name there. 

However, for drag and drop, the upload is instant, like you said. I think we can still allow the import to initiate after dragging and dropping, but before it's complete can we show a modal giving the user the option to rename? They can certainly have the option to skip renaming but that way there is the functionality available. 

This might be jarring though, having a modal appear when it wasn't triggered.

@dongniwang fyi

**Comment by amysueg** [comment]
@seanforyou23 will contact @kahboom to discuss approaches.

**Comment by amysueg** [comment]
@dongniwang In the work you've been doing for #3581 have you considered this?
