### ISSUE TITLE
[Trivial] Update the email address for Contact Us for GA

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis#2277]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
In the staging UI, selecting Help > Contact Us automatically displays fuse-ignite-tech-preview@redhat.com as the email address to send a message to. This will need to be something different for GA. 

## Expected behavior
@kcbabo  - What email address should this use?

**Comment by kcbabo** [comment]
@sjavurek What email address should we use for support?  Should we change this to a link to the CSP?

**Comment by TovaCohen** [comment]
Just want to note here that the email address also appears on the Support page. So it will need to be updated in two places.

**Comment by TovaCohen** [comment]
@deeleman I noticed that you were asking about the email address on IRC. Just want you to know about this issue. Maybe you can leave a comment here about updating the dictionary file with the email address, when we know what it will be.

**Comment by paoloantinori** [comment]
Hi @sjavurek  have you got a chance to find this email address to use for GA ?

**Comment by sjavurek** [comment]
I'm so sorry for the very late reply! 

Customers need to open a ticket to get support so they should be directed to the customer portal:

https://access.redhat.com/support/cases/#/case/new

Please let me know if you need anything else.

**Comment by kcbabo** [comment]
@paoloantinori : related question for you - is the contact us info stored outside the images (e.g. in ConfigMap)?  Reason I ask is that the Ignite eval cluster should have different info than than the production Fuse Online cluster.

**Comment by sjavurek** [comment]
@kcbabo interesting question on the eval. Let me check something and get back to you.

BTW, let me try to provide the updated on the text as well:

{code}
Support
To obtain support, download diagnostic information through this page and open a request on the <a href="https://access.redhat.com/support/cases/#/case/new"> Red Hat Customer portal</a>.  If the downloaded zip file is less than 1 GB, you may attach it to directly to the case otherwise, please follow one of the options listed in this <a href="https://access.redhat.com/solutions/2112">article<a/>. 
{code}

Question: is asking a citizen user to ftp a file too much? I know we discussed doing this automatically at one time. That may be easier once the portal integration is back in OpenShift.

**Comment by kcbabo** [comment]
IMO, we should leave the FTP bit out.  If the zip file is bigger than 1GB and a user can't upload it, then they will likely ask that question on the support case.  I think there's a pretty low risk of those files getting bigger than 1 GB, but engineering might be able to provide more clarity there.

**Comment by sjavurek** [comment]
@kcbabo Hi Keith. For the evals, we can take them too.  They usually have separate SKU's, however, I hear online is different in that they use some sort of coupon system instead of or  in conjunction with SKU's.  It would be good to understand that process and also if there is anything else we need to do to make it work.

**Comment by TovaCohen** [comment]
I suggest this revision:
If the downloaded zip file is less than 1 GB, attach it to the case. For a larger zip file,  tell the support team that the zip file is larger than 1 GB and ask for instructions.

**Comment by kcbabo** [comment]
Our eval cluster has its own signup and registration, so the coupons aren’t
actually used with the eval cluster.  I will circle back with you
separately to provide more details.

**Comment by paoloantinori** [comment]
Guys, could you recap what are your expectations here. Have you reached an agreement on the text to include?

@kcbabo currently the text is hardcoded. Being it an html page, we can turn it into a dynamic one, but it's not that straight forward since it has to be a pre-init static replacement and not something that we can do at either compile time or runtime.

**Comment by kcbabo** [comment]
If we can only have one contact detail across environments, then we should go with the URL that Susan provided earlier:
https://access.redhat.com/support/cases/#/case/new

It would be nice if we could make this customizable per environment in the future.

**Comment by sjavurek** [comment]
My only concern is that customer who are eval won't actually be able to log a ticket since they won't have an account. That sort of sets us up for a bad evaluation ....

Do we need to add a block that says:

{code}
Support
To obtain support, download diagnostic information through this page. If you have a subscription please log a ticket with us on the Red Hat Customer portal otherwise please e-mail fuse-ignite-evalutions@redhat.com. If the downloaded zip file is less than 1 GB, you may attach it to directly to the e-mail/case otherwise, please follow one of the options listed in this article.
{code}

**Comment by kcbabo** [comment]
The email address for eval feedback is included in all the notification emails, so people should know how to contact us if they are in an evaluation.
