### ISSUE TITLE
No padding between buttons

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2567]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

<img width="683" alt="image" src="https://user-images.githubusercontent.com/99080/39788117-ab5f849c-52dd-11e8-9f3c-4226d60c84ec.png">

**Comment by rhuss** [comment]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/99080/39788140-d3f12f14-52dd-11e8-870e-b953ed6c0ad5.png">

**Comment by michael-coker** [comment]
The validation component currently displays the validation success/error message after the button. An easy way to address this without much work would be to swap the buttons and make the "validate" button the primary action (makes sense, since the paragraph above references the validate button). Then the alert will come after it.

![screen shot 2018-05-10 at 2 20 00 pm](https://user-images.githubusercontent.com/35148959/39889411-652acff0-545d-11e8-9d26-00fa5341e6f5.png)

![screen shot 2018-05-10 at 2 20 03 pm](https://user-images.githubusercontent.com/35148959/39889410-651560d4-545d-11e8-8c6c-e35c52099d7f.png)


But I suspect that isn't ideal, because the message from the "reconnect" button displays above those buttons.

![screen shot 2018-05-10 at 2 35 14 pm](https://user-images.githubusercontent.com/35148959/39890192-adbea32a-545f-11e8-9c95-44b19b3470ec.png)

I'm assuming we'd like the alert messages to have the same placement (above the buttons)? If so, we'll need to modify the validate component to decouple the message from the button, so we have the flexibility to display the message somewhere else on the page, independent of the button placement. We can discuss this in the next UXD meeting.

**Comment by dongniwang** [comment]
Is Validate and Reconnect targeting the same kind of actions? I'm asking because I feel like we probably need to restructure the content on this page to address consistency issues.

**Comment by gashcrumb** [comment]
'validate' is "Check and see if my credentials/config work against the target system".

'reconnect' is "go and update my authentication token with the target system's oauth provider".

So I think it's kinda different.

**Comment by michael-coker** [comment]
Left these buttons as they are and spaced the buttons/messages appropriately. It matches the current layout on other types of connections with validation ("http" connections, for example). If we want to move the output of the validate button, let's open another issue to refactor the connection validation component so that the validation output can be separated from the button.
