### ISSUE TITLE
Extension Import screen is a bit confusing

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2569]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

In the top box it says in the green box "Sucessfully imported", but there is still an active "Import" button. Actually, at that stage the extension has *not* been imported, but _uploaded_ and checked. Maybe the green label should be changed to *Sucessfully uploaded* ?

<img width="986" alt="image" src="https://user-images.githubusercontent.com/99080/39788356-f4d5ec14-52de-11e8-90aa-8a68575c5278.png">

**Comment by rhuss** [comment]
Also, after the extension has been imported there is only a Toast notification about "Sucessfully imported" which vanishes after 3s. This leaves the user with this screen:

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/99080/39788475-7d7a161c-52df-11e8-9b60-d1c0d8fc47f8.png">

That's a bit confusing as there are only two Options: An "Update" in Blue (which means default ?) and "Delete". I've seen many people here pressing the Update button because they were not sure whether the integration is really imported or how to get out of this screen. This happened multiple time at the workshop, so its a real UX issue.

**Comment by tplevko** [comment]
The same "Sucessfully imported" confusion is also valid for integration import. The integration get's just uploaded, to import it successfully, user needs to confirm the import first:
![import_integration](https://user-images.githubusercontent.com/4180208/39858341-90b5e438-5436-11e8-8a09-eaf18238edcc.png)

**Comment by michael-coker** [comment]
@seanforyou23 and I talked about this and agree that the text should say "Successfully uploaded" instead of "Successfully imported" once the file is uploaded prior to importing.

Though I'm not sure how to address the second issue with the toast notification and "Update" button. This is potentially related to https://github.com/syndesisio/syndesis/issues/2396 to ensure we have a consistent standard for inline and toast notifications.

One option could be to leave the toast notification on the screen longer or until the user closes it ([patternfly toast notifications](http://www.patternfly.org/pattern-library/communication/toast-notifications/#design) for reference).

Another could be to use a text notification in the extension details page alongside or instead of a toast notification.

Another could be to change the "Update" button text to something like "Edit".

@sjcox-rh @dongniwang @amysueg what do you think?

**Comment by gashcrumb** [comment]
> Also, after the extension has been imported there is only a Toast notification about "Sucessfully imported" which vanishes after 3s.

This actually should be raised as a separate issue tbh.

To be consistent with the rest of the app, after importing we should transition to the extension list page instead of the detail page for that extension.  This is what happens when you create a connection, when you create an API client via swagger I believe.  I guess though when creating an integration you technically wind up then at the detail page for that integration.  So yeah, needs a separate issue so we can figure out the right target page once the user clicks 'import'.

**Comment by michael-coker** [comment]
Great, thanks @gashcrumb 

> when you create an API client via swagger I believe

Confirmed it does.

**Comment by gashcrumb** [comment]
I think I might just add that redirect to the list while sorting this one and then someone can log a bug against that in the future if needed :-)
