### ISSUE TITLE
Upgrade template of fuse-ignite flavour should point to productized image version

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#2574]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When templates are released to `fuse-ignite-install` repository. Coordinates to `fuse-ignite-upgrade` should be also changed accordingly from Dockerhub to RH registry.

https://github.com/syndesisio/fuse-ignite-install/blob/master/resources/fuse-ignite-ocp.yml#L1522 

## Expected behavior
Fuse Ignite template points only to product versions

Cc @paoloantinori @rhuss. If you prefer to have the issue created in the other repository, just let me know.

**Comment by paoloantinori** [comment]
Fixed

**Comment by paoloantinori** [comment]
@avano my bad, fixed now.

https://github.com/syndesisio/fuse-ignite-install/blob/1.3/resources/fuse-ignite-ocp.yml#L1522

Thanks for finding this!

**Comment by paoloantinori** [comment]
I assumed that the internal repo would have been polled. It seemed not the case. It should be fixed with this.

https://github.com/syndesisio/fuse-ignite-install/blob/master/resources/fuse-ignite-ocp.yml#L1530

**Comment by avano** [comment]
@paoloantinori shouldn't the image also re-use the SYNDESIS_VERSION tag property instead of hardcoding the version? 

For upgrade you need the "UPGRADE_VERSION" container to

**Comment by paoloantinori** [comment]
Hi @avano  could you help me understanding why this blocker has been re-open? 
Is it currently using any wrong value?
I cannot understand if you are suggesting an enhancement or reporting a blocker.

**Comment by avano** [comment]
> Hi @avano could you help me understanding why this blocker has been re-open?

currently you are hardcoding the upgrade image tag. Upgrade image tag refers to a version to which the current ignite installation will be upgraded
> Is it currently using any wrong value?

Yes
> I cannot understand if you are suggesting an enhancement or reporting a blocker.

With current state you will never be able to upgrade, because you will be running still running the same upgrade container, no matter which SYNDESIS_VERSION you specified. 

Therefore here: https://github.com/syndesisio/fuse-ignite-install/blob/master/resources/fuse-ignite-oso.yml#L1529 (in both templates) you should use

```
 "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/fuse7/fuse-ignite-upgrade:${SYNDESIS_VERSION}" 
```

(the parameter that is defined few lines before that)

**Comment by rhuss** [comment]
I agree with @avano that this should be `$SYNDESIS_VERSION` if we allow to specify the version from the outside (as we do).

An alternative would be to nail down the version already in the template so that this template is specific for this version only (no SYNDESIS_VERSION required then). This would allow to change the structure of this template for upgrades (but the process would be different for upgrades then as you would have to install updated template first).

Let me send a PR to fix this.

**Comment by paoloantinori** [comment]
Can you guys help me understand this?

1) @avano mentioned a missing ImageStream. That totally confuses me since
syndesis-upgrade template wasn't using an ImageStream.

2) I don't get why the need to use a variable there. What was the problem
in having it set to the latest released version?

**Comment by rhuss** [comment]
@paoloantinori as mentioned, you release.sh run would have been broken anyway because of https://github.com/syndesisio/fuse-ignite-install/blob/767534685080e81e22dc928b2237dd07adbb67f9/release.sh#L178

**Comment by rhuss** [comment]
@paoloantinori please consider this PR for doing the release. It contains other fixes to release.sh, too.

**Comment by rhuss** [comment]
https://github.com/syndesisio/fuse-ignite-install/pull/17 this I mean.

**Comment by rhuss** [comment]
This PR works without any hack. Please note, that the Template is already fixed within the 1.3.10 tag. --> https://github.com/syndesisio/syndesis/blob/1.3.10/install/generator/01-header.yml.mustache#L135

So you 'hack' is not needed anymore for 1.3.10 (might even not work).

**Comment by rhuss** [comment]
It's really only the commit https://github.com/syndesisio/syndesis/commit/c9b4fc553a71df7d810b98fd080e812d0fb3943e which was included to 1.3.10 after the fact. I take the full responsibility for this commit and does not influence or change anything wrt to the already productised Maven artefacts or Docker images based on top of 1.3.10.

**Comment by rhuss** [comment]
```
git clone git@github.com:syndesisio/syndesis.git
git checkout 1.3.10
git merge c9b4fc553a71df7d810b98fd080e812d0fb3
git tag -f 1.3.10
git push -f -u origin 1.3.10
```

**Comment by paoloantinori** [comment]
I'm finding hard to keep track of all this moving part during code freeze.

Please @rhuss take care of this release, since I'm no longer sure what happened.

My understanding is that we are basing our work on commits happened after the release of the tag that was supposed to be used in production. 

Please take all the actions required to release the templates corresponding to a commit that we are able to support and that has been tested by QE.

**Comment by dsimansk** [comment]
@paoloantinori sorry, I've asked Roland to review the original problem mentioned in this issue. To make sure the stated`$SYNDESIS_VERSION` assumptions are correct. The conversation was carried away to other issues. I'm really sorry about that.

**Comment by rhuss** [comment]
@paoloantinori ok, I will take care about releasing fuse-ignite-install. Sorry for trouble, its all my fault. 

Just one last question: 

* registry.access.redhat.com is the final registry (not brew as in the 1.3.10 tag)
* fuse7 is the final repository, not jboss-fuse-7-tech-preview as it is now in 1.3.10

**Comment by rhuss** [comment]
@paoloantinori @dsimansk what about the oauthproxy issue ? Currently docker.io/openshift/oauth-proxy:v1.1.0 is referenced in the image streams. Is this ok ?

**Comment by dsimansk** [comment]
>registry.access.redhat.com is the final registry (not brew as in the 1.3.10 tag)
>fuse7 is the final repository, not jboss-fuse-7-tech-preview as it is now in 1.3.10

That's correct, those are final destination.

>what about the oauthproxy issue ? Currently docker.io/openshift/oauth-proxy:v1.1.0 is referenced in >the image streams. Is this ok ?

That should be OK. Afaik there's no other image we could use currently.
