### ISSUE TITLE
Import of zipped Integration - password for FTP connection needs to be reprovided

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#2602]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

An existing integration that uses a FTP connection was exported. When reimported to another Fuse Ignite instance, the FTP connection of this integration has to be reprovided with the FTP server password, as the password that was exported fails the validation.

**Comment by paoloantinori** [comment]
This error belongs to a recurrent pattern of errors related to secure information and encryption.

I'm not expecting this being solvable, probably we can just mitigate it with a better UX telling the user to re-configure part of the application

**Comment by tplevko** [comment]
I would say, this is actually expected behavior, because both syndesis instances: the one from which the integration was exported and also the second one, where the integration is imported, both use instance specific encryption key. 
After the import of integration, the user needs to change the "connection configuration", which is announced this way:
![config_required](https://user-images.githubusercontent.com/4180208/42650344-7311755c-860c-11e8-972c-1f3acd42d04b.png)

@paoloantinori, as you mentioned, this could be reviewed by UX team, because the user notification is from my POV not ideal. He has to go to the "connections" page and the user has no way of knowing that he needs to perform this connection update.

**Comment by dongniwang** [comment]
@tplevko @paoloantinori - 

I think the issue raised here is part of the import/export workflow. [Here](https://github.com/syndesisio/syndesis/blob/master/ux/designs/importexport/importexport.md) is the UX design for the flow. 

@tplevko - could you help explain a little bit more about what you mean by  
>  He has to go to the "connections" page and the user has no way of knowing that he needs to perform this connection update.

One quick way to improve the situation is adding information in the success toast notification to let users know they need to configure the connections and re-authenticate if necessary. 
![image](https://user-images.githubusercontent.com/24943812/42765723-a67fcc40-88e6-11e8-8976-825163bef0b7.png)

cc: @amysueg @sjcox-rh

**Comment by dongniwang** [comment]
@tplevko - no worries and thank you for the detailed description! 

Are you importing multiple integrations or just one at a time? After users pressed "Done", is there any feedback (e.g. a toast notification) on the screen?

**Comment by dongniwang** [comment]
@tplevko - I think with #3101 in place, the situation we're talking about in this issue should be improved with the "configuration required" showing up in the import results screen. 

![image](https://user-images.githubusercontent.com/24943812/42887641-731f21cc-8a74-11e8-9332-e9ea04777adf.png)

**Comment by gashcrumb** [comment]
Have an export now that should show this, will test today and see if that message will show up on import and further investigate if needed.

**Comment by gashcrumb** [comment]
So on this one, the embedded connection object in the API response for connections isn't there.  I'll fetch all the connections too and correlate them I guess.

**Comment by dongniwang** [comment]
Thanks @gashcrumb! 

> Have an export now that should show this, will test today and see if that message will show up on import and further investigate if needed.

Based on what @tplevko described ealier, it seems like there's no toast notification when import is successful. Not sure if that's the case for both single import or multiple import.

**Comment by gashcrumb** [comment]
do we really need one?  The whole page kinda reacts to dropping/uploading...

**Comment by gashcrumb** [comment]
Well, at least it's supposed to when it works :-)

**Comment by gashcrumb** [comment]
Before:

![capture](https://user-images.githubusercontent.com/351660/42891602-b93797b2-8a7d-11e8-82ad-44a0b154400b.PNG)

And then after:

![capture](https://user-images.githubusercontent.com/351660/42891639-d74557a8-8a7d-11e8-8d82-f3ff561df72a.PNG)

**Comment by dongniwang** [comment]
@gashcrumb - do you mean we already have the confirmation message within the drag and drop area?  Yeah, if we have that confirmation, then no need for a toast I guess. 

So maybe the issue is we need to explain what should happen next to users so it's clear for them that they need to check the connections and reconfigure if necessary. 

cc: @sjcox-rh @TovaCohen

**Comment by gashcrumb** [comment]
Yeah, am going to investigate what I can do on top of what's there.  The API response doesn't contain the info needed to show the config required message as needed for the connections, but maybe I can come up with something.

**Comment by TovaCohen** [comment]
It sounds like there needs to be a message that says something like:

One or more imported connections are not yet valid. In the left panel, click **Connections** and look for connections that have **Configuration Required** at the bottom. For each of these connections, edit it to update its parameters and then validate it.

**Comment by sjcox-rh** [comment]
Agree with @TovaCohen. I'm fine with removing the toast message since the import is officially successful from the import screen. However, I think we should still utilize an inline notification that calls out that the user has to configure certain connections. 

In the design, for single imports the user is taken to the integration details page so show an inline notification at the top (ignore the toast since we are removing it going forward) We can use the text that Tova suggested above and have a link to the connections page within the notification.

With multiple imports, just use the same inline notification at the top of the integrations list page.

<img width="751" alt="screen shot 2018-07-20 at 9 29 16 am" src="https://user-images.githubusercontent.com/16257540/43014108-f5da4a2e-8bff-11e8-9297-ec15de8b0ba1.png">

@dongniwang @gashcrumb @tplevko Thoughts?
