### ISSUE TITLE
Integrate Apicur.io

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2617]
This is the main epic. See detailed subtasks

**Comment by kahboom** [comment]
It kind of feels like this should be renamed, as we are no longer evaluating, but actually implementing. Not sure..

**Comment by heiko-braun** [comment]
Done

**Comment by heiko-braun** [comment]
@kahboom @paoloantinori What about the remaining issues attached to this epic? Should these be moved to a new epic or do we simply drag this along?

**Comment by kahboom** [comment]
Was wondering this same thing @heiko-braun , and I think we need a new user story if it makes sense to @kcbabo (I closed this one: https://github.com/syndesisio/syndesis/issues/2750).

So, I think since the integration has been completed per the user story, it should be safe to close this one and we can open a more specific user story and attach subsequent issues (I think there was only one that got pushed forward, the one requesting additional details and perhaps to add some backend features for the review page for the URL-requested specifications).
