### ISSUE TITLE
Backend - Give more details on the publishing process

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2619]

**Comment by dhirajsb** [comment]
After a few implementation iterations, I've settled on an out of band status monitoring of sorts. Trying to shoehorn status details into existing publish process turned out to be error prone and it still left the status lookup decoupled from the `IntegrationDeploymentState`.

So, the implementation uses the same strategy as logging, metrics, etc. controllers, where it looks for integration deployments with `Pending` state first. Then it dives into build and deployment pods to figure out the actual `IntegrationDeploymentStateDetails`. The details also contains API urls for events and logs. Depending upon whether/how the UI can access it, we can massage it so the end user can see the events or logs depending on integration state. 

There is a new `monitoring` endpoint, which can return the publishing state details for a given integration, or all known _publishing_ integrations. 

Note that since it's polling, the details could be slightly out of sync, especially after the integration pod starts, and is marked as published in `IntegrationDeploymentState`. 

I am also pushing a PR for an initial version of this feature. There are still some issues to be ironed out, especially cleaning up stale state. But, let's start with an initial implementation and go from there, especially since UI is waiting on a backend endpoint to start using for state updates.

**Comment by dhirajsb** [comment]
Opened PR https://github.com/syndesisio/syndesis/pull/2947 to resolve this on the backend.

**Comment by gashcrumb** [comment]
@dhirajsb awesome!
