### ISSUE TITLE
Investigate how to expose REST apis

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#2648]

**Comment by nicolaferraro** [comment]
@chirino , @rhuss , @zregvart , @lburgazzoli wdyt about the approach above?

If I've understood it correctly, @lburgazzoli was also suggesting that the "expose" function can also be executed by the integration, that can "register" itself using a pluggable strategy (new Camel feature related to serviceCall EIP). This may require permissions on the pod service account.

**Comment by nicolaferraro** [comment]
Yes, Traefik or 3scale, we need a dynamically configurable reverse proxy for REST (not for webhooks).

I love the idea of showing the same connection as start and end of a integration in case of in-out (req/resp) interaction. A lot effective!

About webhooks being in-only connections... It's true that the response in webhooks calls is completely unuseful for the caller (except for http status code). Webhooks are asynchronous notifications.

But some providers require a verification on the endpoint (i.e. the endpoint must reply to a challenge in a specific way) before they start to send data. E.g. [Facebook/Instagram](https://developers.facebook.com/docs/graph-api/webhooks/getting-started) or [Slack](https://api.slack.com/events-api#subscriptions). I've summarized this problem in #2666.

If we want to support those webhook providers we can either:
- Take care of the verification phase in the webhook connector: difficult because of fragmentation and no standards among providers
- Make the webhook connector "input-output", to allow citizen users to handle the verification requests in the syndesis route: easy, for us...

**Comment by zregvart** [comment]
I think we should also discuss some form of grouping for integrations. It's quite common that you want to provide multiple REST endpoints and it would be a bit wasteful to have each endpoint occupy single integration pod.
Example would be doing CRUD on a database: this would consist of REST API with the usual GET/POST/PUT/DELETE endpoints and users would need to create 4 integrations to implement them.
It would make sense to have some sort of grouping functionality that in turn deploys multiple integrations in the same integration pod.

It would be also very nice if we could offer Swagger/OpenAPI specifications for the exposed endpoints, not sure if we can get that out of the box with Traefik or 3scale, but Camel has this functionality. There is support in Camel for starting from Swagger specification and generating REST DSL (at runtime, in .java or XML).

**Comment by nicolaferraro** [comment]
Yes, grouping is something to consider for REST, but it complicates our internal model and also the building phase we have discussed in the call today. It may also introduce unexpected runtime errors because of the flat classpath.

For the swagger -> integration. I imagine this is one of the main topics for the apicur.io story. Users can design apis in apicur.io, that produces a openapi spec that we then use to design integrations.

We can then configure the reverseproxy/gateway to publish the openapi spec designed by the users and forward API calls to the integrations. But this is [another story](https://github.com/syndesisio/syndesis/issues/2224)...

**Comment by paoloantinori** [comment]
To  give you a different perspective, I will look at this from a different use case.
Imagine that if this "exposing rest" starts from a swagger file, the reasonable expectation is to expose all the endpoints defined there ( or all those that the user haven't edited out).
This is an implicit group, but at also most likely our most common scenario.

**Comment by chirino** [comment]
+1 on using an API gateway.  I do think we need to start **looking** into co-locating integrations onto single JVMs.  I don't think we necessarily need to group them by APIs.  I think as long as there is a gateway in front, we don't need to figure the co-location issue right at this moment, so I would defer that part.

**Comment by paoloantinori** [comment]
@nicolaferraro  you are probably in the best position to comment on this pending activity.

This was supposed to be an investigation step. Are we satisfied with our analysis or should we keep this open?

**Comment by nicolaferraro** [comment]
We can close this discussion here and use it as basis for future work on REST.
