### ISSUE TITLE
Please consider moving the issue tracker to Jira at issues.jboss.org

### ISSUE THREAD

**Issue by apodhrad** [syndesisio/syndesis#2657]
Please consider moving the issue tracking for Syndesis/iPaas/Ignite to Jira at issues.jboss.org.

Since it is a part of Fuse product it makes sense to track all issues at one place together with other Fuse components.

**Comment by rhuss** [comment]
From an engineering POV (well, from my POV actually), the killer feature for using GitHub issues is the tight integration between Pull Requests and issues, eg. seamlessly refering each other by their plain number, automatically closing issue with Git comments, simple labeling, our pure-bot support, and many more ...

I really would feel less productive if I would be forced to move to a system outside of GitHub with is the central place for all our coding work.

At least for upstream work on Syndesis I really would like to stick to GitHub issues.

**Comment by gashcrumb** [comment]
It would most likely make sense to use Jira for *product* issues, i.e. bugs that come out of customer engagements etc.

But yeah, I'd rather keep github issues for all upstream work.  We can always link issues between Jira and github as needed to further track upstream work and it's impact on the product.

**Comment by rhuss** [comment]
@syndesisio/all hey guys, could you please vote on this issue (thumbs up/down on the initial description) as there was (for whatever reason) the impression that "only one random developer guy" is against moving from GitHub issues to the JBoss JIRA for doing upstream development.

**Comment by KurtStam** [comment]
+1 for jira for ignite production issues, and GitHub issues for the syndesis project.

**Comment by oscerd** [comment]
+1 for JIRA for production issues, and GitHub issues for the upstream project.

**Comment by apodhrad** [comment]
Hey guys, thanks for your feedback. I really appreciate that.

The reason why I mentioned "only one developer is against" is that I wanted to know whether more developers have similar opinion (this wasn't obvious to me from the email communication). Probably the question
"Are there more developers who prefer GitHub issue tracker to Jira?"
would sound much better ;-)

**Comment by iocanel** [comment]
Jira, just means having to look at one additional place. Unless of course
we completely disable github issues (like jenkins does) which is
furstrating for the users.

On May 18, 2018 09:00, "Andrej Podhradsky" <notifications@github.com> wrote:

Hey guys, thanks for your feedback. I really appreciate that.

The reason why I mentioned "only one developer is against" is that I wanted
to know whether more developers have similar opinion (this wasn't obvious
to me from the email communication). Probably the question
"Are there more developers who prefer GitHub issue tracker to Jira?"
would sound much better ;-)

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/syndesisio/syndesis/issues/2657#issuecomment-390103072>,
or mute the thread

**Comment by rhuss** [comment]
I think we are good to close this.
