### ISSUE TITLE
generate json schema for extension automatically

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis#2724]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When model is modified, the json schema currently needs to be updated manually. it has been forgotten already (see https://github.com/syndesisio/syndesis/issues/2719 )
it will be better to generate on each build or to fail the build if the a modification is detected

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by lburgazzoli** [comment]
Please note that the internal model is not guaranteed to be the same as the extension one and it can evolve without requiring the extension developers to adapt their scheme. 

We also need to think about how the scheme is used as if the scheme generated by the model is used as it is, it may trigger false positive as some mandatory fields are automatically added by the syndesis-extension-plugin and that's why the generated scheme is not generated/updated automatically and it is not in sync with the model.

@paoloantinori I guess it would be nice to create an epic for this topic.
