### ISSUE TITLE
Syndesis UI not displaying integrations/connections

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#2941]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

There seems to be an issue when I try to display "integrations" and "connections" page.

## Screenshot

![syndesis_not_working](https://user-images.githubusercontent.com/4180208/42159042-b649a3c0-7df2-11e8-89fb-dce4875cb396.png)

## Tasks involved / Steps to Reproduce

1. syndesis from master is running
2. try to access integrations/connections page

**Comment by gashcrumb** [comment]
Is this after a pull/rebuild of master?

**Comment by gashcrumb** [comment]
Rebuilding locally to reproduce and have a look, likely came from the Angular 6 upgrade.  Hit #2942 on the way too.

**Comment by gashcrumb** [comment]
Using `yarn start:minishift-aot` yeilds:

![image](https://user-images.githubusercontent.com/351660/42165967-96e9adc4-7dd7-11e8-8941-2cb7e31d0ae4.png)

**Comment by gashcrumb** [comment]
So cause appears to be due to an older version of `ngx-bootstrap` getting pulled in, we're looking at upgrading to `patternfly-n`g 4.x which depends on a newer `ngx-bootstrap` version that'll work with Angular 6 in the linked PR, changes there appear to fix the issue, @seanforyou23 is going to continue working on that branch to see what other changes might be needed for this upgrade.

**Comment by gashcrumb** [comment]
Please re-open if this still isn't sorted, thanks!
