### ISSUE TITLE
Failure while installing Syndesis without routeHostname

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#3093]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Installing Syndesis via operator without a route hostname cause errors in the process.
This should be handled differently, i.e. validate the custom resource to avoid accepting something without route hostname, or better auto-generating the route hostname if that is missing from the CR config.

## Expected behavior

If a CR is submitted without routeHostname, it should be refused or the operator should generate one.

## Screenshot

N/A

## Request and Response Data

N/A

## API Endpoints and Schemas

N/A

## Tasks involved / Steps to Reproduce

1. Install the operator and the Syndesis CRD in a namespace
2. Create a Syndesis CR without .spec.routeHostname
3. Observe the error in the operator logs and partial resources created

**Comment by rhuss** [comment]
@nicolaferraro is the error because the template parameter for the route hostname is marked as mandatory ? I _think_ it should be possible to create route without that parameter so that its get autopopulated by OpenShift.

However I also believe (not 100% sure) that we need the route hostname in a different context, too. If so, we could first create the Route and then re-read the autogenerated route to insert it elsewhere it's required.

**Comment by nicolaferraro** [comment]
Yes, that is the same approach used now with the service account (for getting the auto-generated token). If the hostname is not specified in the route, we can get it from Openshift when it is generated, then we pass it to the other resources.

**Comment by rhuss** [comment]
ok, so lets try to relax the constraint on the parameter in the template.
