### ISSUE TITLE
Integration import results UI

### ISSUE THREAD

**Issue by michael-coker** [syndesisio/syndesis#3101]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## problem1
When I import an integration, the results seems to list all of my integrations in the import results area. Shouldn't that just list the integration(s) that were imported? I only imported one integration in the screenshot below.

To reproduce:

1. Create more than one integration.
2. Export one of your integrations.
3. Import it.
4. You should see all of your integrations listed in the import results area.

![screen shot 2018-07-17 at 9 24 56 am](https://user-images.githubusercontent.com/35148959/42824896-6f82a684-89a6-11e8-9bf4-709d72eda726.png)

## problem2

If I remove the connections that an exported integration used, then import that integration, the import results list and buttons render but with no content for a moment. After a second or so, those areas populate with content. This seems to be dependent on the system speed and is much more apparent on staging.

1. Create an integration with 2 connections.
2. Export the integration.
3. Delete the integration and the 2 connections it used.
4. Import the integration.
5. Observe an empty results list and tiny buttons with no text.

![screen shot 2018-07-17 at 9 49 18 am](https://user-images.githubusercontent.com/35148959/42825014-b6565678-89a6-11e8-8169-2f9f1169c025.png)

cc @dongniwang

**Comment by dongniwang** [comment]
Reference: 
https://github.com/syndesisio/syndesis/issues/3098
https://github.com/syndesisio/syndesis/issues/2582

**Comment by gashcrumb** [comment]
Looking back at the designs, in the list there's the 'Integration Name' and 'Connection Name' in bold, is that actually just supposed to be the integration/connection name?

**Comment by michael-coker** [comment]
@gashcrumb maybe @sjcox-rh could verify, but it looks that way to me. There should be 1 "integration name" (the name of the imported integration), and 2+ connection names (connections used in the imported integration)

**Comment by gashcrumb** [comment]
Yeah, this page needs some work.

**Comment by gashcrumb** [comment]
Also there's no 'Cancel' vs 'Done', when you drag/drop a zip file, it's imported immediately.  I'd recommend doing away with Cancel for now as it's no different from 'Done'.

**Comment by michael-coker** [comment]
@gashcrumb related - https://github.com/syndesisio/syndesis/issues/2587

**Comment by gashcrumb** [comment]
@michael-coker awesome, snagged that one too, better ping him on IRC too actually.

**Comment by sjcox-rh** [comment]
@michael-coker @gashcrumb I can see why there's confusion. You are both right, the integration and connection name is meant to be bold, not a label. I realize now that's not clear!

Also agree that this page could use some tweaking. 

<img width="718" alt="screen shot 2018-07-17 at 12 11 23 pm" src="https://user-images.githubusercontent.com/16257540/42840083-908def82-89ba-11e8-8f3c-a78a2ddcfeb3.png">

I made some minor tweaks and wanted to get your thoughts. Number each integration imported (since we can upload multiple) and list out connections used within each integration indented under the integration. (Only integration name is bold).

Let me know your thoughts! Fyi - @dongniwang

**Comment by dongniwang** [comment]
The updated design looks good to me! @sjcox-rh 

@gashcrumb - on a separate but related issue, is the "Configuration Required" showing up at all in the implementation of this screen? (see https://github.com/syndesisio/syndesis/issues/2602)

**Comment by gashcrumb** [comment]
@sjcox-rh I'd suggest breaking out connections separately in some fashion.  You can import multiple integrations that share the same connection that could/would get imported/created.

And honestly from the API response I actually have no idea if a connection gets created because it was imported or if the integration just references it.  I'm making a best effort here based on the step array :-)

@dongniwang I added the 'configuration required' bit and I think it *could* maybe show up, but I'm not 100% sure.  At the moment I'm just fetching integrations after the import completes, and then looking in the step array of each integration for the embedded connection instance, I'm not 100% sure if that would contain the object that indicates it needs configuration or not.  If it does it'll show up but in the exports I tested I don't think it actually needed configuration changes.  But the support is there if the API embeds that information in the response.
