### ISSUE TITLE
syndesis install and builds commands create images in conflicting docker repositories

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#3122]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Running openshift using 'oc cluster up' from docker. Therefore, to get syndesis up 'n running I use 'syndesis install' which creates images in the docker repository, by default, as:
* docker.io/syndesis/syndesis-server
* docker.io/syndesis/syndesis-meta
* docker.io/syndesis/syndesis-ui

So I do some work locally then compile syndesis using 'syndesis build'.
If I add the '--docker' switch the image repository for the images becomes:
* syndesis/syndesis-server
* syndesis/syndesis-meta

If I don't add the docker switch (or add the --openshift), the s2i images become:
* 172.30.1.1:5000/syndesis/syndesis-server
* 172.30.1.1:5000/syndesis/syndesis-meta
(where the ip is the openshift installed registry address)

The consequence is that the build and deployment configurations provided by the templates continue to pick up the original images and not the newly built ones.

## Expected behavior

Both syndesis scripts should have the flexibility to work in concert in that the location of images should be either correctly determined automatically or at least a switch placed on each to allow the registry to be specified.

## Tasks involved / Steps to Reproduce

1. Exec 'syndesis install  --dev --debug --watch -y --local'
2. Note the repository of the pulled-in images by doing 'docker images | grep syndesis'
3. Exec 'syndesis build -f -b --docker' to witness the creation of the second set of images
4. Exec 'syndesis build -f -b --openshift' to witness the creation of the third set of images

**Comment by zregvart** [comment]
I think @rhuss might help us here. But I think you need to _patch_ the image streams, i.e. run `syndesis install --dev`.

**Comment by rhuss** [comment]
If you use `--docker` mode for building you also need to use --dev for `syndesis install` as this are the templates using direct Docker images and not image streams.

As described in https://doc.syndesis.io/#syndesis-install there are two mode:

* The 'regular' mode which use imagestreams and s2i, which automatical triggers a redeployment after a s2i build
* The (now deprecated) dev mode which use plain docker images and a deploymentconfigs which reference the Docker image directly. In order to trigger a redeployment you have to kill the pods to pick up the new image. `syndesis build` has support for killing the pods, too.

Currently, we are using the s2i mode also for development as it automatically triggers a redeployment, too. Actually we are really considering to remove the dev mode (with the plain  Docker build alltogether).

Does this answer your question ?

**Comment by phantomjinx** [comment]
@zregvart @rhuss 
So I happen to have been running 'install' with the --dev but looking at the script it only modifies the name of the image to $is:latest (where $is is syndesis-meta, syndesis-server etc...).

If we forget the straight docker mode and focus on the disparity between 'install' and 'build', the 'install' script assumes docker.io as the image repository by default while the 'build' script finds the openshift repository as uses that instead.

I am thinking that there should at least be a switch on the 'install' script that allows me to specify the docker-repository and provides a value for the 'oc new-app' parameter of SYNDESIS_REGISTRY. This latter parameter is what defaults to docker.io.

WDYT?

**Comment by zregvart** [comment]
I can't really wrap my head around this, kinda goes at what would be the best practice and I'm not sure I'm experienced enough to make claims. So I'll let @rhuss and @phantomjinx hash out what works best.

**Comment by rhuss** [comment]
I think we found the primary issue already in the chat.

However, we have to distinguish between the scope of `install` and `build`:

* *install* is for generally installing Syndesis without requiring a prior build. It's the skeletion of our current way to install Syndesis. Therefor it has to refer to a registry outside the cluster. For upstream, this is docker.io, for Fuse Online, it's redhat's registry
* *build* is for creating the Docker images locally. In order to bring it into a running cluster these images could be either pushed to a registry, or, as we do, using s2i to update an imagestream. So we need to tweak the installation that it does not refer to the Docker registry but to this stream updated by an s2i build. Therefor this post-install patching step when using `syndesis install --dev`.

The registry btw is part of the OpenShift template which is used for installation and which creates the imagestreams, not provided by the script directly. I'm not sure how a switch to install would help much to let it point to a different registry (you typically don't know the internal address of the OpenShift registry except by fiddling around).

Tbh, I would prefer to *reduce* the options how we create images during our build process to avoid the confusion we had. So I opt for removing --docker from `syndesis build`.

**Comment by phantomjinx** [comment]
So agree with @rhuss, the primary issue has been resolved. The nature of the problem was that the patching of the image streams during the --dev install was NOT being applied since the scripts were prematurely extiing due to the version of oc/OS being 3.7.1 (which lacks the cron templating API). My lack of knowledge meant I didn't notice the problem until I reran with @rhuss' help.

Therefore, in my view the issue is mute and there is no conflct between install and build. Minor issues may remain in
* Verifying/enforcing the minimum version of oc (see [PR 3146](https://github.com/syndesisio/syndesis/pull/3146) 
* Removal of the --docker switch (I'll defer to @rhuss)

**Comment by rhuss** [comment]
@phantomjinx for `syndesis minishift` #3144 updated to 3.9.0 as the default version which was forgotten.

I agreed that we should check for the minimal version of openshift when running with `syndesis`

Also agreed that we should remove or at least highly deprecate the plain docker build `--docker` as there are no corresponding templates anymore which would refer to plain docker images. The template generator would still be able to generate such template but we just do not generate them. The `-dev` flavor also uses imagestreams.

**Comment by heiko-braun** [comment]
@rhuss @zregvart Do we need to act on this in this sprint?

**Comment by zregvart** [comment]
> @rhuss @zregvart Do we need to act on this in this sprint?

naah, it's not user facing only developer facing issue, but we seem to be close to having this closed, if @phantomjinx really wishes to tackle this one I would not stop him though :)

**Comment by rhuss** [comment]
#3146 fixes the check for the minimal version, I think we are good to close this one. #3169 is for the removal of `--docker`
