### ISSUE TITLE
Telegram Receive Message action does not reflect chat Id property

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#3168]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

Telegram does not listen and answer to correct chat Ids specified in the integration.

## Reproducer: 

Create integration: TELEGRAM receive ==> DATA MAPPER (map text to text) ==> TELEGRAM send
Specify different chat Id's for receive and send telegram actions.

### problem 1
Send a message to the chat you used in receive action. The integration will respond to the same chat instead of the chat you specified in telegram send action.

### problem 2
Send a message to the chat you used in send action. The integration will also respond to this chat even though it should not even listen to this chat.

### note 1
The telegram send action works as expected when tested separately.

@nicolaferraro

**Comment by mcada** [comment]
You forbid setting chatId for receive action - I do not like it but whatever. The issue is still present - bot listens to all chats where he is present even when receive action has tool tip: "Receive all messages sent to the chat bot". Sending message "/qqq" to another channel where the bot is present - not straight to the bots chat, will trigger the integration. From my POV this is still the same problem - reopening.

**Comment by nicolaferraro** [comment]
@mcada, as I've said in the PR, I've removed the chatId from the receive action because the Telegram bot API [does not allow filtering](https://core.telegram.org/bots/api#getupdates) by channel. For each bot, the API allows for a single message consumer, so you cannot set two consumers listening for the same bot on two different chats. This holds true even if using the [webhook strategy](https://core.telegram.org/bots/api#setwebhook) (that is not currently implemented in the Camel component), because only one webhook per bot can be set.

So filtering is not a option at the receiver side. The integration will receive all messages that the chat bot is allowed to read, i.e. messages sent directly to the bot and messages sent to the bot and other participants in a channel. Messages starting with `/` are specifically targeted to all bots listening to a channel.

**Comment by mcada** [comment]
Sorry, I just saw failed tests and could not recall all the details. I will check if this is somewhere in documentation and if so, I will close this issue. Thanks!

**Comment by mcada** [comment]
Well, looks like Telegram has no documentation :/ But since it is tech preview it does not trouble me that much that customers wont know that bot commands from different channels will trigger the integration. They will either figure it out as in our case or they will ask us. Closing.
