### ISSUE TITLE
Activities disappeared after DB cleanup  

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3396]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Activities right after stopping integration (after 2,5 days of running):
![screen shot 2018-08-17 at 12 39 56](https://user-images.githubusercontent.com/6814482/44263722-5562ed80-a220-11e8-9fb8-4059f56c487e.png)
15min later..:
![screen shot 2018-08-17 at 12 54 59](https://user-images.githubusercontent.com/6814482/44263748-6ad81780-a220-11e8-86a6-e39f33687779.png)

 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by zregvart** [comment]
This probably has to do with how we discard older activity entries from the database. We don't have a way to do chronological queries with JSONDB, so we rely on the paths to be ordered in chronological order. We currently should keep latest 50, this is the query that removes everything by the latest 50:

https://github.com/syndesisio/syndesis/blob/a78b251c47b1587f4ad052366c06fbed8664351f/app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java#L158-L161

I think all we're missing is to change to `ORDER BY path DESC`.

**Comment by zregvart** [comment]
@mmelko I've tested the PRs for this locally and it looks good. The plan is to release a new version today when those PRs are merged.

Since you tested the performance/loss of activity entries over a long period I think you don't need to test this again over a long period. I've tested this by just generating > 50 entries and then stopping the integration and waiting for the cleanup task to kick in, should be every 15mins.
