### ISSUE TITLE
Create/investigate using reusable components out of client API connector wizard

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#3474]

**Comment by gashcrumb** [comment]
Here's the [overall api connector wizard](https://github.com/syndesisio/syndesis/tree/master/app/ui/src/app/customizations/api-connector/api-connector-create) code, for whatever reason the [review](https://github.com/syndesisio/syndesis/tree/master/app/ui/src/app/customizations/api-connector/api-connector-review) component is outside of this directory.  I think this bit of the app uses redux, I don't envision though that it should make reusing some of these views difficult, but something to be aware of.

**Comment by riccardo-forina** [comment]
In PR #3676 I created a new module named `openapi` that expose 3 new components:

* a custom form field to upload a specification from the local filesystem / a remote url / create a new one from scratch
* a review component to render the validation response results
* an editor component, that embeds Apicurio

I then used these components in the API Provider create page, new in that PR.

They are not drop-in replacement though, the new page is fully based on Redux, so some heavy refactoring of the Customization section will be required in order to use them.

**Comment by gashcrumb** [comment]
> Should we close this issue and create a new one in the back-lock as a reminder for this activity perhaps?

+1

**Comment by riccardo-forina** [comment]
Follow up: #3677
