### ISSUE TITLE
Syndesis template for deploying "the old way" references syndesis-operator service account

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#3514]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

In the "old school" template, that is used to deploy syndesis without the operator, we reference `syndesis-operator` service account that is obviously not present. 

https://github.com/syndesisio/syndesis/blob/master/install/syndesis.yml#L1632

This will cause problems with upgrade in the environments where the operator can't be used.

## Expected behavior

Upgrading "the old way" by deploying the upgrade pod should not require the `syndesis-operator` service account

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by heiko-braun** [comment]
Does this block of from rolling out 7.1 to the cluster we operator?

**Comment by avano** [comment]
@heiko-braun no, this is just a followup from #3460 and the discussion continues there, do you want to leave this open for tracking purposes or do you want to close this?

**Comment by heiko-braun** [comment]
To summarise:

- Only matters to template based installations
- Only applicable to upgrade use cases
- Can be postponed to 7.1.1

**Comment by rhuss** [comment]
Actually for non-operator based installations the upgrade template defined within the syndesis template is not used. Instead, the upgrade pod is supposed to be instantiated manually (by creating a plain pod definition).

**Comment by heiko-braun** [comment]
@rhuss What about @avano statement that 

> Upgrading "the old way" by deploying the upgrade pod should not require the `syndesis-operator` service account

Is this a valid assumption?

**Comment by rhuss** [comment]
Yes, that's true as the user who calls the pod has to have the appropriate permission (same as the `syndesis-operator` SA which is used by the operator when creating the pod)

**Comment by rhuss** [comment]
Is there still anything todo here ? As mentioned, the service account is referenced in the upgrade-pod template for the operator only (its doesn't make sense to instantiate the update pod for the current version, you would need to have the update pod the version to update).

So although this SA is referenced there it shouldn't harm. @avano or do you see some negative impact of the SA elsewhere ?

**Comment by heiko-braun** [comment]
I guess it means that the SA setup needs to be provided by the user even if they want to use the template approach, right? If that's just it, I would say we can document it and close this issue.

**Comment by rhuss** [comment]
No, thats not the case. Only when you *apply* this upgrade template which references the service account. But a Syndesis template user wouldn't apply the upgrade template as should create the pod directly. 

I know, this sounds a bit confusing but the complexity is a bit due to the fact that we have to support two ways of installing Fuse online:

The Fuse Online Template contains another, nested Template for the upgrade. So, when you apply the outer Template (the Fuse Online one) then just an upgrade template is created (but not applied). You then could manually apply this just created update template, but that won't work out for you as it would update to the version that correspond to the outer template (so to the version which is currently running).

The operator can extrat this upgrade template from a next-version Fuse Online template without applying the outer template. So an new-version operator can apply a new-version update pod.

For the non-operator based approach one needs to manually create the pods for the upgrade which correspond to the new-version. This is not yet implemented really and it affects "only" Fuse Online OSO which we have under full conrol (i.e. we have to create this upgrade pod for every existing installation when we do an new version, project-by-project. Another reason why should switch to operators ASAP).

**Comment by rhuss** [comment]
IMO this issue can be closed, but I would like to have some kind of confirmation from @avano beause I might have overseen something.

**Comment by heiko-braun** [comment]
@avano Have you seen Rolands comment? Any thoughts on this?

**Comment by rhuss** [comment]
I still think that can be closed. Please let me know if there is still something to do from my side.

**Comment by rhuss** [comment]
@heiko-braun is it ok that pure-bot moved that issue back to 'backlog' ? btw, I missed the reason why this is reopened.

**Comment by heiko-braun** [comment]
My bad: Manual intervention and wrong bot configuration.
