### ISSUE TITLE
Simplify testing of CR builds

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#3534]
Testing CR's is fairly complicated at the moment. We need to improve the setup from `fuse-online-install` and enhance the documentation around this.

**Comment by heiko-braun** [comment]
@lburgazzoli @nicolaferraro Please add your thoughts here

**Comment by heiko-braun** [comment]
@tplevko Your feedback would be good as well.

**Comment by nicolaferraro** [comment]
One of the main problems I've noticed is: in order to test brew images, one need to setup minishift for using insecure registries, and this includes creating a new minishift installation from scratch with the insecure flags, and then hacking around the Openshift configuration to make them whitelisted.

The productization phase is also complicated by the need to set the insecure annotation on every image stream.

Wouldn't it be easier to add a certificate to the brew repo and deliver images via https?
registries under `*.redhat.com` are also already whitelisted in Openshift.

**Comment by tplevko** [comment]
@heiko-braun In QE's test suite, we addressed this problem with automated installation of productized images on minishift (or OCP), with steps described by @nicolaferraro under the hood. Even though we need quite extensive manual configuration prior to the test suite run and template updating for Operator image, it can be done, but in my opinion can be error prone. In case there would be an easier way to do this, QE is really interested.
