### ISSUE TITLE
Wrong number of filtered items in some sections

### ISSUE THREAD

**Issue by riccardo-forina** [syndesisio/syndesis#3613]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Sections with a filterable list don't show the right result number if filtering is implemented using the `objectPropertyFilter` pipe. 

## Expected behavior

The number of results should be right.

## Screenshot

![filter-bug](https://user-images.githubusercontent.com/966316/45693865-55774580-bb5e-11e8-9f18-c1272d9fbb88.gif)

In this gif the bug is reproduced in the Settings page and in the Operations page of an integration of type API Provider. The Integrations list page is unaffected because filtering is implemented without the pipe.

## Tasks involved / Steps to Reproduce

1. Go to any section that uses the `objectPropertyFilter` pipe. Eg. the "Settings" page.
2. Search something that's present in the list. Eg. "mail".

**Comment by gashcrumb** [comment]
I think the method the integration list page is using is the way to go, as there's a couple flaws in the method used for the OAuth settings page, so I'll go ahead and update these pages and ensure all the other pages are aligned as well.

**Comment by gashcrumb** [comment]
I've updated the oauth app page locally to work similar to the integration list page.  I then was checking some other pages and realized that the step select page in the integration editor is set up sorta the same but works, and it looks like it's because of -> https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/step-select/step-select.component.ts#L114

I was going to update this page but the toolbar in this case is slightly special as it's supposed to filter the list to just show steps provided by extensions when you pick "Custom Step" from the filter toolbar drop-down.

And I dunno @riccardo-forina , do you want me mucking around in the choose operation page?  I could update that too but I think if you just set the results count then that filter should start kinda working.  I forget if there's more complicated filtering requirements for that page.

**Comment by riccardo-forina** [comment]
[Swagger Petstore-export.zip](https://github.com/syndesisio/syndesis/files/2397032/Swagger.Petstore-export.zip)

@gashcrumb that's the export of the PetStore multi-flow integration you see in the GIF
