### ISSUE TITLE
Import / Export APIs

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3701]
As a developer, I want to have access to import and export apis for Fuse on openshift. I want to be able to build a CI/CD pipeline for my Fuse integrations.
A customer has their own build pipline, and wants to take an intergtation from one syndesis enviroment to another syndesis enviroment. One or multiple apis may be required.
In the future we may need to be able to roll back to a previous deployment.
A failure to depoy should automatically roll back.

DoD
I can build a CI/CD pipeline for deploying a Fuse integration on FuseOnline.

The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

## Related Issues

- https://github.com/syndesisio/syndesis/issues/3615
- https://github.com/syndesisio/syndesis/issues/1959

**Comment by zregvart** [comment]
Related to #1959

**Comment by rhuss** [comment]
Not sure whether I understand properly, but this is about exporting an **integration runtime** so that it can be deployed independently of Syndesis ? Like an archive holding a pom.xml, a Jenkinsfile, the route definition and all code, similar like what we do when creating the runtime during publishing of the integration.

What is meant by import then ? The import we have so far is about importing more or less parts of the domain model (jsondb json snippets). What import is refered to here ?

**Comment by oscerd** [comment]
Actually this is blocked by the inability to use cookies to access syndesis API from outside, related to #967 

You can't access to export.zip endpoint and import endpoint from an Ansible playbook, but even with a simple curl the situation is the same.

**Comment by oscerd** [comment]
The situation is still the same by the way.

**Comment by dhirajsb** [comment]
Merged PR #4344 for backend public APIs. 
Waiting on UI work (almost done) to be finished soon in issue #4494

**Comment by dhirajsb** [comment]
Closing as both backend and UI work is complete.
