### ISSUE TITLE
'Get a specific Event' Google calendar action has wrong pattern defined

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3740]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Google Calendar connector action 'Get a specific Event'(io.syndesis:google-calendar-get-event-connector) is defined with Pattern 'To'.

I think it is wrong, as a get operation is typically a starting step. This way this action is useless.

**Comment by oscerd** [comment]
this is not a priority 0 issue.

**Comment by oscerd** [comment]
Ignore what I've said before. The get Operation requires an header to be set so it can be only a Producer endpoint. The "to" pattern is right. Not a problem. Closing.

**Comment by jstastny-cz** [comment]
@oscerd can you guide me on what 'From' and 'To' patterns mean?
I would expect that the get event would be an initiation step of a flow like:
1. I get a specific event
2. I do something with the info
What is the use case when 'Get event' is an end action? Can I do sth with the result that it returns?

**Comment by oscerd** [comment]
The main difference between From and To is at camel level. When you have a From endpoint, you are usually starting a route from there: so you will probably get something from an external system and consume it (to do this you'll need to get an exchange at camel level). When you have a To endpoint you'll produce something: so you get an incoming exchange, use something from inside the exchange, and send ahead a different exchange (modified) from the endpoint. In case of Producers you may have also headers coming from the past steps of the integration used in the following steps, or you may set some headers through a processor (of the exchange) between the endpoints. In this specific case to get a specific event you'll need to set an header on the exchange and then pass at the next endpoint with this header set, with a From endpoint you can't do this because the exchange which could contain the header is not yet created when you consume. That's why this can be only a To endpoint. If you look at the camel source in different components, you'll see many get* operations on the producer endpoints of these components. Some other components, offers the possibility to specify option at consumer level, like for example a filename or an id, to consume exactly one entity and use it in the following endpoints of a route. It depends a lot on how a component has been developed. Even with a producer endpoint you can have the same behavior: for example you can use a timer that trigger a route just one time, it will be create an exchange and then you'll be able to set the eventId header and pass to getEvent endpoint.

**Comment by jstastny-cz** [comment]
@oscerd  Thanks.
How do I provide the eventId value to the step? I can't put a mapper in front of it currently, can I somehow parameterize the eventId?

**Comment by oscerd** [comment]
Actually you can only specify it through the action form, statically. Let me think about it by the way. We may set the input datashape as a String and check it in the customizer, can you raise an enhancement for this? Maybe linking this issue?

**Comment by oscerd** [comment]
ping @paoloantinori @heiko-braun @gaughan

**Comment by paoloantinori** [comment]
it makes sense to me to open an enhancement
