### ISSUE TITLE
'Send Event' Google Calendar connector action description issue

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3741]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The description of the action Send Event (io.syndesis:google-calendar-insert-event-connector) is malformed. This needs a refinement (problematic part is  '...from to...').
`Send an event from to the Calendar account that this connection is authorized to access.`

**Comment by zregvart** [comment]
cc @TovaCohen

**Comment by oscerd** [comment]
I'm fixing another thing on the calendar side, I'll fix this too.

**Comment by zregvart** [comment]
@oscerd perhaps we could also tweak the action name to say `Create event`:

https://github.com/oscerd/syndesis/blob/ea5fd6d58b0584e108692f5614a93a8d477d7d7b/app/connector/google-calendar/src/main/resources/META-INF/syndesis/connector/calendar.json#L191

**Comment by dongniwang** [comment]
Great work on the connector @oscerd! I know it's probably nit-picking, but any chance we can review the form labels so that they match closely with what we see on Google Calendar? 

For example, Google Calendar uses terms _Guests_ and _guest list_ when referring to attendees. 

![screen shot 2018-10-05 at 9 10 48 am](https://user-images.githubusercontent.com/24943812/46541473-21a05d80-c88a-11e8-85ea-6208b822b05c.png)

**Comment by oscerd** [comment]
Sure :-) I'll try to take a look

**Comment by dongniwang** [comment]
@oscerd - Happy to set up a meeting so we can review it together if needed. Thanks so much! 

cc: @TovaCohen

**Comment by oscerd** [comment]
Sure :-) Next week will be ok!
