### ISSUE TITLE
Template step - can't upload a file nor create template in the editor

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#3760]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I can't upload a template file (nothing happens after selecting a file)
&
Missing template editor:
![screenshot from 2018-10-05 09-13-03](https://user-images.githubusercontent.com/8707251/46594790-7e438880-cad5-11e8-85a1-9fe006362461.png)
![screenshot from 2018-10-05 09-14-21](https://user-images.githubusercontent.com/8707251/46594793-84396980-cad5-11e8-972f-536f168fccb5.png)

**Comment by phantomjinx** [comment]
@mastepan 
It would appear that something in the codemirror module dependency does not like the minification routine used in the productionalization/release operations.

@gashcrumb 
Are you able to shed some light on the minification routine, please?

**Comment by gashcrumb** [comment]
@kahboom can you work with @phantomjinx on this one while I'm out?

**Comment by mastepan** [comment]
I've just updated Syndesis to the latest version and the editor and file upload started to work.
I'm closing this as it seems to be ok.

**Comment by mastepan** [comment]
This issue is present again...I can reproduce it in Chrome and Firefox.

- Editor is unresponsive
- Uploading a template file doesn't fill the editor
- Uploading a template file doesn't enable **Done** button (after 2nd upload try Firefox enables it. Chrome doesn't)



Syndesis:
    1.5-SNAPSHOT

Build ID:
    dd612b39-ed84-477b-9b06-9583a5932028

Commit ID:
    61eea3921d5f03920934677d47747ebdcd0a85f5

**Comment by heiko-braun** [comment]
@phantomjinx This has been reopened by QE, can you take a look please?

**Comment by phantomjinx** [comment]
Latest investigation results:
There seems to be some deficiency in codemirror's [lint addon](https://github.com/codemirror/CodeMirror/blob/master/addon/lint/lint.js#L177) that causes the observed error when production builds uglify the code.

[This](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/264) seems to be a similar issue.

Trying to customise the webpack configuration is proving problematic on account of angular's ng hiding the config particulars. It is possible to get inside and use a custom config, see [here](https://codeburst.io/customizing-angular-cli-6-build-an-alternative-to-ng-eject-a48304cd3b21?gi=2f4870c4bc8a). However, the exact config on this is proving elusive.

**Comment by phantomjinx** [comment]
So latest attempts currently [failed](https://github.com/phantomjinx/syndesis/commit/8ad69c4c26147596e4e1f394ae8825983641747f)

- From [this](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/264) and [this](https://github.com/graphql/graphiql/issues/665) determined the 'ReferenceError: b is not defined' is to do with uglify settings where codemirror's addon 'lint.js' contains an if/else clause that is not compatible;
- Angular's ng does not allow much access to its underlying webpack configuration;
- Used [these instructions](https://codeburst.io/customizing-angular-cli-6-build-an-alternative-to-ng-eject-a48304cd3b21?gi=2f4870c4bc8a) to modify the angular.json and allow access to the underlying webpack configuration;
- Added an additional [extra-webpack-config.js](https://github.com/phantomjinx/syndesis/commit/8ad69c4c26147596e4e1f394ae8825983641747f#diff-7208ecb12e3ff4bea88bdae76da53726) that allegedly changes the configuration of webpack;
- Tried different settings to [exclude 'codemirror' or turn off compression/mangling etc...](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/). However, nothing seems to have made much difference;
- The custom webpack builder configuration used suggests it should work with 'ng serve' as well. However, the latter with '--prod' simply ignored the configuration entirely. Only 'ng build' appeared to observe the new custom configuration file;
- Despite adding items to the config file, nothing appeared to fix the problem.

Would someone else care to shed light on this please? Otherwise the only way I have found to workaround is to essentially turn off optimization in the angular.json file (not good!).

@gashcrumb @kahboom @heiko-braun

**Comment by riccardo-forina** [comment]
One option could be to:
* fork `ng2-codemirror`
* remove [this line](https://github.com/chymz/ng2-codemirror/blob/master/src/codemirror.component.ts#L14) which forces us to have codemirror installed through yarn (and therefore, linted/minified)
* load codemirror from a CDN adding the proper `script` tag in the body 
* change [this line](https://github.com/chymz/ng2-codemirror/blob/master/src/codemirror.component.ts#L79) to look something like `this.instance = (window as any).CodeMirror.fromTextArea(this.host.nativeElement, config);`

I haven't tried this, so it could be horribly wrong on many levels!

**Comment by phantomjinx** [comment]
@riccardo-forina 

Sounds pretty drastic. Is there not traction in the idea of using a custom-webpack config to exclude codemirror? A day of tinkering has got me so far. Wondered if there is still scope for getting over the top.

**Comment by gashcrumb** [comment]
We can't use scripts from a CDN, the web app needs to be a self-contained thing.

**Comment by riccardo-forina** [comment]
Right 🤦‍♂️ The public folder then?

Dunno, tweaking the minify strategy just because of codemirror gives me the creeps for some reason.

**Comment by phantomjinx** [comment]
Can we do a pre-build tweak on the codemirror/addon/lint.js file to fix the code error?

**Comment by mastepan** [comment]
Shouldn't we wait for QE to verify and close this? :)

Verified on 1.5.4-20181023 (Chrome, Firefox)
