### ISSUE TITLE
API Provider 501 status default

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3780]
When I implement a flow, the return status stays on 501, it should be now automatically set to 200.

**Comment by paoloantinori** [comment]
Actually it's not universally assumed that any flow will have to return a 200.
Depending on how strict the requirements are, a user might want to opt for a `201 Created` but even on anything else that http allows you to.

If you are looking for improvements, we might think about a warning or toast notification, suggesting the user to change that value if he needs to, but I don't think we should do it on his behalf.

**Comment by gaughan** [comment]
Agree, but currently, we assume an implemented flow returns 501.
Ideally, you should set it yourself as part of the flow creation.
Removing the 501 is an option (set it blank) and then force the user to explicitly set a return code to proceed.
Setting to 200 or 201 automatically is better than leaving at 501 I think, as long as we are not overwriting a code already selected.

**Comment by KurtStam** [comment]
If the return code is specified in the swagger then we should be using that.

**Comment by nicolaferraro** [comment]
I'm reasoning about this. Usually a OpenAPI operation declares a single 2xx response, so there's usually no ambiguity. Also when there's a single return code, there's no ambiguity. If we treat all non-ambiguous cases, as @KurtStam is suggesting, we're fixing most of the real cases.
Maybe the backend can save the "default" return code into a special field of the integration, so that the front-end can set it by default in the editor when the user starts editing a flow. Non-edited flows will remain with 501 as expected.

Does it work @gaughan ?

**Comment by gaughan** [comment]
Sounds perfect to me @nicolaferraro
