### ISSUE TITLE
API Provider Data Type Mismatch

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3807]
See also **https://issues.jboss.org/browse/ENTESB-11568**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When you provider Todo App swagger to API Provider a data type mismatch occurs on unimplemented flows:

![image](https://user-images.githubusercontent.com/674767/46811671-35900780-cd41-11e8-894c-f04272893466.png)

![image](https://user-images.githubusercontent.com/674767/46811728-5193a900-cd41-11e8-9294-737bb1cd299c.png)

**Comment by zregvart** [comment]
@gaughan this is due to the fact that the start step has the shape of the request and the end step has the shape of the response. This is quite common.

On this particular case we have a difference due to the same reason behind #3788. The response, or the input shape of the end step, is not wrapped in our _standard_ wrapper for APIs that looks something like:

```json
{
  "parameters": {},
  "body": {}
}
```

So with #3788 fixed I hope this particular case will not have a mapping difference. Are you concerned about this case (Create new Task operation) that happens to have the same request/response defined in the OpenAPI specification, or are you concerned that the users might end up with data type mismatch warnings in general with API provider-based integrations?

**Comment by KurtStam** [comment]
Verified that this issue is resolved per #3788.

<img width="1012" alt="screen shot 2018-10-18 at 2 35 25 pm" src="https://user-images.githubusercontent.com/35576/47154615-149c5900-d2e3-11e8-8c89-c9387e56fe1d.png">

**Comment by KurtStam** [comment]
The reason of the mismatch is now more obvious:

<img width="1015" alt="screen shot 2018-10-18 at 2 38 14 pm" src="https://user-images.githubusercontent.com/35576/47154781-8a082980-d2e3-11e8-82de-d241cd0a4f6a.png">

Reason being that there is an extra 'parameters' section on the Target. 

So the question now becomes:

1. Do we not worry about it as it maybe obvious to the enduser as to what's going on.
2. Do we equate equality of input and output shapes if the body is identical.
3. Do we try to add the parameters (Content-Type and Status) on the Source. (I don't think this last option makes any sense)

**Comment by zregvart** [comment]
> 3. Do we try to add the parameters (Content-Type and Status) on the Source. (I don't think this last option makes any sense, though @zregvart is that what you were expecting to happen?)

We can totally drop those, I was on the verge of dropping them but I used the fact that they were there. Could be done better...

**Comment by KurtStam** [comment]
@zregvart ok so we go for option 4 and drop them from the Target side?

**Comment by zregvart** [comment]
> @KurtStam side question, is that icon your own local environment or did we update the atlasmap icon?

@gaughan yup there were a bunch of icon updates in #3842

**Comment by zregvart** [comment]
> @zregvart ok so we go for option 4 and drop them from the Target side?

Yeah, I'd drop them they really have no use and it was silly of me to add them: the status is set on the end step and the Content-Type is determined via the OpenAPI specification. Wasn't very lean of me...

Anyhow now that I've thought of a better way to determine if the data shape is unified or not (via the Syndesis unified JSON schema URN) those are no longer needed.

**Comment by heiko-braun** [comment]
Kurt, once again, please leave these in tge open state, done column. We need this to support the QE workflow

**Comment by KurtStam** [comment]
@heiko-braun oops - sorry, Any way we can do this via a label? That way I stay in Safari.

**Comment by heiko-braun** [comment]
For now you would need to  look at the history: if `pure-bot` reopens, please leave it open. In the future I can add a label that matches the zenhub column.

**Comment by dongniwang** [comment]
Data type mismatch notification is still showing up on the unimplemented flows when using [task-api](https://raw.githubusercontent.com/syndesisio/syndesis-quickstarts/master/api-provider/task-api.json). 

I was using the syndesis-1.5.6.fuse-720003 tag. 

My concern is that users are drawn to the orange notificaiton and they will want to resolve the warning by adding a data mapping step, which is perhaps not neccessary based on my understanding. 

See screenshot below:
<img width="648" alt="screen shot 2018-11-06 at 9 44 35 am" src="https://user-images.githubusercontent.com/24943812/48071556-9c6dd880-e1a8-11e8-828d-d1b50cf3d82b.png">

**Comment by KurtStam** [comment]
@dongniwang can you bring up the data mapper? It will show you why they are different, then we can go after it (again)

**Comment by KurtStam** [comment]
Ready for QE

**Comment by dongniwang** [comment]
@KurtStam - OK. That makes sense. But then I was wondering if we can display the input and output types more obviously in the UI and help users make the understand that the Data type mismatch is because of the differences in the input and output types. 

What would happen if users first add a data mapping step (as the result of seeing the data type mismatch notification), then add more steps or connections in the flow (either before or after the data mapping step they just added)?

**Comment by heiko-braun** [comment]
cc @syndesisqe Can this be verified?

**Comment by tplevko** [comment]
@asmigala can you please provide feedback to eng?

**Comment by asmigala** [comment]
I no longer see the data mismatch in the Create task operation:
![image](https://user-images.githubusercontent.com/9480152/50084534-9d5a4700-01f7-11e9-8966-227f94818b80.png)
This is good


I do see it in the Fetch Task operation:
![image](https://user-images.githubusercontent.com/9480152/50084492-7734a700-01f7-11e9-9902-112c04d9e410.png)
This is also good (the input and output don't match)

I do also see it in Update task:
![image](https://user-images.githubusercontent.com/9480152/50084634-ead6b400-01f7-11e9-8d13-0ca4e2ed93e9.png)
because there's an extra `parameters/id` variable to be mapped (this corresponds to url parameter defined in swagger): 
![image](https://user-images.githubusercontent.com/9480152/50084672-0e99fa00-01f8-11e9-9322-9cc7336aaf25.png)
This is probably ok, but I think it could also be mapped automatically.

However, I don't see it in List all tasks:
![image](https://user-images.githubusercontent.com/9480152/50084838-954ed700-01f8-11e9-8333-f0a2b1908af4.png)
which I think is not ok, because it will result in return nothing.

@KurtStam @zregvart  WDYT?

**Comment by zregvart** [comment]
@asmigala I think the `list all tasks` has no input shape and that's why there is no warning there.

**Comment by asmigala** [comment]
@zregvart right, but is that the expected behaviour? The orange triangle should advise the user that the route in the current state will not return any data unless they do something about it (i.e. add a data mapper). Now I will concede that returning an empty array would be ok here, but what happens in reality is that the response is completely empty.
Not sure this is what we want.

**Comment by zregvart** [comment]
My 2c is that we should create a new issue(s) for refinements. Skimming through seems that we have just one case that we should handle better; the one outlined in https://github.com/syndesisio/syndesis/issues/3807#issuecomment-448948660.

**Comment by gaughan** [comment]
@zregvart I think we should keep this in mind with other API provider enhancements, a more seamless UX is ideal

**Comment by asmigala** [comment]
@zregvart I think this is still the same issue ("When you provider Todo App swagger to API Provider a data type mismatch occurs on unimplemented flows" as in the original report). 

I am ok with closing this and opening a new issue, as this in particular is fairly minor issue, but I think it sets a dangerous precedent on what it means an issue is "fixed".

**Comment by asmigala** [comment]
@zregvart @gaughan have we reached a decision regarding this issue? Current master still does not have the warning as mentioned in my previous comments.

**Comment by zregvart** [comment]
@asmigala I'll move it to backlog so your last point in https://github.com/syndesisio/syndesis/issues/3807#issuecomment-447815848 gets addressed.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11568**
