### ISSUE TITLE
Split Step

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#384]
See also **https://issues.jboss.org/browse/ENTESB-11542**

A new step needs to be introduced which allows the split of an array like message into multiple messages, one for each element in the list.

@kcbabo I wonder whether we require a user story for this ? Or is this already cristal clear. Any configuration options which might be needed ?

**Comment by rhuss** [comment]
We need to start this story ASAP if we want to get something done in this sprint.

@KurtStam you said you would like to take this as a feature owner. Another idea from me was, that @jimmidyson could pick this up.

wdyt ?

**Comment by KurtStam** [comment]
Sure I can pick it up.

On Nov 29, 2017, at 12:59, Roland Huß <notifications@github.com> wrote:

We need to start this story ASAP if we want to get something done in this
sprint.

@KurtStam <https://github.com/kurtstam> you said you would like to take
this as a feature owner. Another idea from me was, that @jimmidyson
<https://github.com/jimmidyson> could pick this up.

wdyt ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/syndesisio/syndesis/issues/384#issuecomment-347943687>,
or mute the thread

**Comment by sjcox-rh** [comment]
@KurtStam @kcbabo 

I want to start working on this story asap but I need additional details before I get started. Is it possible to get a few clear user stories describing the user's interaction with this step, where it can be used, valid parameters, configurable input fields used, etc?

Any info would be helpful, thank you!

**Comment by KurtStam** [comment]
Hi SJ,

It turns out that I’m able to avoid having to use a separate Splitter for the Database connector. So we can push this down the road for now and give it a lower priority. 

—Kurt

**Comment by sjcox-rh** [comment]
Okay so just to clarify, we won't be working on Split step this sprint? I just want to make sure :]

@rhuss @KurtStam @kcbabo 

Thanks!

**Comment by rhuss** [comment]
@sjcox-rh yes, that's correct. We have no spare cycles for the split step and found a 'light-weight' solution for where we would need it by doing the split directly from within the connector.

**Comment by kcbabo** [comment]
@sjcox-rh if we have remaining designs for TP3, then we should prioritize those over split.  If we are done for TP3, then we can start with the user stories and design as soon as you want.

**Comment by rhuss** [comment]
Not sure what to do with this and whether it still in focus for Fuse Online. @heiko-braun could you please resolve the status of this epic with @gaughan / @kcbabo  ?

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11542**
