### ISSUE TITLE
Cannot publish saved integration draft

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#3853]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After editing and saving an already published integration, the integration's detail page indicates that it needs to be republished. However, the Publish button is disabled.

It's still possible to publish the new version by clicking Edit Integration and publishing from the editor.

## Screenshot
![screenshot_2018-10-16_12-00-45](https://user-images.githubusercontent.com/9480152/47008738-27742980-d13b-11e8-92cf-f958b88de094.png)

**Comment by gashcrumb** [comment]
The button is an easy enough fix.  

The warning there shouldn't appear however, wonder @phantomjinx @lburgazzoli is this due to the equivalence checking between what's stored in the DB and what's running?  Ideally if the user makes changes to the integration in the editor just the draft line should show up without any corresponding warning.

**Comment by tplevko** [comment]
@asmigala please verify the fix

**Comment by asmigala** [comment]
Verified with latest master
