### ISSUE TITLE
Template step - {{variable}} mapping by Data Mapper doesn't work

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#3854]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
What's wrong in short:
No data are mapped to a variable used in a template.
If I use **{{variable}} text** as a template and map any data to {{variable}}, output is **" text"**

**Steps to reproduce by creating an integration
DB -> Datamapper -> Template step -> Datamapper -> DB**
1. Create a new integration 
2. Add **PostgresDB** start connection
- select **PeriodicSQL Invocation**
- **SQL Statement:** select * from contact limit 1
- **Period:** 20 seconds or similar
3. Add **PostgresDB** finish connection
- select **Invoke SQL**
- **SQL Statement:** insert into contact values (:#param)
4. Add **Template** step
- create or upload template:
**{{template_param}} Bill**
5. Add **Data Mapper** step between **Start connection** and **Template**
- create mapping: **first_name** -> **template_param**
6. Add **Data Mapper** step between **Template** and **Finish connection** 
- create mapping: **message** -> **first_name**
(message is a result of the template with all it's mapped variables in step 5)
7. **Publish** the integration

Take a look at the contact table in the database.
There should appear a new row with first column containing **Joe Bill** each 20 secs.
Joe from the DB, Bill from the template.

But the new rows contain only Bill. Joe hasn't been mapped to {{template_param}} variable in the template

**Comment by heiko-braun** [comment]
@phantomjinx Can you take a look at this?

**Comment by phantomjinx** [comment]
Hi @mastepan,
The reason the template is not being populated is because you have used _template_param_ rather than _body.template_param_. This is not clearly stated in the documentation (I didn't properly emphasise it). 

Mustache collects and holds variables in a map where the keys are standard items such as 'exchange' and 'body'. Each of these keys has a value of type map. Therefore, the key body.template_param will search body's map for the key template_param, returning "joe".

It may be possible to improve this but due to the complexity and late stage it really is not worth it I think until we revisit when adding velocity and framemaker support.

@heiko-braun @TovaCohen

**Comment by heiko-braun** [comment]
I’d suggest we create a followup issue for sn enhancement and close this one

**Comment by phantomjinx** [comment]
Added a [PR](https://github.com/syndesisio/syndesis/pull/3893) to at least mandate the use of the body prefix on variable symbols.

@TovaCohen
