### ISSUE TITLE
Add $id property to the JSON schema URI in the DataShape

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3914]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
We need to follow this up with a change that includes the syndesis JSON schema URI in the data shape so that `ResponseCustomizer` can detect the need to unwrap the response here:

https://github.com/syndesisio/syndesis/blob/9e99679cd43adf3cfe171d4218ec4f31b2ea83a0/app/connector/rest-swagger/src/main/java/io/syndesis/connector/rest/swagger/ResponseCustomizer.java#L64

That means we need to add `$id`[1] property to the unified JSON schemas. Similar to how the WebHook connector does it:

https://github.com/syndesisio/syndesis/blob/9e99679cd43adf3cfe171d4218ec4f31b2ea83a0/app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java#L39

https://github.com/syndesisio/syndesis/blob/9e99679cd43adf3cfe171d4218ec4f31b2ea83a0/app/connector/webhook/src/main/java/io/syndesis/connector/webhook/WebhookConnectorCustomizer.java#L82

[1] https://json-schema.org/understanding-json-schema/structuring.html#the-id-property

**Comment by heiko-braun** [comment]
@KurtStam What's the expected and observed behaviour?

**Comment by KurtStam** [comment]
Up until we added the default parameters in the message (#3807) we detected the schema by the presence of body/parameters. Now we only have the body, the issue is that if the payload legitimately has a body property then it will not work correctly. Not yet a case we have encountered, but kinda waiting to surface. The proposed id property will address the issue.

**Comment by zregvart** [comment]
This is breaking the response wrapping of the custom API client connector. That's bad. The data shape and the payload now differ which leads to `null` values in the Atlasmap step after the custom API connector.

For example in the attached integration the response of implementing `POST /todo` ends up being `{"id":null,"task":null}` instead of `{"id":10357,"task":"hello again"}`.

So we broke the custom API client connector, is this a `p0` blocker @gaughan?

[Task API-export (1).zip](https://github.com/syndesisio/syndesis/files/2553253/Task.API-export.1.zip)

**Comment by paoloantinori** [comment]
Gary says that if this introduces a regression, we should raise the priority to p0.

**Comment by gaughan** [comment]
Agree it is a blocker if this is a regression on API Client connector

**Comment by heiko-braun** [comment]
@tplevko  Can your team review this ? it should be fixed
