### ISSUE TITLE
Add step before step doesn't work

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#3986]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When I have integration with one step and I want to add another step before that step, the page is blank and in the web console is the errors:
`TypeError: "this.currentFlowService.getPreviousStepWithDataShape(...) is undefined"`
`TypeError: "right-hand side of 'in' should be an object, got undefined"`
But when I want to add another step after that step, everything works fine. So I am able to add middle-steps **only** before the Finish Connection.

## Screenshot

![image](https://user-images.githubusercontent.com/16251792/47651560-db39d800-db83-11e8-83b0-603377d66f30.png)

## Tasks involved / Steps to Reproduce

1. Create integration
2. For starting integration set timer
3. For ending integration set DB
4. Add middle step (e.g. log)
5. Add step after middle step (e.g. another log, works)
6. Add step before middle step 
(Sorry for quality of gif, I don't know why ffmpeg convert it like this)
![output](https://user-images.githubusercontent.com/16251792/47658618-928a1b00-db93-11e8-9b5d-dfe1b41c9a80.gif)

**Comment by heiko-braun** [comment]
@gashcrumb can we get your initial assessment? Please add people as you see fit

**Comment by gashcrumb** [comment]
This behavior is firefox specific I guess, on Chrome I see:

![image](https://user-images.githubusercontent.com/351660/47686356-0a1a7300-dbb1-11e8-9b5a-7f0b42dd55fa.png)

Which I suspect is because the Timer connection doesn't have a data shape, [so this line](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/integration/edit-page/flow-view/flow-view-step.component.ts#L356) throws this error.

The above gif seems to be from firefox, which behaves like the above, unfortunately I can't pinpoint the error from the minified source on staging as firefox's devtools can't seem to unminify the source and maintain the location where the error is thrown from.  My initial thought though is [this line](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/store/step/step.store.ts#L308) or [this line](https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/store/step/step.store.ts#L313) as these are the two spots that I know of where this type of comparison is made which would cause `TypeError: "right-hand side of 'in' should be an object, got undefined"`

Unfortunately I can't seem to get a working development environment or even actually a minishift environment working where I can see the UI locally, so I can't look further.

@riccardo-forina can you have a look when you get a chance?

**Comment by gashcrumb** [comment]
Figured out my dev issue, linked PR should sort it out.

**Comment by tplevko** [comment]
@mkralik3 please verify the fix
