### ISSUE TITLE
Still can't delete a connection after deleting the integration

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#4008]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After deleting an integration, I still can't delete the connections that were used by it, until I hard-refresh the connection page. The `delete` is greyed out until then.

**Comment by christophd** [comment]
I am facing a problem when importing integrations to Syndesis and I think it is related to changes made for this issue.

This here throws a NPE because the connection is not present in the db yet. I think we need to add a null check on `dbConnection`

https://github.com/syndesisio/syndesis/blob/master/app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java#L317

**Comment by christophd** [comment]
@phantomjinx FYI

**Comment by heiko-braun** [comment]
@christophd Does you commit fix the issue?

**Comment by phantomjinx** [comment]
@christophd 
Can this be closed now?

**Comment by phantomjinx** [comment]
Out-of-date .... closing.
