### ISSUE TITLE
As a citizen integrator, use a database connection in an integration

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#403]
As a citizen integrator, I want to connect to databases as part of an integration flow in the following scenarios:
- As a start connection, to periodically execute SQL SELECT commands against a database
- As a step connection, to execute SQL SELECT, INSERT, UPDATE, DELETE commands against a database
- As a finish connection, to execute SQL INSERT, UPDATE, DELETE commands

When using a connection in an integration flow, I expect a single action that allows me to specify SQL of my choice as action configuration.  Once I have specified the SQL I want to use and complete the action configuration step (clicking 'Done'), the following validation should take place:
- Verify that SQL uses only supported commands (SELECT, INSERT, UPDATE, DELETE)
- Verify that all fields referenced in the SQL are valid

If validation fails, I want details on the failure to be reported on the action configuration page.  I should not be able to complete action configuration with invalid SQL.

Any fields referenced by SQL commands in a SQL connection should be available as data shapes within my integration flow, allowing type-aware steps such as data mapper and filter to operate on the specific data used by my database connection.

**Comment by Stefan365** [comment]
@kcbabo @KurtStam 
may I ask what is the meaning of the 'step connection'? (I understood it somewhere in the middle between start and finish connections)
If the command there is SELECT it cuts off previous START connection. 
On the other hand, INPUT, UPDATE, DELETE returns nothing, so in this case it cuts off following FINISH connection.
And If there are more such IN - OUT couples in the integration, this could be expressed as well in more separate strictly START-FINISH integrations.

**Comment by kcbabo** [comment]
Step connections do not necessarily step on any data shapes for an integration.  If data is not changed, then the data shape should stay the same.  Whether or not the runtime handles this well right now is something we should test. :-)

For example, let's say I have a step connection which takes an input and returns no output.  The current data shape after that step executes should be the same as the data shape prior to that step - it would not be replaced by null just because the step has no output shape.

**Comment by Stefan365** [comment]
ok. so according your explanation step connections should be 'transparent'(following Connection should see data 
regardless what happened in previous connection) and that make sense. 

I'm just asking because 
it seems this is not the case for datamapper step for the time being
e.g
If I use 3 connections(START - STEP - FINISH) 
and START connection is "select * from contact",
I can see data from that select in datamapper 1 (between START and STEP)
but not in datamapper 2 (between STEP and FINISH)
And if I choose INSERT/UPDATE/DELETE in STEP, I see no input in datamapper 2
- but no problem I will raise datamapper issue.

Just to be sure: 
if the STEP connection contains e.g. "select * from todo"
then FINISH connection should see results from both selects?

thanks for explanation

**Comment by KurtStam** [comment]
Still open issues on the UI are 
- filter actions by to/from: https://github.com/syndesisio/syndesis/issues/253
- error handling: https://github.com/syndesisio/syndesis/issues/718
- widget to input time for the period field: https://github.com/syndesisio/syndesis/issues/717

**Comment by KurtStam** [comment]
@kcbabo @Stefan365. Until we store the history of ALL output (TP4), we should keep the last output as the input for the next step. If there was no output then we keep the input (data + shape) as output for the next Step. Going to make sure it works this way.
