### ISSUE TITLE
Clicking on link in list item takes you to list item details

### ISSUE THREAD

**Issue by mcoker** [syndesisio/syndesis#4071]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Clicking a link in the main area of a pfng-list row triggers the onclick event for the row. For example, clicking a link in a list row of the integration list page or api client connector list page will take you to the integration or api client connector detail page.

## Expected behavior
The click event on the link shouldn't bubble up and trigger the onclick event on the row.

## Screenshots
<img width="918" alt="screen shot 2018-11-09 at 5 44 36 pm" src="https://user-images.githubusercontent.com/35148959/48293957-29ce5880-e447-11e8-899c-5f07b900793c.png">
<img width="832" alt="screen shot 2018-11-09 at 5 42 45 pm" src="https://user-images.githubusercontent.com/35148959/48293958-29ce5880-e447-11e8-9f29-0633b538af59.png">

## Tasks involved / Steps to Reproduce

1. Start an integration from the integration list page.
2. While it's assembling/building, click the "view logs" link.
3. Go back to the Syndesis window and you'll notice you're on the details page.

#### another way
1. Create/edit an api client connector.
2. Put a hyperlink in the description (ie, `<a href="#">foo</a>`)
3. Go back to the api client connector list page.
4. Click the hyperlink in the list row.
5. Notice that the browser takes you to the api client connector details page before navigating to the link. 

cc @syndesisio/uxd @gashcrumb

**Comment by mcoker** [comment]
@gashcrumb is this something you or someone on the UI team could work on?

**Comment by gashcrumb** [comment]
Yeah, so the problem is that the components *inside* the list component need to carefully ensure that the their own click event doesn't bubble up.  We've had to deal with this already in the app, see here:

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/connections/list/list.component.html#L47

And here:

https://github.com/syndesisio/syndesis/blob/master/app/ui/src/app/connections/list/list.component.html#L70

Which I think is really the only good solution, it's kinda error prone to check in the parent component what inner element is the click target and if it should handle the event or not.

**Comment by mcoker** [comment]
Ah, gotcha. Should be straight forward to stop propagation on the "view logs" link click event, but what about dynamic links in the api client connector description? Seems like we should strip HTML from the description snippet we display in the list view?

**Comment by gashcrumb** [comment]
We could probably actually just add a click handler to the containing element that prevents propagation if the description is there.

I think generally the problem is we're asking list items to normally be like a big button, except in some cases we don't want it to be a big button, this kinda feels like a general usability problem with the patternly list and using it's on select for naviation, it feels a bit overloaded.

Maybe it'd be better to avoid that pattern and instead make the name a link (like obviously a link) or explicitly use a button.

**Comment by mcoker** [comment]
@dongniwang what do you think about this? When you click on a link in a PF list row, the click will register on the link _and_ the row, triggering whatever happens when you click on the row, too. Do you think this enough of an edge case would be OK to address this in the react POC, or want to try and get a fix in for what we have now?

**Comment by amysueg** [comment]
@mcoker What level of effort is required to separate that link's click from the underlying row's click behavior? If it's a large level of effort, then I'd say it's probably ok to wait and address this in the React POC. If we get a lot of negative user feedback on this unexpected behavior, then it may be necessary to address it sooner.

**Comment by mcoker** [comment]
After discussing today, we should

* stop propagation of the "view logs" link in the integration list row.
* add support for links in the description of an integration.
* I'm not sure how to edit an extension .jar file, so I can't currently test this, but we should have support for a link in the description of an extension, too.
* stop propagation on the click event of the entire description element in the list view for API connectors, extensions, and integrations.

@gashcrumb what do you think about these changes?

**Comment by mcoker** [comment]
Assuming you would add a link in the description like this, then it just includes text and doesn't render it as HTML.

```
<description>a foo descrption <![CDATA[<a href="#">foo</a>]]> </description>
```

What's the level of effort for this change?

**Comment by mcoker** [comment]
ping @gashcrumb ^^ I'm not sure what this would involve, but Amy's trying to gauge the level of effort for whether we should do this work now or include it in the React app. What do you think?

**Comment by gashcrumb** [comment]
I don't view this as too high priority tbh, so yeah maybe we defer this.

**Comment by riccardo-forina** [comment]
This is not relevant anymore on the React UI. Can we close it?

**Comment by dongniwang** [comment]
Related to https://github.com/syndesisio/syndesis/issues/5525. But we can close this one I think.
