### ISSUE TITLE
RFI - FHIR Connector seems to only be producer

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4186]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Documentation issue or request
</code></pre>

## Description
While looking into the odata connector, I have been using the other connectors as reference points. So, in my syndesis UI, I created a FHIR connector and happily it has a default value for the server to make life easy! However, I then get confused ...

1. Create new FHIR Connector
![new-fhir-connector](https://user-images.githubusercontent.com/1634180/49228026-6526cc00-f3e2-11e8-9f43-033f7c429216.png)

2. Creating a new integration, I cannot use the FHIR Connector for a start connection:
![new-integration-no-fhir-connector](https://user-images.githubusercontent.com/1634180/49228061-766fd880-f3e2-11e8-9e59-ad000f93768f.png)

3. However, I can use the FHIR Connector as a finish connection:
![finish-connection-has-fhir-connector](https://user-images.githubusercontent.com/1634180/49228093-8ab3d580-f3e2-11e8-847e-62f9333009ac.png)

4. This is where I get confused, the FHIR Connector has a read operation and therefore it would appear that my twitter connection (the one I selected for the start connection) could be mapped to this read operation (?). This is confirmed when looking at the [code](https://github.com/syndesisio/syndesis/blob/master/app/connector/fhir/src/main/resources/META-INF/syndesis/connector/fhir.json#L62), the fhir.json show defines the read operation as a 'To' pattern:
![fhir-connector-has-read-op](https://user-images.githubusercontent.com/1634180/49228128-96070100-f3e2-11e8-839c-ea5e78c67146.png)

Having only got into the intricacies of connectors in the last few days, I am wondering if this is correct please?
(Please accept my apologies if I have failed to understand properly how the FHIR connector works)

@rkorytkowski @lburgazzoli @heiko-braun @christophd @lgarciaaco

**Comment by christophd** [comment]
@phantomjinx I thought through it once more after our conversation yesterday. The current read operation in FHIR connector is not able to listen for changes on the FHIR resource and therefore does not apply for being used as a start connection.

The read is executed as a once in a lifetime operation. If used as a start connection your integration would only be processed a single time. Start connections are supposed to react on resource changes, API invocations or polling events in order to trigger the integration processing multiple times.

Others please correct me if I am totally wrong here.

**Comment by rkorytkowski** [comment]
@christophd, you are correct.

**Comment by phantomjinx** [comment]
@rkorytkowski @christophd 

Thanks guys! Explain a lot and clears up my confusion.

Cheers.
