### ISSUE TITLE
Support Page to also collect integration source code and binary artifacts

### ISSUE THREAD

**Issue by tmielke** [syndesisio/syndesis#4204]
See also **https://issues.jboss.org/browse/ENTESB-11574**

## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Please let the Syndesis Help -> Support Page also collect and zip up
- the source code of the integration (i.e. zip up /tmp/src/src on the pod that runs the integration)
- the binary application files (i.e. zip up /deployments folder on the pod that runs the integration)

for every integration selected.
This will greatly help in analysing customer problems.
The Support Page currently captures neither of the two above and therefore does not seem to collect any information about the routes being deployed.

**Comment by tmielke** [comment]
This is in relation to https://github.com/syndesisio/syndesis-project/issues/135

**Comment by zregvart** [comment]
The problem is that we need to access the Maven project we provide to the S2I binary build and it's only accessible (currently) in a running integration POD or in the build image.
Accessing it from a running integration pod could be difficult in cases when the user needs support, i.e. the integration could be crashing and accessing it could be a race to access the files while the integration is still running.
We could either:
 - access the files from the build image (for example spin up a build with custom logic to copy the files)
 - run the integration pod in debug mode (if we can do that without requiring additional permissions)

**Comment by tmielke** [comment]
Any chance to reopen this one?

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11574**
