### ISSUE TITLE
 API Provider: Collection Support 

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4257]

**Comment by christophd** [comment]
There are lots of different issues and discussions around this epic so I want to collect/summarize what we are going to implement:

* https://github.com/syndesisio/syndesis/issues/4346 Migrate integrations
  * Auto translate implicit split that is used by connectors (sql, asw-s3, servicenow) to new split/aggregate steps
  * Either do this via DB migration script or auto translate when providing old integrations from DB to UI
  * User might be provided with a warning/info that the integration has been migrated/auto translated
* https://github.com/syndesisio/syndesis/issues/3896 Add collection support to connectors
  * Connectors such as SQL, Twitter will return collections only
  * User can choose to add new split/aggregate steps in order to operate on individual items in these collections or work with the collection itself
  * Old integrations will be provided with auto split/aggregate steps
  * Connectors continue to describe the type of elements of the collection, not the collection itself
* https://github.com/syndesisio/syndesis/issues/4337 Data shape definition for collections
  * Add flag to data shape definitions that mark data shape to be a collection
  * Data mapper is able to provide topmost collection support for these kind of data shapes
* https://github.com/syndesisio/syndesis/issues/4349 Implement UX
  * Introduce new split/aggregate steps in UI
  * New steps do not hold any properties (for now - might change in future with split expression, aggregation strategy)
  * New split and aggregate steps are added separately to an integration
  * When split is added integration shows an info that aggregation might be needed, too
  * Aggregate step is only available in case a split step is present
  * Aggregate can only be added after a split step
  * Backend automatically provides new split aggregate steps for old integrations that have been using implicit split functionality
  * UI will display a info that the integration has been automatically migrated/translated from implicit split to new split/aggregate
  * Users can add aggregate step as finishing step of an integration
  * Users can add aggregate step after an existing finishing step
* https://github.com/syndesisio/syndesis/issues/4355 Out message capturing adjustments
  * Data mappers inside a split/aggregate see all captured out messages as possible source
  * Data mappers placed after an aggregate step do not see the inside messages within split/aggregate but only the overall aggregate out message and all out messages before the split

**Comment by asmigala** [comment]
Verified with CR3
