### ISSUE TITLE
API Provider: Implement UXD changes

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4260]
Changes described in https://github.com/syndesisio/syndesis/issues/4120

**Comment by gashcrumb** [comment]
@paoloantinori @riccardo-forina Added some high-level items after going through the design, but going to do a second pass in a few to catch things I've missed.

**Comment by gashcrumb** [comment]
@riccardo-forina can't decide, should we consider adding storybook support to the old app in support of some of these?

**Comment by riccardo-forina** [comment]
We could try following the [guide](https://storybook.js.org/basics/guide-angular/) and see it works right out of the box. In that case, we could use it for the new UI bits, but I'm not sure it's worth writing stories also for the existing UI components...

**Comment by gashcrumb** [comment]
Yep, I did a little investigation yesterday afternoon and it does seem to run alright.

I made the mistake then of trying the integration status component, thinking it's pretty simple, but turns out it isn't a simple UI component since it pulls in the detailed status component.  And that's my only concern, it's great for pure UI widgets but the angular codebase has none of that.  I'm not sure really how much *new* UI bits we'll create for this, in many ways the designs are all elements of what's there but moved around and styled a little differently.

**Comment by riccardo-forina** [comment]
The bulk of the work has been done in #4467, I think we can close this.

**Comment by heiko-braun** [comment]
Thanks @riccardo-forina , I'll move it to `Done` which signals QE start doing the verification 

//cc @syndesisio/qe

**Comment by mastepan** [comment]
Closing this epic. Contained issues will be/have been verified.
