### ISSUE TITLE
SPIKE: investigate support for CRD in kubernetes-client

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#4269]
To leverage camel-k builder we need to be able to create/delete/update camel-k's CRs

**Comment by valdar** [comment]
**DISCLAIMER: the code produced as a POC is just a quick way to show that handling of CRD and CD is possible using the k8s-client version currently used in syndesis. It works only if you are connected to a running ocp/k8s cluster with an admin user and are using project/namespace named "myproject".**

As [this quick POC](https://github.com/valdar/syndesis/blob/github_issue_4269_POC/app/server/runtime/src/test/java/io/syndesis/server/runtime/CdrITCase.java) shows, it is possible to handle CRD and CR with the current version of k8s-client (i.e. k8s-client 3.1.4.fuse-710001). 
Since kamel binary itself perform creation of a CRD starting from a yaml file this is what I have recreated [here](https://github.com/valdar/syndesis/blob/github_issue_4269_POC/app/server/runtime/src/test/java/io/syndesis/server/runtime/CdrITCase.java#L57-L66), most probably this task will still be performed by camel-k operator or the syndesis install operator.
Coming to the more interesting part of managing CR, that is done [here](https://github.com/valdar/syndesis/blob/github_issue_4269_POC/app/server/runtime/src/test/java/io/syndesis/server/runtime/CdrITCase.java#L84-L116), the tedious part is the need to map the CR structure as java objects needed by the k8s-client api:

- [Integration](https://github.com/valdar/syndesis/blob/github_issue_4269_POC/app/server/runtime/src/test/java/io/syndesis/server/runtime/Integration.java)
- [IntegrationList](https://github.com/valdar/syndesis/blob/github_issue_4269_POC/app/server/runtime/src/test/java/io/syndesis/server/runtime/IntegrationList.java)
- [IntegrationSpec](https://github.com/valdar/syndesis/blob/github_issue_4269_POC/app/server/runtime/src/test/java/io/syndesis/server/runtime/IntegrationSpec.java)
  - [SourceSpec](https://github.com/valdar/syndesis/blob/github_issue_4269_POC/app/server/runtime/src/test/java/io/syndesis/server/runtime/SourceSpec.java)
- [DoneableIntegration](https://github.com/valdar/syndesis/blob/github_issue_4269_POC/app/server/runtime/src/test/java/io/syndesis/server/runtime/DoneableIntegration.java)

these might be generated on syndesis or camel-k part or kept in sync by hand.

**Comment by lburgazzoli** [comment]
Looks very good so I think we can remove SPIKE and move among the done issues if @rhuss has no remarks about permissions ?
