### ISSUE TITLE
[Upgrade] Scripts in "minorVersion" folder are not handled during upgrade to daily build

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4413]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This is related to community only, during productized build the productization handles this.

Currently, the upgrade doesn't work well for the daily version when upgrading between major versions with added functionality - the migration scripts are expected to be present in the directory with the exact name of the version we are upgrading to.

For example, we have this file https://github.com/syndesisio/syndesis/blob/master/tools/upgrade/migration/resource/1.6/01_db_metrics_config_map.sh in the `1.6` folder, that is not picked up automatically during an upgrade to `1.6.1-20190131`.

First thing that comes to my mind was to move the content of `1.6` folder to `current_daily_version` during the build of upgrade image if it is possible

@rhuss wdyt?

**Comment by rhuss** [comment]
@avano I think it would be even better if the script could be written in an idempotent way that it could be placed into `migration/resource/any` directory. These scripts are applied for every update.

I'm not sure that a current_dail_version directory would solve the issue because it could be still that the script gets applied several times (e.g. when updating from daily version to the next daily version to the next daily version). 

Having it running always makes sense IMO. For DB updates we might also think about switching to a real DB migration toolkit like flyway.

**Comment by avano** [comment]
@rhuss so does it make sense for the upgrade scripts to check the `upgrade_version` folder anyway? Why not make all scripts idempotent and forget about `upgrade_version` and `all` folders and just apply all scripts found in `migration/resource`, or something like that?

**Comment by rhuss** [comment]
I agree that this is definitely better to have everything in an idempotent way but might be that its not feasible every time. Having an option for a specific update step which is not idempotent to use the jump from one version to the next is not a bad thing, I think.

Of course, we could rearrange the scripts, to different directory names.

**Comment by avano** [comment]
> Having an option for a specific update step which is not idempotent to use the jump from one version to the next is not a bad thing, I think.
> 

You are right. I'm just thinking out loud to help you find a solution that will work for both upstream & prod builds :neutral_face:

**Comment by rhuss** [comment]
I could add a feature that several directory levels are tried. E.g.

* 1.6.1-20190228
* 1.6.1
* 1.6
* 1

and will apply all scripts found in these directories. But tbh, I think if we allow for such stepwise updates, we should make it more sophisticated. I.e. we should record also intermediate steps. Because e.g. when one goes from 1.6.1-20190228 to 1.6.1-20190301 we don't want to have the same script applied.

Maybe it would make sense to remember the update steps that already have been applied, e.g. either in the custom resource or kind of configmap. 

However, for now, I think it's better to make scripts idempotent. Hence I'm going to move the metrics db config to be an idempotent script for now.

**Comment by avano** [comment]
@rhuss so at the moment all new scripts should be idempotent and placed in the `any` directory, is that correct?

What will we do with this issue then? Do you want to keep it open for further enhancements (based on your last comment) or should I close it?

**Comment by rhuss** [comment]
@avano yes, we should put everything into `any` for now, especially we have not sorted out how to work with the same update pod on Syndesis (1.6.x versioning scheme) and Fuse Online (1.3.x or so scheme).

I'm going to close this issue for now, but maybe we should create a followup issue for future versions ? (like documenting how todo updates, or researching how this can be done better ?)

**Comment by avano** [comment]
@rhuss thanks

A followup issue would be nice, can you create it, please?
