### ISSUE TITLE
Idiot's guide to the GMail Connector

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4431]
As a typical user, who fails to read the syndesis manual accurately, I want to create a GMail Connector. Having skipped through the manual, I successfully register Syndesis in Google's GMail API settings page. I return to Syndesis and begin creating a GMail connector.

At this point, having failed to read the manual properly, I go to Connections > GMail and begin to copy n paste the settings from the Google page. However, I am confronted by the 2 properties 'Access Token' and 'Refresh Token', which are no where mentioned in either the Google settings page or the syndesis manual. After returning to the manual and starting over from scratch, it once again dawns on me I have to add the GMail settings into syndesis's settings page. Of course, once done everything it straight-forward and working correctly.

Therefore, is it possible to:
* put a message on the GMail Connection page to tell the user to enter the settings in Settings > GMail?
* completely hide the Access Token and Refresh Token as they are 'programmatic' inputs and not obviously available for the user to add information to?

**Comment by oscerd** [comment]
You can use accessToken and Refresh token without any troubles. That couple will start fail in 60 minutes. IMHO it doesn't make sense to hide the fiekds

**Comment by phantomjinx** [comment]
@oscerd 
Fair enough. However, where would one get the tokens from? Without any documentation to that effect, the typical user is left flailing. Therefore, maybe an extra paragraph in the documentation and an extra label/tooltip in the UI would dot the i's / cross the t's.

**Comment by heiko-braun** [comment]
@TovaCohen Is this soemthing we can sneak into 7.3?

**Comment by TovaCohen** [comment]
@phantomjinx @oscerd @heiko-braun 

I could but IMHO doing so is not in the best interests of the user.

The 7.2 doc for creating a Gmail connection discourages the user from entering values on the Gmail connection page when Syndesis is not registered as a Gmail client. This is what we say:

> If Connect Gmail does not appear, then your Fuse Online environment is not registered as a Gmail client application. See Register with Gmail. When you try to create a Gmail connection and your Fuse Online environment is not registered as a Gmail client application, then Fuse Online displays multiple fields that prompt for authorization information. While you can create a Gmail connection by entering values in these fields, you should register with Gmail first, and then create a Gmail connection after registration is in place.

Do you want to remove that recommendation? It doesn't make sense to me to recommend doing it in a certain way, and then give details for doing it in another way.
As Andrea says, if the user inserts authorization details on the Gmail connection page, the connection will fail after 60 minutes. Do we want to point this out in the doc to explain why we do not recommend doing it this way?

While I understand that no one wants to read doc, I don't think we should be helping the user enter values on the Gmail connection page. 

Instead, on the Gmail connection page, only when it displays the 6 authorization fields, I would add this:

> While you can create a Gmail connection by entering values in these fields, it is not recommended. Instead, register with Gmail first.

And make "register with Gmail first" a link to:

https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/connecting_fuse_online_to_applications_and_services/connecting-to-gmail_connectors#register-with-gmail_gmail

In that procedure, the last steps tell the user to copy the Google client ID and the client secret into the Syndesis Settings page. To accomodate the user who starts to read but doesn't finish, I'll add the following as a prerequisite for creating a Gmail connection:

> In the Syndesis Settings page, the Gmail entry contains values for the Google client ID and Google client secret. 

and I can provide a link to the doc that tells the user how to do that. 

Paul, I'm not disregarding your experience. You registered Syndesis as a Google client. You just didn't copy the Google client ID and Google client secret into the Syndesis Settings page. Do you all think that this is a likely situation for someone who is new to Syndesis? If yes, then the doc could provide a separate procedure for copying the values into the Settings page. I hesitate to do that because the registration procedure in Google provides the client ID and the client secret and it seems incomplete to not tell the user what to do with those values. 

What do you all think now?

As a 7.4 UI enhancement, how about this:

As background, the procedure for registering Syndesis as a client application is the same for Gmail, Google Calendar, and Google Sheets. The user only has to do it once. The user gets credentials that can be used for each of these Google apps. Yet we make the user copy each credential into three fields in order to access the three apps. 

We should change the Syndesis Settings page to remove the three entries for Gmail. Google Calendar, and Google Sheets. 
Replace them with one entry for Google Applications. 
In that entry, under the Client ID and Client Secret fields, add a checkbox for each Google application. The user can select the appropriate box instead of needing to copy the client ID and client secret to the entry for each Google application. Internally, Syndesis does the copy/paste instead of the user. It would look something like this:

Google Applications

&nbsp;&nbsp;&nbsp; Client ID      _________________________

&nbsp;&nbsp;&nbsp; Client Secret  _________________________

&nbsp;&nbsp;&nbsp;Register access to:  [] Gmail    [] Google Calendar   [] Google Sheets

If you like that idea, let me know and I'll create an enhancement request.

**Comment by gashcrumb** [comment]
> We should change the Syndesis Settings page to remove the three entries
for Gmail.

I agree, we really should only have a Google entry on that page.

**Comment by zregvart** [comment]
Having one entry in OAuth settings can be a bit difficult. When we authorize Syndesis to access a Google service we need to provide a proper OAuth scope. For each connector this scope is different (AFAIK).

_Brainstorming:_ So we can either ask for all scopes (security issue, overwhelming the user) and use a single connection or implement logic to attempt to ask for additional OAuth scopes when creating connections for other connectors.

In general I think we should discourage as much as we can entering OAuth properties when creating a connection and encourage entering OAuth settings and creating the connection via single click.

**Comment by TovaCohen** [comment]
In the user doc for creating a Gmail connection, creating a Google Calendar connection, and for creating a Google Sheets connection, the prerequisites for doing that are now as follows, with the appropriate name of the Google application where you see "Gmail": 

> Prerequisites
> 
> - You registered Syndesis as a Google client application and enabled the Gmail API.
> - The Syndesis **Settings** page entry for Gmail has values for the client ID and client secret, which you obtained by registering Syndesis as a Google client application.

Let me know if you want me to do anything else.

**Comment by zregvart** [comment]
I think this issue has the same root cause as #5582, and the conclusion reached there is that for OAuth based connectors we should stop supporting manual entry of OAuth tokens. In this case the user needs to go to settings and ender the client id and secret and then create a connection using the OAuth flow (single button).
