### ISSUE TITLE
Summary page view and clear messages

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4461]
## This is a...

<pre><code>
[x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

On the summary page I see the number of messages.  I want to be able to link to the message to examine the content and clear or delete these messages.

## Screenshot

![image](https://user-images.githubusercontent.com/674767/52372153-66e5bf00-2a25-11e9-9d75-b9c4af602024.png)

**Comment by seanforyou23** [comment]
I wanted to share an idea, not sure how relevant or practical it is, but maybe it will help improve the experience here.

Since the total messages card reflects what's happened at the holistic system level, and not individual integrations, maybe it would be good to split this card into two. One that reflects the total messages from the beginning of time, which is never cleared, and another that reflects total messages for a given integration(s) which could be cleared on demand or automatically after they are "deleted" by the user.

Chew the meat and spit the bones here, not pushing hard one way or the other. Just wondering if it would be beneficial for users to be able to see both POV of this data. Thoughts?
