### ISSUE TITLE
[Split] Weird workflow when I want to end the integration with "aggregate"

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4567]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
This is a follow-up for https://github.com/syndesisio/syndesis/issues/3433 , that doesn't get much attention it seems (and IMO it should).

I want to create an integration on current master: `SQL1 -> Split -> SQL2 -> Aggregate`

How I go through the process:
- Choose the start of the integration: `SQL1`
- Choose the end of the integration:   I can't see `aggregate`, I assume it is because I don't have the `split` anywhere in the integration, so I choose `SQL2`
- I add a split in between
- I **delete** previous ending step `SQL2` in order to substitute the ending for `aggregate`
- I **re-add** SQL2 before the aggregate step

EDIT: just a note, I'm not sure if there must be `Aggregate` at the end of the integration, but in my understanding `Split` and `Aggregate` are just `forEach` and `endForEach`?

**Comment by gashcrumb** [comment]
@gaughan @dongniwang FYI

**Comment by gaughan** [comment]
@avano I'm not sure I follow, step 2 seems correct to me, at that point you were looking to add a split, was that not available?

**Comment by gashcrumb** [comment]
Well, no he was looking for what would be the end step in his integration ultimately which is aggregate.  But we make you pick the finish step first, and we don't allow aggregate without split (apparently) so you have this odd sequence of things you have to do.  Ultimately it's because we make you pick the end of your integration up front.  

This issue and the other linked issue argue against choosing the end of the integration up front.

If we want to explore it we can certainly test it out, it's mainly removing code as far as I can recall, just lemme know.

**Comment by avano** [comment]
thanks, Stan, you were quicker :-)

**Comment by gaughan** [comment]
So I think we stick a pin in the "choosing an end connector" issue, I agree it needs addressing but not for this release. The issue it seems in this workflow is that aggregate should not be a valid end connector. wdyt?

**Comment by gashcrumb** [comment]
Yeah, aggregate by itself at the end doesn't get you much.  It still needs a thing after it, otherwise it doesn't have an input data shape to derive it's own data shape from.

In the API provider case it works because there's always an "end connection", the API provider response connection.

Also as @christophd mentioned in the demo call, we're going to find a lot of edge cases with data shapes across the flow definition I suspect.

I think though that none of this affects the original decision, which was that we ensure that the user has created something brings in data, something that spits out data and then can have the chance to go in and muck with the data in the middle :-)

**Comment by dongniwang** [comment]
Hey @gaughan @christophd, can we have a conversation about this at some point? 

cc @gashcrumb

**Comment by gaughan** [comment]
sure, i'm back on Monday if that works?

**Comment by christophd** [comment]
Technically speaking we do not need the aggregate at the end of an integration. Makes no difference to the integration execution neither to the outcome of the integration.

**Comment by avano** [comment]
@christophd then probably two things should happen:
- don't show the "hint" that the split step is not closed - #4549
- don't add the aggregate step as the last one when doing upgrade of older integration - #4516 , #4455

These two things are giving me the impression that I should always have the aggregate step in the integration

**Comment by christophd** [comment]
@avano the aggregate as last step after integration migration has been removed

@dongniwang @gaughan do we need some more conversation about the other aspects?

**Comment by gaughan** [comment]
Yea, a review would be great

**Comment by avano** [comment]
@christophd I can confirm that the aggregate is not added at the end of the integration anymore, but leaving this open for the discussion

**Comment by dongniwang** [comment]
@heiko-braun I just removed the sprint milestone on this issue but keeping it open for 7.4.
