### ISSUE TITLE
Syndesis-db-metrics doesn't work when syndesis-db is down

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4652]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I wanted to try [FuseOnlineDatabaseInstanceDown]( https://github.com/jamesnetherton/syndesis/blob/ec10dc4ec4ceb5bf90dd84e07fc7fd6c3ab9ddfe/doc/managing_environments/topics/alerting_sop.adoc#fuseonlinedatabaseinstancedown) alert from https://github.com/syndesisio/syndesis/issues/4151
For Grafana, Prometheus and AlertManager, I am using https://github.com/integr8ly/application-monitoring-operator. 

When I scale syndesis-db to 0 due to simulate database down state for alerting, the OpenShift set syndesis-db-metrics as Unhealthy and pod as Not Ready. This causes that syndeis-db-metrics is set as DOWN in the Prometheus Targets.

**Comment by heiko-braun** [comment]
@mkralik3 Can you expand on what you expected to see?

**Comment by heiko-braun** [comment]
@jamesnetherton Can you work with @mkralik3 on this one?

**Comment by jamesnetherton** [comment]
@heiko-braun Yes, we spoke about it earlier today and I'm investigating.

**Comment by heiko-braun** [comment]
Thanks @jamesnetherton !

**Comment by jamesnetherton** [comment]
There's a couple of issues here.

1. The liveness / readiness probes target the `/metrics` endpoint. This is probably not what we want given that the metrics endpoint will (or should) return an HTTP 500 if any errors occurred collecting metrics. It also generates unnecessary load on Syndeis DB. Prometheus scrape requests should be the only thing hitting the `/metrics` endpoint. We can fix this by using `/` as the endpoint for liveness & rediness probes or maybe use `tcpSocket` instead of HTTP.

2. There's a bug which results in the exporter crashing some time after the Postgres instance has gone down. See https://github.com/wrouesnel/postgres_exporter/issues/245.

**Comment by heiko-braun** [comment]
> 1. We can fix this by using `/` as the endpoint for liveness & rediness probes or maybe use `tcpSocket` instead of HTTP.

Sounds good.  @lgarciaaco What do you think?

**Comment by lgarciaaco** [comment]
Yep absolutely, a tcp check should be enough for this case

**Comment by jamesnetherton** [comment]
I think the issue with the Postgres exporter crashing is due to some kind of DNS resolution issue. Which may  explain the long pause when hitting the /mertrics endpoint after the syndesis-db pod is scaled back to 0.

If I test locally with my default resolve.conf, I can replicate the issue consistently. If I tweak my resolver configuration to point at Google's DNS servers, then the problem goes away and the exporter gracefully handles the target Postgres instance being down.

We should be able to solve this with #4674. If we move the exporter container into the syndesis-db pod, then we can avoid DNS lookups entirely and connect to the Postgres instance using localhost.
