### ISSUE TITLE
"2nd step and the steps after" after Split step doesn't perform

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#4728]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description.
Let's have an integration:
**DB select -> Split -> DB insert1** -> DB insert2 -> ... -> final step

Only the **bold** steps perform (the first step after Split step is the last one that happens)

[2 steps after split-export.zip](https://github.com/syndesisio/syndesis/files/2925854/2.steps.after.split-export.zip)

1. suppose you have exactly any 3 records in CONTACT table 
2. run the integration
3. Look at TODO table. If you can't see every 10 seconds new records as follows, it's wrong (if I get how Split step works):

**task column**
first task
first task
first task
final task
final task
final task

**Comment by mastepan** [comment]
@christophd what's your opinion?

**Comment by christophd** [comment]
@mastepan I will try and have a look

**Comment by christophd** [comment]
I think this is not related to split functionality but to SQL connector in general. 

The SQL connector tries to read query parameter information from the current exchange payload in order to set those parameters in the query. The connector assumes that the body (when set) is a JSON string defining a proper query parameter information.

The 1st SQL insert is provided with such a JSON String coming from the initial start connection. The 2nd SQL insert is failing because no such valid JSON parameter information is set as body. Instead the body contains the empty results of the 1st SQL insert.

I suppose 

1) SQL connector should only try to read query parameter information from exchange body when the actual query to execute uses some parameters
2) SQL connector should be able to handle exchange bodies other than JSON

@zregvart WDYT!?

**Comment by zregvart** [comment]
Kinda weird to have two DB inserts in a row, the second one will get the output of the previous one as input. I think mapper and data buckets (referencing data from previous steps) should be used here.

**Comment by mastepan** [comment]
@christophd, @zregvart 

There is different behavior:
- If I don't use Split, the result of the first SELECT is only first row and all the following steps perform (once for each integration run)
- If I use Split 2nd and further steps after Split don't perform - as described previously.

**Comment by christophd** [comment]
@zregvart DB inserts here use static queries without any parameter. Therefore there is no mapper option available for the user between those two SQL steps. I think it is a rare corner case but yet we should handle in SQL connector

**Comment by christophd** [comment]
@mastepan weird I get the same error when removing the split

**Comment by zregvart** [comment]
So if I understand correctly, the SQL connector is looking for parameters even if it doesn't require any to function? Yeah that should be handled in the SQL connector.

**Comment by mastepan** [comment]
> @mastepan weird I get the same error when removing the split
Hm... I get the error now too... weird...

**Comment by mastepan** [comment]
> > @mastepan weird I get the same error when removing the split
> 
> Hm... I get the error now too... weird...

well, I cannot reproduce this again. But it surely happened. I can't wind the "right" configuration

**Comment by mastepan** [comment]
Thanks for the quick fix @christophd 
I've verified this on 1.6.1-20190305
