### ISSUE TITLE
FuseOnlineDatabaseInstanceDown alert is not activated when Syndesis-db is down

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4762]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I have those alerts (https://github.com/syndesisio/syndesis/issues/4151 , https://github.com/syndesisio/syndesis/issues/4499):
![image](https://user-images.githubusercontent.com/16251792/53820191-8fe96900-3f6b-11e9-9060-89928be2f6cc.png)

I scale syndesis-db to 0 due to simulate database down state for alerting. After some time, when the server cannot connect to db, the latency of RestAPI is higher(10s)
![image](https://user-images.githubusercontent.com/16251792/53820296-c8894280-3f6b-11e9-9d9c-69f6c7f7f941.png)
Because of that, The FuseOnlineRestApiHighEndpointLatency and FuseOnlineRestApiHighEndpointErrorRate alerts are in the pending state
![image](https://user-images.githubusercontent.com/16251792/53820390-f66e8700-3f6b-11e9-8233-f5531c052dd5.png)
and after some times, they are fired
![image](https://user-images.githubusercontent.com/16251792/53820464-1aca6380-3f6c-11e9-9355-99ae92776bd1.png)

However, the [FuseOnlineDatabaseInstanceDown]( https://github.com/jamesnetherton/syndesis/blob/ec10dc4ec4ceb5bf90dd84e07fc7fd6c3ab9ddfe/doc/managing_environments/topics/alerting_sop.adoc#fuseonlinedatabaseinstancedown) alert is still inactive. In my POV, when syndesis-db pod is scaled down to 0, this alert should fired too.

**Comment by jamesnetherton** [comment]
For 7.3 I think we should maybe remove the `FuseOnlineDatabaseInstanceDown` rule and revisit in 7.4.

I realised we have a general issue configuring rules that monitor for a job's availability using `up`, and in this case `pg_up`, for environments where Fuse Online could be installed in multiple namespaces (E.g integr8ly).

If a pod is scaled to 0, then its endpoint is removed from the service that the Prometheus ServiceMonitor is trying to scrape. The typical query to use for alerting in this case would be something like:

`absent(up{job="syndesis-db"})`. 

That works fine where only a single instance instance of Fuse Online is running in one namespace. If multiple namespaces come into the picture the query would need to look like:

`absent(up{job="syndesis-db" namespace="foo"})`. 

The problem is, how do you determine which namespace to query on? I don't see any way of doing it dynamically (without hacks like [this](https://serverfault.com/a/951539)). Maybe OpenShift templates and variables could be used to achieve this.

**Comment by heiko-braun** [comment]
@jamesnetherton Is it the only rule that is impacted by multiple namespaces?

**Comment by jamesnetherton** [comment]
@heiko-braun Yes it's the only one affected. There are only two other rules at present and they are unaffected.

**Comment by jamesnetherton** [comment]
Although, even for a single namespace scenario I think the `FuseOnlineDatabaseInstanceDown` rule in it's current state is broken because the Postgres exporter is now moved to the syndesis-db pod (see #4674).

To support a single namespace the rule would need changing to something like `absent(up{job="syndesis-db"})`.

**Comment by heiko-braun** [comment]
Does it mean that `absent(up{job="syndesis-db"})` triggers on changes in any namespace?

**Comment by jamesnetherton** [comment]
@heiko-braun  It'll only work where the cluster has 1 Fuse Online installation in a single namespace. Or, if there are multiple Fuse Online installs in separate namespaces and syndesis-db happens to be down in all of them (an unlikely scenario).

Like I hinted at in my previous comment, to support multiple namespaces the query would need to match on the namespace label like:

```
absent(up{job="syndesis-db", namespace="foo"})
```

But, as I pointed out there are some challenges to implementing that. Hence, I advocate removing the alert rule until we can solve that problem. 

I think the other rules we have for HTTP latency and HTTP error responses are sufficient for now. If syndesis-db is down, then one (or both) of those alerts will fire and it'll be a task for whoever is investigating to check the DB pod. I could maybe add a note into the SOP to that effect.

**Comment by heiko-braun** [comment]
@jamesnetherton I would leave it in, knowing that there is a limitation. At least it works for one namespace,  and if doesn't have any side effects in case multiple namespaces (other then it will not trigger), I see an issue with it.

**Comment by mkralik3** [comment]
Verified.
When the syndesis-db pod is scaled down to 0, the FuseOnlinePostgresExporterDown alert is fired.
When the postgres container is doesn't response, (for instance when all connections were canceled on the databases in the container and no new connection are permitted), the FuseOnlineDatabaseInstanceDown alert is fired.
