### ISSUE TITLE
Fuse Infra deployed in a separate names space to the integrations it creates

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#4794]
See also **https://issues.jboss.org/browse/ENTESB-11507**

## This is a...

<pre><code>
[ x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
As a Fuse administrator, I would like to have the ability to separate Fuse infrastructure from the integrations I deploy in separate namespace/s
The ability to deploy toi different namespaces would allow be to manage by integrations across dev, test, production namespace or by different business units in my organization (Accounts, HR etc)

Minimum DoD:
- I have the option to deploy integrations I create in Fuse Online to a single separate namespace that is automatically created for me.
- I can deploy to multiple namespaces.
- I can see what version is published in each namespace.

**Comment by johnfriz** [comment]
+1 Really need this.

**Comment by theodor2311** [comment]
+1 This feature is important for deploying the Fuse Online as a shared service that can be shared by multiple project teams within the same organization. Besides, the shared Fuse Online service should also support multi-tenancy with integrated OpenShift RBAC. So that each project team can only manage the assets in Fuse Online in their own project only.

**Comment by radarlui** [comment]
+1 This feature is important for deploying the Fuse Online as a shared service that can be shared by multiple project teams within the same organization. Besides, the shared Fuse Online service should also support multi-tenancy with integrated OpenShift RBAC. So that each project team can only manage the assets in Fuse Online in their own project only.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11507**
