### ISSUE TITLE
Should OData remove its split option?

### ISSUE THREAD

**Issue by phantomjinx** [syndesisio/syndesis#4833]
Since the introduction of the split step, the usefulness of the split option internal to the odata connector has come into question. Essentially, the split step is doing the same job in that the results of the odata query are split into separate messages and presented individually to the rest of the route.
Up until now, the use of either option has presented no issues. However, a flaw has been identified in the odata split option, namely that even though the result is split the json is still being described by an array schema, ie. the dynamic creation of the json schema does not take into account the fact that the results have been split. This in turn causes a problem for the datamapper:
- Data Mapper shows on the source side an extra parent array node with the entity schema as its child;
- Mapping then publishing causes failure;
This can be rectified but now begs the question should it in favour of removal of the split option, leaving the function to be performed by the split step.

**Comment by phantomjinx** [comment]
@christophd @oscerd @heiko-braun @lburgazzoli 
Guys, I would value your opinions on this, thx.

**Comment by christophd** [comment]
> a flaw has been identified in the odata split option, namely that even though the result is split the json is still being described by an array schema, ie. the dynamic creation of the json schema does not take into account the fact that the results have been split

We can sort this out in the dynamic meta data lookup so this will be in sync with the split option set in the connector.

This leaves the desicion weather to keep the connector split option or not just to the point of usefulness. 

In case we decide to not keep it we should definitely backport that change to the 7.3 release in order to avoid another db migration of existing integrations using the split option. 

Also we have to adapt the final decision to the Google Sheets connector as we have the split option there, too.

**Comment by christophd** [comment]
Regarding usefulness I personally think that the split option on the connector is very straight forward and easy to use for a citizen integrator.

Using the split step requires more insight and understanding of message processing in my opinion. You have to understand where to place the split step and what you want to do. 

Also at the moment split option and split step are identical in functionality. But split step may be much more powerful in the future with custom split expressions and aggregate strategies provided by the user.

Split option on the connector will remain the easy to use and comfortable way to process each element for the whole integration

**Comment by jsafarik** [comment]
@phantomjinx just tried to verify if odata read with split enabled -> Data Mapper -> DB still causes failure, and it does. Should that have a new issue created?
I looked at the output of the entity when split is enable, and the entity is still inside array that is inside array: `[ [ {entity} ] ]`. is this the right behavior?

**Comment by phantomjinx** [comment]
@jsafarik 
Well that's surprising so yes please can you provide all the info you have and I'll take a look. Technically, the customizers detect if split is set and don't add results into lists. Likewise, the Olingo4Consumer should not add extra lists/arrays so mystified where they would come from. If the results do actually return an array-inside-array then it would come through intact but know way of being sure until I see your odata query.

**Comment by jsafarik** [comment]
@phantomjinx ok so that was my bad I guess, just tried it with syndesis 1.6.3 and I am able now to use the data mapper with split step enabled in OData connection, I have tried simple OData read -> data mapper -> insert into DB with mapping some Strings and everything worked properly.

regarding the entity inside array inside array, I was told that the log in syndesis UI just adds square brackets to the output, so I tried to compare the output of split option in OData with split step and it matched. The only difference is:
With split step there is one integration logged that contains all entities from the split collection:
![split_step](https://user-images.githubusercontent.com/46523434/54753782-34151600-4be2-11e9-85c8-439f5399fac5.png)

But with split option enabled in OData connector, there is one integration logged for each entity, containing only the one entity:
![split_odata](https://user-images.githubusercontent.com/46523434/54753873-66267800-4be2-11e9-9d0d-efed9cb6bea4.png)

But since the split option in odata connector and split step can be used the same way, I guess the form of logging is not a big issue.

**Comment by phantomjinx** [comment]
@jsafarik
Phew! that's a relief!
As regards the split step logging, what you may be seeing depends on where the logging is tracking the messages in the camel exchange.
- The split step occurs as a processor after the odata endpoint so the input of this step is a collection of entities which get broken up and sent out as individual messages;
- The split option occurs inside the odata endpoint. Thus, the output of the odata endpoint is individual messages for each entity.

Thus, I think it depends on at what point in the camel route, the logging is tracking.

**Comment by jsafarik** [comment]
@phantomjinx 
Well the integrations were:
OData (with split option enabled) -> log -> ...
vs
OData -> split step -> log -> ...
so since the logging is always after the splitting I thought the output of the log should be the same.

**Comment by jsafarik** [comment]
@phantomjinx 
with the last comment I posted, I guess the output should look the same, still not sure if this could cause any issue.

**Comment by phantomjinx** [comment]
Me neither. If the logging is basically reporting at the same point then they should look the same. The fact they aren't is odd.

**Comment by jsafarik** [comment]
So I guess it is going to behave this way (even with the difference in logging, it still hasn't reveal any issue). 
Since the split option is kept, can I close this issue?

**Comment by phantomjinx** [comment]
Yeah. I should think so. I haven't looked into the differences in logging and, due to no issue, I think it is at best a low-priority investigation.

**Comment by jsafarik** [comment]
ok, thanks, closing
