### ISSUE TITLE
Google-sheets: Max results is ignored

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#4997]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
User is still getting amount of rows defined in range so max results option is not taken into account.

**Comment by christophd** [comment]
seems that max results only applies with proper effect when split option on the GoogleSheets connector is enabled

**Comment by christophd** [comment]
@gaughan @heiko-braun this could be a p0 as max results limitation occasionally is not applied to the GoogleSheets results and this may lead to lots of returned rows when user specifies unbounded ranges such as (A:C) in combination with max results setting (e.g. 100). Then all rows are returned instead of the limit 100 rows.

**Comment by heiko-braun** [comment]
I would leave this to @gaughan.  It seems we already have a PR for this, right?

https://github.com/syndesisio/syndesis/pull/5008

**Comment by christophd** [comment]
@heiko-braun yes that is the PR to master

**Comment by gaughan** [comment]
P1 in 7.4 I think
