### ISSUE TITLE
Auto merge of small pull requests

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#506]
Create a label “2s2f” (“too small to fail”) which, when applied by the author, force a merge by purebot without a review

**Comment by apupier** [comment]
out of curiosity:
What is the benefit of removing a human review if the PR is very easy to review?
How can each developers determine when a modification is "too small to fail"?

**Comment by rhuss** [comment]
The time between starting the PR and doing the review. The issue we do address is that the lead time for PR reviews are too long. That way we can focus on the PRs requiring a tough review (just have a look into our PR backlog)

Of course, this could be misused (so in https://github.com/syndesisio/pure-bot/issues/30 asked for a certain threshold until which this label can be applied). Maybe it might make sense to send out a notification (e.g IRC) for such auto-merged PRs so a post-mortem review could be done if desired. 

At the end, a review is an incentive for the author of a PR to increase quality (which we are all after, right ?) and it's his/her responsibility and judgement that the PR is *really* too small to fail (and with small impact). Typo updates, comments, minor build beautification, ... all that sort of this things.

Don't forget that these PRs still have to pass the CI pipeline.

Another idea was even more drastic: Automatically merge stale PRs after three days when they pass CI.

We might even consider this ;-)

It's not only about speed but also about trust in the people, tests and CI.

**Comment by apupier** [comment]
> At the end, a review is an incentive for the author of a PR to increase quality (which we are all after, right ?) and it's his/her responsibility and judgement that the PR is really too small to fail (and with small impact). Typo updates, comments, minor build beautification, ... all that sort of things.

I don't think that everybody agrees on the level of quality and so is after reaching the same level of quality.
Having a second pair of eyes is helpful to detect when some files were committed inadvertently. I experienced it from time to time.
Even for fixing typo, I have a recent example where the typo was needed to be fixed upstream instead of in the repository itself as the code was generated/duplicated (and you were the reviewer and was happy that you pointed it)

I think that "minor build beautification" is really something that is not trivial. It can work locally, on CI if not rebuilt but it might not break for some other local installations, on rebuild of the CI.

Do you see my point on "how to set the limit between trivial and not trivial pull request"?

I think that increase of quality is not the only goal. It is also to always be in a "releasable state" and to avoid blocking a whole team, even for few minutes, because of a bad modification.
Adding another layer of check by forcing a review seems 

> It's not only about speed but also about trust in the people, tests and CI.

I will never be good enough to trust myself and in my knowledge of a whole codebase.
For tests and CI, I don't think that we are in the kind of project where we can blindly rely on that. I mean: do we have almost 100% for permutation testing?
(i'm not criticizing the current level of test confidence, having 100% permutation testing coverage would cost far too much and will surely not bring enough value)

>That way we can focus on the PRs requiring a tough review (just have a look into our PR backlog)

Some other possibilities can explain a huge PR backlog:
- PR are too complex so it requires too much time
- time spent reviewing code is lower than what is needed (Developers usually prefer writing code instead of reviewing code)
- there are too many external contributors and not enough reviewers

Anyway, i'm not working fulltime on this codebase. It is also to each team to define their own processes and level of quality. I just want to share my little experience and to warn that it really looks **to me** a bad way to go in most circumstances.

**Comment by rhuss** [comment]
> Having a second pair of eyes is helpful to detect when some files were committed inadvertently. I experienced it from time to time.

So review _was_ an incentive for you, isn't it ? Also having more than one file commit very likely doesn't qualify for '2s2f'. At least not for me, but thats for each author to decide.

> Even for fixing typo, I have a recent example where the typo was needed to be fixed upstream instead of in the repository itself as the code was generated/duplicated (and you were the reviewer and was happy that you pointed it)

Agreed. But again, I wouldn't have classified that a fix 'too small to fail', especially it was for a repo you are not working with every day. You are completely free to *not* use that label if you like to have a review. As I said, its a service _for the author_ which he can request.

> I think that increase of quality is not the only goal. It is also to always be in a "releasable state" and to avoid blocking a whole team, even for few minutes, because of a bad modification.

The "releasable state" should be guaranteed by the CI not by a review. That's not their purpose.

> Do you see my point on "how to set the limit between trivial and not trivial pull request"?

Absolutely. If you are unsure, don't use that label.

> will never be good enough to trust myself and in my knowledge of a whole codebase.
> For tests and CI, I don't think that we are in the kind of project where we can blindly rely on that. I mean: do we have almost 100% for permutation testing?
> (i'm not criticizing the current level of test confidence, having 100% permutation testing coverage would cost far too much and will surely not bring enough value)

I maybe would agree if we would live in a perfect world. But let's face it, we do not. So we have two possibilities: Force people to a process, or adapt the process to the people. Of course this is not an either-or but there are many shades of gray. In general I lean towards highly to the second way (adapt the process to the people, that's all what agile is about) if we can make *good compromises* that bring us forward on many axis (in speed, quality, fun, ...). THis is a good compromise IMO.

Good example is that people started to force merge (without a running CI or review), because they were desperate and disenchanted because either no reviews are picked up or the CI was constantly failing. And we we are currently acting in a high pressure context, too.

> PR are too complex so it requires too much time

That's a bit of an catch22: PR tend to grow when the lead time for PR reviews grow, because otherwise the idle time waiting on the PR to merge to continue on this feature gets too large. But large and complex PR are not picked up quickly for a reason.

> time spent reviewing code is lower than what is needed (Developers usually prefer writing code instead of reviewing code)

That's IMO the biggest problem. Also, that's always the same people doing reviews, others are not showing up here. We have even issue for this #508 .

> there are too many external contributors and not enough reviewers

That's not an issue for us (no external contributors).

> I just want to share my little experience and to warn that it really looks to me a bad way to go in most circumstances.

@apupier thanks for your feedback, really appreciated. I agree with you it really depends on the team and the team character. All in all the important part is to keep the machine rolling while still producing high quality code.

**Comment by gashcrumb** [comment]
We all know the reality :-)
