### ISSUE TITLE
warns about parameters changed on a connection

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5076]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I create an integration on staging I always see the banner that warns about parameters changed on a connection

![image](https://user-images.githubusercontent.com/1868933/55149176-fbc58880-5149-11e9-9938-1b27252fcff9.png)

**Comment by lburgazzoli** [comment]
@tplevko fyi

**Comment by lburgazzoli** [comment]
@phantomjinx do you mind having a look ?

**Comment by phantomjinx** [comment]
@lburgazzoli 
Having looked into this, this morning, note the following:
* The message appears due to the [IntegrationUpdateHandler](https://github.com/syndesisio/syndesis/blob/master/app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java#L322)
* The comparison tests the connection cached in the Integration against that stored in the database manager. So when I do see the message it was due to the output-spec having been changed between an integration and connection being created (ironically, the connection was out-of-date and once it was edited/revalidated, the message disappeared). Thus, it could simply be that the connectors need revalidating and saving?

* One change I have made locally is to not bother with the connection comparison if [integration.isDeleted == true](https://github.com/syndesisio/syndesis/blob/master/app/server/update-controller/src/main/java/io/syndesis/server/update/controller/bulletin/IntegrationUpdateHandler.java#L322). This reduces the work that has to be done but shouldn't introduce a false positive.

* It is possible to observe what the comparison failure actually is by looking at the brower Network tab, see screenshot. This might give us a clue as to what is causing the messages in the first place.

![config-required-detail](https://user-images.githubusercontent.com/1634180/55405455-0620c180-5552-11e9-9160-a35b55bdd26f.png)

**Comment by mastepan** [comment]
@lburgazzoli  just checking. Is there anything that should be checked by QE?
