### ISSUE TITLE
Better distribution of reviews

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#508]
Better distribute PR reviews so that reviews get merged faster and don't put the burden on a few doing the reviews (which is always hard work)

Some ideas:

* Re-enable mentionbot #418 
* Author actively select the reviewer and assigns it (+ pings on IRC). An even distribution still is a problem then.
* A "Default Feature Reviewer": When the feature team is formed at the beginning a "Default Reviewer" is nominated, which needs not to be from the feature team but is willing to follow the feature technically and domain-wise. That way the ramp-up remains small for a reviewer
* Activate an IRC bot for each PR coming in, maybe with already starting to bug potential reviewers.

@syndesisio/all Other ideas, opinions ?

**Comment by rhuss** [comment]
Another idea is to do some [agile gamification](http://gameagile.com/).

My idea was to use something like a horse race as a web-app

![Horse Race](https://images.fineartamerica.com/images-medium/carnival-horse-race-game-garry-gay.jpg)

* Each developer is a horse rider.
* The race length mimics a sprint (or TP cycle or even longer)
* When pressing on the button the race starts:
   - For each tick (sprint day), a metric per rider is measured based on : Number reviews, number comments, length of comments, time to pick up the PR, response times ... This should all be queryable from the GitHub API
  - Depending on the metric, the riders advance.

At the end of the Sprint the data is deleted and the race starts afresh.

I could imagine here some fancy animated Web-App (which might be even useful for other projects, too ;-) which is offered to the team only (shouldn't be public probably).

**Comment by amysueg** [comment]
@kcbabo and I are having a related conversation about timely review and approval of UX designs. I like the idea of targeting a "default feature reviewer" and also "approver." In the case of UX designs, I believe we need approval sign-off from UX, Dev, and PM.

**Comment by rhuss** [comment]
Yes another idea: A _PR budget_ : You have an initial budget from let's say 5. Then, for every PR submitted as author this number decrease by one, for each Review done the number increases. 

Goal: Not to go below 0.

**Comment by zregvart** [comment]
> Yes another idea: A PR budget

Can I start at 100 😀

**Comment by kahboom** [comment]
@rhuss - This is great, thanks for opening this issue. lol A few comments:

- I know most people don't like a lot of noise from the IRC bots, but I find it very useful if it's just for PRs being opened, not for every issue opened or anything like that.
- Would be nice to get pinged if you are mentioned in the original PR opening or if you are automatically assigned by default, or something that is more relevant to you vs. a PR for something totally irrelevant (e.g. pinging someone from UXD when it's a new PR for the backend, unless they specifically mention them). Though of course you could just manually ping someone as well. 😂 
- It's very convenient to have a bot put the link to the newly opened PR as well.
- Since we are now using a monorepo, I think it's important to either have the specific ping feature or to have the bot specify the label or something that shows if it's for UXD, REST API, UI, etc.
- While I really appreciated the racehorse illustration and it made me laugh, and I like the idea of tracking this visually, I don't know if we want to have a kind of competitive environment by making it look/feel like a race. It could be fun though, I'm not sure as I've never seen it in practice! Willing to try anything out that might help tackle this problem.

**Comment by zregvart** [comment]
So I feel that `mention-bot` is not doing a good job anymore, it keeps assigning to fallback regardless of file history and PR manual review assignment. Perhaps it's time to give up on it?

**Comment by rhuss** [comment]
Yes, I would disable it for now. Doesn't make sense when it always falls back to the default. Maybe we should switch on the GitHub native assignment ?

**Comment by gashcrumb** [comment]
Think this is kinda stale now that we've decided YOLO no reviews by default...
