### ISSUE TITLE
Support for conditional mapping in AtlasMap

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#5113]
Bump AtlasMap version to 1.40.0 or later to enable conditional mapping in Syndesis data mapper step. No additional work is required at Syndesis side.

**Comment by heiko-braun** [comment]
@gaughan Can you provide a user story and acceptance criteria for this?

**Comment by gaughan** [comment]
added to atlasmap
https://github.com/atlasmap/atlasmap/issues/848

**Comment by igarashitm** [comment]
Do we keep this until we update AtlasMap version in Syndesis to the one contains atlasmap/atlasmap#848?
I'm A-OK closing this and go with #848, but I don't know if QE guys are watching AtlasMap Epics. Also I know pure-bot reopen the issue after auto-close due to PR merge in Syndesis (guess for QE?), but it's not working like so in AtlasMap.

**Comment by heiko-braun** [comment]
Closing as duplicate of https://github.com/atlasmap/atlasmap/issues/848
