### ISSUE TITLE
API provider ignoring query parameters

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#5152]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Query parameters on API provider operations are always `null`. The query parameter is passed to the unified data shape but the value is not set correctly at runtime. Instead the parameter value is always `null`.

You can reproduce this with a simple GET operation that uses a query parameter and log the body right after entering the operation flow.

**Comment by mmuzikar** [comment]
I have a question regarding the option to make the parameters required / not required... Is there an easy way to handle null values of not required parameters? I thought about filtering but there is no such thing in basic filter as `is present`/`is not present`, so should it be compared to `null`? It would probably be best handled by conditional mapping or the data mapper conditional mappings.

Just a food for thought for @syndesisio/uxd we might not be best suited for working with "might not be present values"

**Comment by mmuzikar** [comment]
To further explain my previous question... it seems that using required parameters causes unintended behavior... it's hard to recognize any patterns of behavior because of how long it takes to set up the integrations and change the definitions but I will do my best to describe what I encountered and it will probably be cleaner to understand what's happening during the fixing.

I tested on API provider with just one path and GET operation specified, usually returning string so I don't have to check logs in Openshift. I remember that when I defined the operation with not required parameters (all strings), everything worked correctly (or as expected, the pod maybe crashed a few times when I was using the parameters in datamapper etc.).

When I started testing the required parameters, most of the times the integration pod crashed even when I included the parameter in my request, which caused the pod to get stuck in crash loop and after that every API provided I specified seemed to be misbehaving even when I created a new one with not required parameters.

**Comment by zregvart** [comment]
@mmuzikar bit difficult to troubleshoot this without an example of the integration/openapi document that crashes or logs from the integration pod. Can you provide those?

**Comment by mmuzikar** [comment]
[api-provider-test-export.zip](https://github.com/syndesisio/syndesis/files/3305024/api-provider-test-export.zip)

This should crash right after the application gets started

**Comment by mmuzikar** [comment]
The crashing is no longer a problem for me.
The API Provider doesn't ignore query parameters anymore, not required parameters can be addressed with Conditional flows. 
Verified by QE.
