### ISSUE TITLE
Links in masthead help menu don't work 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#5154]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I'm using the staging site and noticed the links in the masthead help menu (clicking on the "?" icon) don't work and go to 404 pages. 

These following links don't work:
- Sample Integration Tutorials 
- User Guide 
- Connections Guide 

## Expected behavior

All links should go to proper web pages. 

## Screenshot

<img width="583" alt="Screen Shot 2019-04-05 at 3 13 55 PM" src="https://user-images.githubusercontent.com/24943812/55651103-8bf07700-57b5-11e9-9ae8-fe4f7ffb9a6a.png">

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by dongniwang** [comment]
@gashcrumb @seanforyou23 - I'm wondering if this is only happening on staging? And if this is introduced by the masthead updates? 

cc: @TovaCohen

**Comment by gashcrumb** [comment]
I think the 7.3 content is not yet live, so these links won't work until then.

**Comment by TovaCohen** [comment]
Stan is right. If you look at the URLs on the 404 pages, you will see "7.3" in them. There will be content there when 7.3 is actually released. Since no one but us would see them, I think that's okay. If you think we ought to display something that says that the content has not yet been published since that version of the product has not yet been released, let me know.  

Glad to see that someone besides me checks the links!

**Comment by dongniwang** [comment]
Thanks @gashcrumb and @TovaCohen! In this case, I think we can close this issue.
