### ISSUE TITLE
Any way to make the guided tour go away?

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#516]
It's popups always appear and it's not clear what to do to make them stop showing up altogether.

**Comment by kahboom** [comment]
We'd need to add a setting, or check for first time users. That was supposed to be based on whether the point of entry is the registration page (there was another name for it), but we did away with it. I'll see if I can find out what we decided would be the indicator for first time users, I can't remember since it was a while back.

**Comment by gashcrumb** [comment]
This is also not applicable
