### ISSUE TITLE
Implement update technical extension flow

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#518]
Last remaining item:

https://github.com/syndesisio/syndesis/blob/master/ux/designs/technical_extensions/tech_ext.md#update-existing-technical-extension

**Comment by gashcrumb** [comment]
@lburgazzoli on the update flow, how do I notify the backend that the jar file the user is posting is an update for an existing tech extension?  It's not clear to me from https://github.com/syndesisio/syndesis/blob/master/project/proposals/181-tech-extension.adoc apologies if I missed it...

**Comment by lburgazzoli** [comment]
@nicolaferraro can you help @gashcrumb ?

**Comment by nicolaferraro** [comment]
@gashcrumb the endpoint for the update is the same as the one for the import (you just have to pass an additional parameter), because from a backend point of view you're adding a new tech extension, not changing the previous one.

So, for the upload part, just POST the multipart data to the `/extensions?updatedId=<id-of-previous-extension>` the same way you do for the import process. You must pass the `id` field of the extension you want to update as query parameter (note it's the `id` field, not the `extensionId`).

You'll get back a json representation of the tech extension (with a new `id`) that can be validated using the `/extensions/<id>/validation` and installed using `/extensions/<id>/install`. These 2 endpoints are the same used in the import process.

**Comment by gashcrumb** [comment]
Ah okay perfect, thanks!
