### ISSUE TITLE
More info about syndesis

### ISSUE THREAD

**Issue by shneha** [syndesisio/syndesis#5508]
## Description
May I know if it is possible to design a whole new flow/API using Syndesis?
How can I get conditional operations like if/else, loop etc. in syndesis?

**Comment by paoloantinori** [comment]
Hi @shneha, thanks for your interest in Syndesis.

Since it seems that you have just started using the application, we could use your help to review our documentation and quickstarts and gather your feedback on the missing parts.

Could you go through our documentation published here: https://syndesis.io/  and add notes to this thread about the sections that are not clear or missing altogether?
Taking inspiration from your question above, but applied to the context of the documentation that is already published.

thank you!

**Comment by shneha** [comment]
Sorry for late revert... will go through with the documents and definitely provide feedback.
