### ISSUE TITLE
unable to create email connection in the new ui

### ISSUE THREAD

**Issue by wyvie** [syndesisio/syndesis#5560]
See also **https://issues.jboss.org/browse/ENTESB-11423**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

In the new react UI, there are problems with email connectors:
When creating a new email connection, if it's a `send email`, then the `Validate` button does not get enabled and is impossible to click, making it impossible to finish connection creation.
When creating a `receive email` connection, during the validation an empty red rectangle is drawn, and validation also gets failed.

## Expected behavior

It's possible to both validate and create both types of email connections.

## Screenshot

![image](https://user-images.githubusercontent.com/3992240/58799596-0860d400-8606-11e9-9542-6782fad11b09.png)

**Comment by paoloantinori** [comment]
This is in Technology Preview, by definition not a blocker

**Comment by gashcrumb** [comment]
![image](https://user-images.githubusercontent.com/351660/58804920-f91b5f80-85e0-11e9-9eab-1dc37f79d7a0.png)

validate/next won't become enabled because there's a `hidden` property that's set to `required` and has no `defaultValue` setting.  So really this needs to be fixed on the connector side.  

Not sure about what's coming back in the server response for the validate button for it to show up like that, there should be a message string, unless for whatever reason the response isn't matching what the UI is expecting.

**Comment by riccardo-forina** [comment]
By the way, the behavior of the UI changed a bit since [this PR](https://github.com/syndesisio/syndesis-react/pull/404).

For "Receive emails" the validation works as expected, with a gotcha: the BE returns this error `username should be set, password should be set` if username and password are empty, but those fields are not marked as required. Maybe they should?

For "Send emails" I can't get the BE to validate the form properly. 
There is the same error as in the "Receive emails" about missing required username/password, but it's also complaining about a missing `protocol` field. 
Checking the definition, the `protocol` field is marked as `hidden` and `required`. Where should we be getting this data from? 
Note that we are actually sending the `protocol` field to the validation API, since it's marked as `required`: 
```json
{"host":"ddd","password":"ddd","port":123,"protocol":"","secureType":"None","serverCertificate":"","username":"ddd"}
```

This is the whole definition for the "Send emails" connector:
```json
{
  "host": {
    "order": 2,
    "componentProperty": true,
    "deprecated": false,
    "description": "The hostname of the email server.",
    "displayName": "Email Host Name",
    "group": "common",
    "javaType": "java.lang.String",
    "kind": "parameter",
    "label": "common",
    "required": true,
    "secret": false,
    "type": "string"
  },
  "password": {
    "order": 5,
    "componentProperty": true,
    "deprecated": false,
    "displayName": "Password",
    "group": "security",
    "javaType": "java.lang.String",
    "kind": "parameter",
    "label": "common,security",
    "labelHint": "Specify a password for authentication of the email service, if required.",
    "required": false,
    "secret": true,
    "type": "string"
  },
  "port": {
    "order": 3,
    "componentProperty": true,
    "deprecated": false,
    "description": "The port of the email server.",
    "displayName": "Email Server Port Number",
    "group": "common",
    "javaType": "java.lang.Integer",
    "kind": "parameter",
    "label": "common",
    "required": true,
    "secret": false,
    "type": "integer"
  },
  "protocol": {
    "componentProperty": true,
    "deprecated": false,
    "displayName": "Protocol",
    "group": "common",
    "javaType": "java.lang.String",
    "kind": "parameter",
    "required": true,
    "secret": false,
    "type": "hidden"
  },
  "secureType": {
    "order": 6,
    "componentProperty": true,
    "defaultValue": "None",
    "deprecated": false,
    "displayName": "Security Method",
    "group": "security",
    "javaType": "java.lang.String",
    "kind": "parameter",
    "label": "security",
    "labelHint": "Specify what security protocol (if any) the connection requires",
    "required": false,
    "secret": false,
    "type": "string",
    "enum": [
      {
        "label": "None",
        "value": "None"
      },
      {
        "label": "StartTLS",
        "value": "StartTLS"
      },
      {
        "label": "SSL / TLS",
        "value": "SSL/TLS"
      }
    ]
  },
  "serverCertificate": {
    "order": 7,
    "componentProperty": true,
    "deprecated": false,
    "description": "If the SSL email server is internal and possesses a self-signed certificate then enable SSL by adding the certificate here.",
    "displayName": "Server Certificate",
    "group": "security",
    "javaType": "java.lang.String",
    "kind": "parameter",
    "label": "common,security",
    "relation": [
      {
        "action": "ENABLE",
        "when": [
          {
            "id": "secure",
            "value": "true"
          }
        ]
      }
    ],
    "required": false,
    "secret": false,
    "type": "textarea"
  },
  "username": {
    "order": 4,
    "componentProperty": true,
    "deprecated": false,
    "displayName": "User Name",
    "group": "security",
    "javaType": "java.lang.String",
    "kind": "parameter",
    "label": "common,security",
    "labelHint": "Specify a user name for authentication of the email service url, if required.",
    "required": false,
    "secret": false,
    "type": "string"
  }
}
```

**Comment by phantomjinx** [comment]
@riccardo-forina 
Have created new issue #5599 to address your comments & comments in #5559.

**Comment by tplevko** [comment]
> This is in Technology Preview, by definition not a blocker

Hi @paoloantinori, I also think it's necessary for the TP features to be flawless - by definition, but it should be at least possible for it to be usable to some extent.
I think this should be reevaluated to p0. In case the TP feature can't be used by the user at all, it should be considered to remove it from the release.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11423**
