### ISSUE TITLE
Should we adopt git-octopus

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#559]
[git-octopus](https://github.com/lesfurets/git-octopus) seems like a nice way of doing continuous integration. I think it might help us notice issues of two PRs not being integrated sooner.

**Comment by rhuss** [comment]
Looks good but isn't it really superior to manually rebasing our work? Its yet something which can fail (not only because of the merge), also we tend to use "WIP" branches which are not supposed to pass all integration tests and this will lead to another "red light". Too many alerts simply cause that all alerts get ignored eventually.

I'm more happy to have less, but meaningful checks. Like our CI, happy (and hard enough) to get this green.

**Comment by zregvart** [comment]
I think we can set it up so only build for the particular PR goes red, which would be a good thing™️, i.e. that would mean that that branch needs to be rebased or that another PR is clashing with this one, and that would also be a good thing™️ to catch early.
The goal should be that once a PR build is green there is nothing stopping the PR from getting merged, IMHO few failures on WIP branch just bring more confidence in a green build.

**Comment by gashcrumb** [comment]
Apparently not :-)
