### ISSUE TITLE
Multiple authentication schemes in same API client custom connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#5595]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When we create a custom API client connector from an OpenAPI document we require that the user selects a single authentication scheme for authenticating against the API service: one of basic authentication, API key or OAuth, depending on what [security definitions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityDefinitionsObject) are given in the provided OpenAPI document.

Another concept of the OpenAPI specification is the notion of [security requirement](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-requirement-object), that prescribes what if any security definitions are required for invoking an API operation.

In the custom API connector disregard the defined security requirement for all but for API keys.

In order to support both security definitions and security requirements as defined in the OpenAPI specification we would need to:

 1. have a connection that can hold multiple credentials (say OAuth and API keys) at the same time
 1. choose an appropriate credential at runtime depending on the operation being invoked (have the user select if multiple are applicable?)
 1. remove the screen prompting the user to select a single authentication scheme for the connector
 1. when creating API client connection allow the user to specify all credentials according to the security definitions
 1. when choosing an API client action (= API operation) filter out or indicate what actions are unavailable as the connection lacks the credentials required for it's invocation
 1. allow the user to select which credential to use when choosing an action (= API operation) when multiple apply

cc @dongniwang @kahboom @EricWittmann @gaughan

**Comment by EricWittmann** [comment]
In some advanced cases, an OpenAPI operation may be configured with multiple Security Requirements, so the user could perhaps choose which one they want to use.  And worse, each Security Requirement is actually an ordered combination of 1 or more Security Scheme.  Meaning that a single Security Requirement **might** indicate that 2 or more Security Schemes must be used when authenticating.  For example, an operation could be configured to require **both** API Key **and** Basic Auth.

This makes things potentially pretty complex.  However, it should be noted that the advanced cases (combined security requirements and/or multiple security requirements) are pretty rare.  So there is probably some evolution that can happen here to improve support without going all the way.

**Comment by kahboom** [comment]
Following up from the other issue.. and sorry for the long response.

>@kahboom can you attach or point to the OpenAPI document you tested with to syndesisio/syndesis#5592?

Sure thing: https://github.com/kahboom/api-examples

Under `combination` there is one called `multi-oauth-2.0.json`, that one has multiple OAuth 2.0 security schemes, including one that is `implicit` (was curious to see how the app would handle it).

> Except that the two fields should be something like Authorization URL and Token URL. Those two fields should only be visible when the user selects the OAuth scheme (rather than e.g. Basic Auth). And both fields should be editable and pre-filled with whatever values came from the OpenAPI doc.

+1 We do that now, but since we don't support `application` or `implicit` and their URLs are returned in the same property, we get some wonky behavior even if it's just one OAuth scheme (only one of the fields will be pre-filled depending on what flow it is). I have a question though--for any one OAuth `accessCode` scheme, I see that both the `authorizationUrl` and `tokenUrl` fields are required per the OpenAPI spec-- did I read that correctly? At the moment we are able to create a connection with only one of these fields, I think even Apicurio allows it.

> I assume that when you select Basic auth (if that is an option in the OAI doc), then the UI presents the user with Username and Password input fields?

Sadly, no. I'm not sure if this is supported or what happens in the BE--maybe this is taken directly from the `specification` object? cc @zregvart 

<img width="803" alt="Screenshot 2019-06-05 10 59 31" src="https://user-images.githubusercontent.com/3844502/58951838-13447180-878a-11e9-8b7b-576c2846513f.png">

>Yeah different authentication schemes conflict a bit with the notion of a single connection, or at least make it more difficult to implement and create a good user experience at the same time, so we simplified it as much as we could to both make it easier to implement and to have a more streamlined user experience.

@zregvart I think if we wanted a different group of OAuth URL fields for each OAuth `accessCode` scheme provided from the spec, it makes sense to receive back an array of security scheme objects available from the spec, and those would contain the respective URLs.

It might be useful if we could also see the type of OAuth scheme, so that we could show/hide the fields based on that, and not just on whether or not it exists. For instance, if it is `accessCode` but the user only provides the `tokenUrl`, we should still show both fields because of the scheme type. Or if it's anything other than `accessCode` we can just hide it from the list of options altogether until we support that.

Right now we see an array of the label and value like this: `enum: [{label: "HTTP Basic Authentication", value: "basic"}]`, which are used to create the list of radio button items, but the details of each are in another property altogether and appear to only support one single URL of each kind via a `defaultValue` (see below). It would also be good if in those objects we had a specific label for each OAuth Scheme.

What we currently receive from the BE:
```
properties.authenticationType.enum // see below
properties.authorizationEndpoint.defaultValue*
properties.tokenEndpoint.defaultValue*
```

_* if there are multiple OAuth schemes, this really doesn't work_

where `enum` can look like:
```
"enum": [
{
  "label": "OAuth 2.0",
  "value": "oauth2"
},
{
  "label": "OAuth 2.0",
  "value": "oauth2"
},
{
  "label": "HTTP Basic Authentication",
   "value": "basic"
},
{
  "label": "API Key",
  "value": "apiKey"
}
]
```

If the scheme type is `basic`, we can access `defaultValue`, but for anything else it's difficult to pre-fill the fields when there is more than one OAuth 2.0 scheme in the spec.

Properties we might send to the BE, only one scheme:

```
configuredProperties.authenticationType = "oauth2";
configuredProperties.authorizationEndpoint = "https://www.example.com/";
configuredProperties.oauthScopes = "utm.example.admin_read.constraint utm.example.admin_read.myadmin";
configuredProperties.specification = "{}";
configuredProperties.tokenEndpoint = "https://token.endpoint.url";
```

> an operation could be configured to require both API Key and Basic Auth.

😱

**Comment by EricWittmann** [comment]
> I have a question though--for any one OAuth `accessCode` scheme, I see that both the `authorizationUrl` and `tokenUrl` fields are required per the OpenAPI spec-- did I read that correctly? At the moment we are able to create a connection with only one of these fields, I think even Apicurio allows it.

I don't know the OAuth flows very well, but that is correct according to the OpenAPI spec.  Apicurio allows you to provide only the Auth URL if you want, but if you do that then you'll get a validation error:
![image](https://user-images.githubusercontent.com/1890703/58955137-1713cc00-8769-11e9-9360-760f66018dfe.png)

> > I assume that when you select Basic auth (if that is an option in the OAI doc), then the UI presents the user with Username and Password input fields?
> 
> Sadly, no. I'm not sure if this is supported or what happens in the BE--maybe this is taken directly from the `specification` object? cc @zregvart

This probably makes sense now that I think about it - perhaps when creating the connector you're just configuring what kind of auth to use...and then at some point later when a connection is actually established the user must provide some concrete auth credentials of some kind.

> > an operation could be configured to require both API Key and Basic Auth.
> 
> 😱

I know, right?
