### ISSUE TITLE
Advanced filter description 

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5605]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

## The problem

The description of the advanced filter step is `Advanced Filter - Continue the integration only if criteria you define in scripting language expressions are met.` 

## Expected behavior

There should be list of the scripting languages the user can use for writing such expressions. 
I didn't find any information on which languages can be used in the documentation by looking for `filter` neither by looking up `scripting`.

If the scripting language is Simple expression language it would be also very cool if there was a link to this page [https://camel.apache.org/simple.html](https://camel.apache.org/simple.html), where the user can find more information about that language. or having similar page for other languages would be more user friendly.

**Comment by TovaCohen** [comment]
I did update the 7.4 doc for the Advanced Filter step to provide that link:
https://access.redhat.com/documentation/en-us/red_hat_fuse/7.4/html/integrating_applications_with_fuse_online/creating-integrations_ug#add-advanced-filter-step_create

I didn't get it quite right, because I referred to the Camel Simple Expression language when I should have referred to the Camel Simple Language. I already updated this for 7.5. So I'm going to close this issue.
