### ISSUE TITLE
[Conditional flow] flows are still accessible after deleting the step

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5608]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
The flow dropdown shows flows from the most recently added conditional step, which causes that the user is able to access unusable flows.

## Steps to reproduce
1. create a simple integration
2. add conditional step and create a few conditions 
3. delete the conditional step
4. look at the flows dropdown, there are still the *should be* deleted steps

## Screenshot
![Peek 2019-06-05 16-10](https://user-images.githubusercontent.com/46345469/58962919-7941f080-87ac-11e9-9d1f-f0e6b0e19361.gif)

**Comment by paoloantinori** [comment]
We have just switched to the React implementation for Conditional Flows.
Could you verify this?

**Comment by gashcrumb** [comment]
Yeah, think we need to add code in the delete handler to check the conditional flow step and remove the relevant flows.

**Comment by riccardo-forina** [comment]
[here](https://github.com/syndesisio/syndesis-react/blob/c6d2ba5c59cfa019a1495d9ac568871eb119e6f2/app/ui-react/packages/api/src/helpers/integrationFunctions.ts#L681) we already perform some flow sanitization, we should add this too.

**Comment by gashcrumb** [comment]
Yeah, but that's only done at save time isn't it?  We probably want to dump flows created by a conditional flow step when it's removed, otherwise they'll lurk in that drop down until the user clicks save.  Other option is flag them as "hidden" and then finally delete them during that sanitization if there's no references.  That could then give us the possibility to let the user re-connect these orphaned flows to a new conditional step at some point in the future.

**Comment by riccardo-forina** [comment]
Actually no, that's called every time the integration object is mutated (not saved).

**Comment by gashcrumb** [comment]
oh right on!  Then yeah, that'd make sense :-)
