### ISSUE TITLE
[api client connector] swagger file name reaches out of frame

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#5668]
See also **https://issues.jboss.org/browse/ENTESB-11417**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
After uploading swagger in api client connectors, the name reaches out of the frame:

![screenshot_20190611_131521](https://user-images.githubusercontent.com/14313995/59267710-2dc79080-8c4b-11e9-850c-f2e678edf7cd.png)

**Comment by mcoker** [comment]
@mcada @dongniwang I updated this so that the processed line (status icon and file name) are on a new line. Does that look ok? These are screenshots from the current staging site.

<img width="1143" alt="Screen Shot 2019-06-13 at 9 10 16 AM" src="https://user-images.githubusercontent.com/35148959/59439698-59698880-8dbb-11e9-9104-a090ca083754.png">
<img width="1143" alt="Screen Shot 2019-06-13 at 9 10 06 AM" src="https://user-images.githubusercontent.com/35148959/59439684-54a4d480-8dbb-11e9-98af-6bdfb72cd85e.png">
<img width="971" alt="Screen Shot 2019-06-13 at 9 12 06 AM" src="https://user-images.githubusercontent.com/35148959/59439704-5a9ab580-8dbb-11e9-92c8-56656b489074.png">

**Comment by dongniwang** [comment]
Success/error messages on a new line look good to me! Can you verify this behavior across different browsers?

**Comment by mcoker** [comment]
@dongniwang 

### edge
<img width="1166" alt="Screen Shot 2019-06-13 at 10 15 04 AM" src="https://user-images.githubusercontent.com/35148959/59444804-22e43b80-8dc4-11e9-9460-2e7aa9b49768.png">

### firefox
<img width="1036" alt="Screen Shot 2019-06-13 at 10 12 29 AM" src="https://user-images.githubusercontent.com/35148959/59444805-22e43b80-8dc4-11e9-8abb-b9716e311001.png">

### safari
<img width="1081" alt="Screen Shot 2019-06-13 at 10 12 14 AM" src="https://user-images.githubusercontent.com/35148959/59444806-22e43b80-8dc4-11e9-9f78-10f492e05938.png">

**Comment by dongniwang** [comment]
Looks good to me, thanks!

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11417**
