### ISSUE TITLE
not equals condition cannot be chosen in the Basic Filter

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#5702]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In the Basic Filter, when I choose `not equals`, the `equals` condition is chosen.
![output](https://user-images.githubusercontent.com/16251792/59356215-b9fbb580-8d28-11e9-8173-6e6e9409aacf.gif)

**Comment by gashcrumb** [comment]
So I noticed when first creating this interface that we get a really odd response back for the `enum` property for that field.  The UI tries to cope with it, but it'd be nicer if we could clean this up.  Here's what comes in:

![image](https://user-images.githubusercontent.com/351660/59365779-22d23600-8d07-11e9-971d-e449ab646458.png)

In fact, look at how two entries have "==" for the operator, i.e. "equals" and "not equals".  We map the "operator" field here to the select field "value", which means both entries produce the same value.  Which doesn't seem right.  And then there's ones that don't have labels, we currently band-aid that by mapping the operator to the label.  But really, it'd probably be better to have text for these also, `less than or equal` rather than `<=`.

@heiko-braun might need some server-side help on this one.

**Comment by gashcrumb** [comment]
FYI @elvisisking the mapping is done [here](https://github.com/syndesisio/syndesis-react/blob/master/app/ui-react/packages/api/src/WithFilterOptions.tsx#L74-L86)

**Comment by elvisisking** [comment]
@zregvart Please see @gashcrumb's comment [above](https://github.com/syndesisio/syndesis/issues/5702#issuecomment-501333556) with some issues with the server response.

**Comment by tplevko** [comment]
Verified
