### ISSUE TITLE
Error to create an integration with an expired token

### ISSUE THREAD

**Issue by claudio4j** [syndesisio/syndesis#5710]
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request

There is a google-calendar connection, unaware the access_token expired, I tried to create an integration, selected the "Get Events" action, then the error is displayed "Something is wrong" 

![error_create_integration](https://user-images.githubusercontent.com/836543/59391148-d4925680-8d49-11e9-94af-d7d49fa7780e.png)

Looking at meta server, there is an exception about the access token is expired. Would it be nice to report the error on the screen for the user.

**Comment by oscerd** [comment]
If the app creation is done the way it must be done the accessToken cannot expires. You need to do the oauth token flow from the settings page, just one time. Only the first time you'll get the refreshToken and your.credentials won't expire.This is not a big because following the docs this cannot happen
