### ISSUE TITLE
Continuous Integration improvement: UI and BE decoupling

### ISSUE THREAD

**Issue by balejos** [syndesisio/syndesis#5792]
As a result of our retrospective, we want to find ways to speed up the CI execution time by decoupling UI and BE. 
The decoupling may include the split in repos and/or builds. 
It also could help us to have better interfaces that eventually will facilitate experimentation and new clients.

Acceptance criteria:
* The solutions shouldn't just move the UI-BE "integration pain" to a bigger batch to the end of the cycle.
* It shouldn't promote to kick "your part of the stack" off by tossing a component “over the wall” to Back/Front ppl.

**Comment by KurtStam** [comment]
The reason we have the mono repo is to promote collaboration between teams, and to be able to find where all the pieces of Syndesis are. This was quite a problem before and it was hard to keep up with all the changes, and it let to frustration between the teams. The monorepo definitely made this much easier. Maybe we should move to a different build system instead.

**Comment by chirino** [comment]
Decoupling in this request sounds like "Allow things to stay broken for extended periods of time": -1

**Comment by chirino** [comment]
Could folks please articulate why we need the mono repo split up.

**Comment by balejos** [comment]
> Could folks please articulate why we need the mono repo split up.

@riccardo-forina is on PTO until Tue next week. Anybody else who could continue with the discussion?

**Comment by christophd** [comment]
I didn't bring this up in the retro but to my understanding from the discussion in the retro the main goal was to avoid building the UI parts when changes on the backend side are checked in and vice versa. So we can have a more dedicated build to what has actually been changed in a PR

**Comment by phantomjinx** [comment]
I did +1 this idea so will have a go at articulating my feelings on the subject ...

1. Architecturally, the UI is distinct from the BE, ie. the latter is not a dependency on building the former. The UI only requires the BE at runtime. Therefore, the interface protocols between the 2 systems are the only pieces that they share. They use different languages and therefore represent different software implementations. For me, this is the logical reasoning for a split.

2. Encourages the possibility of other UI's interacting with the BE interfaces. Whether this is something that would ever be prioritised, I don't know.

3. Implementation-wise, as we know, the build-system is creaking. People are looking at ways of parallelising modules, making some modules build while others don't, etc.. Specifically, from my experience, it has been frustrating to see a PR fail in test-building on account of a module failure that has nothing to do with the PR in question, eg. PR is connector & failure is in the UI or PR is UI & failure is in the server. If the build innovations are successful then this is certainly mitigated but slotting the UI into a separate repo to the BE seems an easy way of avoiding this.

I can appreciate the above comments that suggest the monorepo makes things easier to find, all-in-one-place etc. I know what a pain it is to find things. However, I feel that that represents shortcomings in implementation rather than logical reasoning in itself. If such shortcomings were carefully managed and overcome then 2 repos side-by-side can work. For example, the Teiid team have their server as a separate project to any of the historical UIs, inc. the bits coming into syndesis as DV, so in my experience such a split has been successful.

Anyway, that's my pennieth. Hope it's informative and useful.

**Comment by chirino** [comment]
Syndesis used to be multi repo.  After too many tears on the Jenkins CI/CD floor, we realized why mono repos rock:  They are simpler and allow you to atomically integrate feature sets across different modules.  We moved to mono-repo and everything has been better since.  For this to go back to being multi-repo, we need someone who lived through the multi-repo days of syndesis to explain why we need to go back to it.  Everyone else might THINK they know what it was like, but unless they lived it, I'm not going to believe you.  Sorry.

**Comment by gashcrumb** [comment]
Also there's nothing decoupled about the FE and BE really, there's all kinds of reasons to ensure it's easy to change both at the same time as easily as possible.  I've dealt with multiple repos plenty of times in the past and it's worse, trust me.

**Comment by gashcrumb** [comment]
Dump building the angular code if we want a quicker build, I don't think we need it any more.

**Comment by balejos** [comment]
We decided to drop it in yesterday's retro
