### ISSUE TITLE
Get operation in API provider with conditional flow results in white screen

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#5887]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When creating new API provider (used petstore swagger json) - when I select one of the GET operations (POST, PUT and DELETE work OK) and select conditional flow step - the integration ends in white screen. See the attached recording.

## Expected behavior

The UI shouldn't end in white screen - if this is not a valid use case, it should be handled in some more user friendly way.

## Screenshot

![out](https://user-images.githubusercontent.com/4180208/60007068-e50fce80-9671-11e9-8d2e-fe4cc5c8b97e.gif)

The web console output:

![Screenshot from 2019-06-24 11-17-29](https://user-images.githubusercontent.com/4180208/60007108-f78a0800-9671-11e9-8927-3fbfd8fe82f9.png)

## Tasks involved / Steps to Reproduce

1. Create API provider (petstore.json)
2. Select one of the GET operations
3. Select Conditional flow as the middle step
4. Observe white screen

**Comment by gashcrumb** [comment]
So this occurs because the conditional flow step has an `outputDataShape` of `ANY` and the console is trying to construct a URL to go to what would be the describe data shape page for that step.  Up to this point that particular page has only been used for "connections" like to AMQ or FTP.

@christophd Wonder, should I suppress this warning icon?  It'd normally be this one:

![image](https://user-images.githubusercontent.com/351660/60021545-331bd680-9660-11e9-9841-75a576139c47.png)

I could try and make the describe data work for the conditional flow step as well, but I worry that's too much change at this point.

**Comment by christophd** [comment]
Defining the output shape for conditional flows step (similar to FTP and AMQ) is already planned (see #5456) but it did not make it to the current release. So ignoring would be a good option for now.

**Comment by gashcrumb** [comment]
Perfect.  I started looking into seeing if I could squeeze it in, but I think it's going be non-trivial.  I'll suppress the warning for now instead with a TODO on it.

**Comment by tplevko** [comment]
Verified
