### ISSUE TITLE
DynamoDB Connector

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#5930]
See also **https://issues.jboss.org/browse/ENTESB-11495**

As a citizen user I want to be able to connect to DynamoDB datastore. I will provide my own connection configuration strings.

Acceptance Criteria
CRUD support
Stretch items
Adhoc queries (regex, range query)
Javascript queries?
Aggregation (Map-reduce)
Force ACID Transactions
--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

**Comment by gaughan** [comment]
@rareddy FYI

**Comment by rareddy** [comment]
@gaughan Are planning this one for 7.5?

**Comment by gaughan** [comment]
yes

**Comment by rareddy** [comment]
Added https://issues.jboss.org/browse/ENTESB-10910 and https://issues.jboss.org/browse/ENTESB-10909 to the backlog of the Data Integration to track the progress of DynamoDB in Data Virtualization. Currently, there is no translator written for DynamoDB so that is going to be lot more work to support.

**Comment by Delawen** [comment]
At this point I'm getting familiarized with both the Camel component for DynamoDB and DynamoDB itself. Once I finish that and make sure it works with latest version, I will start the Syndesis wrapper.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11495**
