### ISSUE TITLE
Base docker S2I image with camel-fuse.x.y.z dependencies

### ISSUE THREAD

**Issue by balejos** [syndesisio/syndesis#6100]
Coming from a Retro: The creation of a docker image with dependencies could help as a way to facilitate the development environment set-up.

**Comment by balejos** [comment]
Is still valid? Please, could you follow up on yesterdays discussion? @squakez @zregvart @KurtStam

**Comment by squakez** [comment]
Just a comment to frame properly the discussion. The issue I've been stumbled upon is about the need to recreate the S2I docker image that is used by runtime for building integration when there is any change that is needed by the integration (ie, changing a connector business logic).

This is the dockerfile I was referring: https://github.com/syndesisio/syndesis/blob/master/app/s2i/src/main/docker/Dockerfile

If instead the actual FROM we have a specific FROM of an image with pre-cached camel-fuse/syndesis dependencies in its local maven we'd spare all the actual download.

Another approach proposed was to install a local Nexus to proxy all requests locally instead, that could be a valid alternative.

I am not sure if however the effort is justified since we should push on Camel-K. I don't have yet enough info about the latter, neither enough experience on the project to take a proper decision.

**Comment by lburgazzoli** [comment]
Another option would be to take into account camel bits in any case, not only for [snapshots](https://github.com/syndesisio/syndesis/blob/master/app/s2i/copy_mvn_repo.sh#L17-L24)

**Comment by squakez** [comment]
Thanks @lburgazzoli. In any case I understand we should better dedicate efforts to move towards Camel-K instead. I've just seen @nicolaferraro is exactly working on improvements to make connectors development smoother. What do you think?

**Comment by lburgazzoli** [comment]
IMHO it make sense to spend some time on this issue as it could be useful even in the context of camel-k where we could use a pre configured s2i image with all the dependencies for the camel-k operator itself, see https://github.com/syndesisio/syndesis/issues/4519

**Comment by squakez** [comment]
Good to know then. I'll try to dedicate some time and ping you and the rest of the team if need some help/advice.

**Comment by squakez** [comment]
The problem of the Docker file is that it cannot make any use of intermediate layer caching because the [presence of the local copy of SNAPSHOT dependencies](https://github.com/syndesisio/syndesis/blob/master/app/s2i/src/main/docker/Dockerfile#L10).

In order to prevent this we can add a stable previous version generated project whose goal is to warm up and cache all integration dependencies. This project won't change during the rest of development, so the intermediate docker layer will be cached and always available at image build time.

The real project will take care to include actual version local SNAPSHOT dependencies (that are going to change by the local compilation) plus introduce any new needed dependency or override the one introduced by the previous `mvn verify` step.

The first time the image is built there won't be any change, but, after second time Docker builder will execute the second project install only getting all dependencies by the intermediate cached layer.

@lburgazzoli, @nicolaferraro,
This is a preview of the change I am going to submit through PR if you are fine with this approach: https://github.com/syndesisio/syndesis/compare/master...squakez:feature/6100?expand=1 - I've managed to reduce build time from 5 minutes to 2 minutes locally.

The only thing I don't have enough clarity is if we can set the previous image generator version by CICD when we release a stable version. Any idea with that?

**Comment by squakez** [comment]
Just an head up after receiving some comments on the solution from @nicolaferraro. I'm working on some script to identify the useless dependencies brought in by the first caching project (ie, the syndesis previous versions dependencies). So far I managed to get a diff like the below that I am going to use to feed a cleaning action and delete the useless dependencies:

```
[jboss@5995102a5758 ~]$ diff project-cache-dependency-log-reduced project-dependency-log-reduced 
136,141d135
< com.atlassian.event:atlassian-event:jar:3.0.0:compile
< com.atlassian.httpclient:atlassian-httpclient-api:jar:2.0.0:compile
< com.atlassian.httpclient:atlassian-httpclient-library:jar:2.0.0-m1:compile
< com.atlassian.jira:jira-rest-java-client-api:jar:5.1.2-2bd0a62e:compile
< com.atlassian.jira:jira-rest-java-client-core:jar:5.1.0:compile
< com.atlassian.sal:sal-api:jar:3.0.7:compile
185,187d178
< com.sun.jersey:jersey-client:jar:1.19:compile
< com.sun.jersey:jersey-core:jar:1.19:compile
< com.sun.jersey:jersey-json:jar:1.19:compile
216,217d206
< io.atlassian.fugue:fugue:jar:3.0.0:compile
< io.atlassian.util.concurrent:atlassian-util-concurrent:jar:4.0.1:compile
242,285c231,274
< io.syndesis.common:common-model:jar:1.7.9:compile
< io.syndesis.common:common-util:jar:1.7.9:compile
< io.syndesis.common:jaeger-spring-boot-starter:jar:1.7.9:compile
< io.syndesis.connector:connector-activemq:jar:1.7.9:compile
< io.syndesis.connector:connector-amqp:jar:1.7.9:compile
< io.syndesis.connector:connector-api-provider:jar:1.7.9:compile
< io.syndesis.connector:connector-aws-s3:jar:1.7.9:compile
< io.syndesis.connector:connector-aws-sns:jar:1.7.9:compile
< io.syndesis.connector:connector-aws-sqs:jar:1.7.9:compile
< io.syndesis.connector:connector-box:jar:1.7.9:compile
< io.syndesis.connector:connector-dropbox:jar:1.7.9:compile
< io.syndesis.connector:connector-email:jar:1.7.9:compile
< io.syndesis.connector:connector-fhir:jar:1.7.9:compile
< io.syndesis.connector:connector-flow:jar:1.7.9:compile
< io.syndesis.connector:connector-ftp:jar:1.7.9:compile
< io.syndesis.connector:connector-gmail:jar:1.7.9:compile
< io.syndesis.connector:connector-google-calendar:jar:1.7.9:compile
< io.syndesis.connector:connector-google-sheets:jar:1.7.9:compile
< io.syndesis.connector:connector-http:jar:1.7.9:compile
< io.syndesis.connector:connector-irc:jar:1.7.9:compile
< io.syndesis.connector:connector-jira:jar:1.7.9:compile
< io.syndesis.connector:connector-kafka:jar:1.7.9:compile
< io.syndesis.connector:connector-knative:jar:1.7.9:compile
< io.syndesis.connector:connector-kudu:jar:1.7.9:compile
< io.syndesis.connector:connector-log:jar:1.7.9:compile
< io.syndesis.connector:connector-mqtt:jar:1.7.9:compile
< io.syndesis.connector:connector-odata:jar:1.7.9:compile
< io.syndesis.connector:connector-rest-swagger:jar:1.7.9:compile
< io.syndesis.connector:connector-salesforce:jar:1.7.9:compile
< io.syndesis.connector:connector-servicenow:jar:1.7.9:compile
< io.syndesis.connector:connector-sftp:jar:1.7.9:compile
< io.syndesis.connector:connector-slack:jar:1.7.9:compile
< io.syndesis.connector:connector-sql:jar:1.7.9:compile
< io.syndesis.connector:connector-support-processor:jar:1.7.9:compile
< io.syndesis.connector:connector-support-util:jar:1.7.9:compile
< io.syndesis.connector:connector-support-verifier:jar:1.7.9:compile
< io.syndesis.connector:connector-telegram:jar:1.7.9:compile
< io.syndesis.connector:connector-timer:jar:1.7.9:compile
< io.syndesis.connector:connector-twitter:jar:1.7.9:compile
< io.syndesis.connector:connector-webhook:jar:1.7.9:compile
< io.syndesis.extension:extension-api:jar:1.7.9:compile
< io.syndesis.integration:integration-component-proxy:jar:1.7.9:compile
< io.syndesis.integration:integration-runtime-springboot:jar:1.7.9:compile
< io.syndesis.integration:integration-runtime:jar:1.7.9:compile
---
> io.syndesis.common:common-model:jar:1.8-SNAPSHOT:compile
> io.syndesis.common:common-util:jar:1.8-SNAPSHOT:compile
> io.syndesis.common:jaeger-spring-boot-starter:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-activemq:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-amqp:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-api-provider:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-aws-s3:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-aws-sns:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-aws-sqs:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-box:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-dropbox:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-email:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-fhir:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-flow:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-ftp:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-gmail:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-google-calendar:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-google-sheets:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-http:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-irc:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-kafka:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-knative:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-kudu:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-log:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-mongodb:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-mqtt:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-odata:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-rest-swagger:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-salesforce:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-servicenow:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-sftp:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-slack:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-sql:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-support-processor:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-support-util:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-support-verifier:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-telegram:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-timer:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-twitter:jar:1.8-SNAPSHOT:compile
> io.syndesis.connector:connector-webhook:jar:1.8-SNAPSHOT:compile
> io.syndesis.extension:extension-api:jar:1.8-SNAPSHOT:compile
> io.syndesis.integration:integration-component-proxy:jar:1.8-SNAPSHOT:compile
> io.syndesis.integration:integration-runtime-springboot:jar:1.8-SNAPSHOT:compile
> io.syndesis.integration:integration-runtime:jar:1.8-SNAPSHOT:compile
315c304
< org.apache.camel:camel-jira:jar:2.21.0.fuse-740038:compile
---
> org.apache.camel:camel-jackson:jar:2.21.0.fuse-740038:runtime
318a308
> org.apache.camel:camel-mongodb3:jar:2.21.0.fuse-740038:runtime
352d341
< org.apache.httpcomponents:httpasyncclient-cache:jar:4.1.3:compile
354d342
< org.apache.httpcomponents:httpclient-cache:jar:4.5.6:compile
358d345
< org.apache.httpcomponents:httpmime:jar:4.5.6:compile
376,380d362
< org.codehaus.jackson:jackson-core-asl:jar:1.9.12:compile
< org.codehaus.jackson:jackson-jaxrs:jar:1.9.12:compile
< org.codehaus.jackson:jackson-mapper-asl:jar:1.9.12:compile
< org.codehaus.jackson:jackson-xc:jar:1.9.12:compile
< org.codehaus.jettison:jettison:jar:1.3.8:compile
404a387
> org.mongodb:mongo-java-driver:jar:3.4.3:compile
435c418
< org.twitter4j:twitter4j-core:jar:4.0.7:runtime
---
> org.twitter4j:twitter4j-core:jar:4.0.7:compile
```
As expected the majority are 1.7.9, so I guess this may solve the possible libraries additional overhead.

**Comment by squakez** [comment]
I've simplified the approach in order to have a neater procedure. I finally am able to create a local cache with needed dependencies (no need to get previous version). With the first step we download the dependencies and at first execution we do cache the docker intermediate layer. The second step is taking care of refreshing the latest syndesis dependencies (invalidating docker cache) and install the base project.

Local cache is invalidated if a `mvn clean` is performed.

Please have a look and let me know if you have any further comment to improve before PR: https://github.com/syndesisio/syndesis/compare/master...squakez:feature/6100?expand=1

**Comment by nicolaferraro** [comment]
Hi @squakez, I've looked quickly at your branch. I think the idea of a two step build with first step skipped if already done is nice.
I can't follow completely the details, I expected some maven commands in the middle but can't find them. Why don't you open a "wip" PR so I can comment on the code directly?

I'd push more with this approach. I think you can pre-configure the "m2.cache" not only with syndesis resources but also with their dependencies, obtained maybe with a "mvn copy:dependencies" command so you never download them from maven but use always your local artifacts.
