### ISSUE TITLE
POC a GraphQL endpoint to assist in reducing API response sizes for some FE uses cases.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#6202]
## This is a...
<pre><code>
[X] Feature request
</code></pre>

## Description
POC a GraphQL endpoint to assist in reducing API response sizes for some FE uses cases.

**Comment by chirino** [comment]
I've got a branch somewhere that I can revive that had a GraphQL endpoint added to syndesis server.  Need a good FE use case where we can apply it to.

**Comment by gashcrumb** [comment]
So I think the current pain point that I'm seeing is actually right on the integration list page.  The UI itself shows not much information, but fetches *loads* of data from the server.  And when an integration is transitioning between states, the UI gets change events which trigger more frequent data fetches so that the user sees something happening.  I think this plays a role in increasing server load for sure, especially if multiple users happen to be sitting on the same page.  The UI debounces these change events so that not every change event triggers a fetch at least.

Another one is the integration detail page, I think the deployment data returned is much more than is needed.  Also there seems to be a lot of change events with regards to integration deployments that I think we filter on on the UI side to try and not make too many requests on the server.

**Comment by gashcrumb** [comment]
A good reference probably too for the above -> https://github.com/syndesisio/syndesis/issues/5989

the issue itself is probably more at the persistence layer, but even the responses for connections is kinda big, I think on the list page these requests are made to get all the icons so we can display them.

**Comment by zregvart** [comment]
This will not solve issues like #5989 in which you will find an example of a query running for nearly 10 minutes. I don't think that it is possible to implement GraphQL abstraction over jsondb that will not exhibit such issues for non trivial load on the database.
