### ISSUE TITLE
server/endpoint/pom.xml issue with org.json:json dependency

### ISSUE THREAD

**Issue by cunningt** [syndesisio/syndesis#6292]
## This is a...

Trying to build syndesis:master and getting the following in server/endpoint.

```
[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (basepom.default) @ server-endpoint ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.json:json:jar:20140107:compile
[INFO] ------------------------------------------------------------------------
```
```
[INFO] Server :: Inspector ................................ SUCCESS [ 13.996 s]
[INFO] Server :: Credential ............................... SUCCESS [ 24.949 s]
[INFO] Server :: Endpoint ................................. FAILURE [ 16.563 s]
```

I'm not sure how to respond to this - if I exclude org.json:json from openshift-client (which is bringing it in), then I get an error 

```
[INFO] --- dependency-management-maven-plugin:0.11:analyze (basepom.default) @ server-endpoint ---
[ERROR] Exclusions must be removed for managed dependency io.fabric8:openshift-client:jar
```

If I add a dependency to server/endpoint for org.json:json, I get a complaint that android-json has classes that are duplicated from org.json:json.

**Comment by christophd** [comment]
`io.fabric8:openshift-client:jar` must be declared somewhere in a `dependencyManagement` section, too. You need to add the exclusion there to avoid the 2nd error.

**Comment by zregvart** [comment]
Used and undeclared dependencies are dependencies that the source code depends on, i.e. compilation of the source code would fail if that dependency were to be removed. If we do indeed depend on this dependency then we need to declare it in the `compile` scope.

When excluding a transient dependency we need to exclude it at the point of declaring the dependent dependency that depends on it i.e. in the `dependencyManagement` section where the transient dependent was declared. This way the exclusion is propagated throughout rather than being local to a module and have the same issue appear in another module that might depend on the dependent dependency.

The odd thing perhaps is that this is not an issue that CI corroborates, from a one of the [latest builds on master](https://circleci.com/gh/syndesisio/syndesis/91332):

```
[INFO] --- dependency-management-maven-plugin:0.11:analyze (basepom.default) @ server-endpoint ---
[INFO] No dependency management issues found
[INFO] 
```

**Comment by cunningt** [comment]
I think the reason that I see this and CI doesn't is that I'm seeing it in the dev build, where we are using a newer version of kubernetes-client.

**Comment by zregvart** [comment]
Perhaps we should start by aligning the kubernetes client versions.
