### ISSUE TITLE
OData connector updates null values with Filter old results turned on

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#6294]
See also **https://issues.jboss.org/browse/ENTESB-11395**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When doing simple integration OData (Read) -> Data Mapper -> OData (Update) 
![image](https://user-images.githubusercontent.com/46523434/62276567-a0334080-b444-11e9-9383-f914a214b283.png)
with this configuration:
![image](https://user-images.githubusercontent.com/46523434/62276606-b5a86a80-b444-11e9-8110-727a812d7531.png)
and updating other entity then the one specified in OData read configuration, the first run of integration run as supposed. BUT the second run updates with null values. See below:
![image](https://user-images.githubusercontent.com/46523434/62276459-62361c80-b444-11e9-831d-7c18f57a6df3.png)

**Comment by jsafarik** [comment]
When I tried to turn the `Filter old results` off, everything works as supposed.

**Comment by heiko-braun** [comment]
@jsafarik Does the above act as a workaround?

**Comment by jsafarik** [comment]
@heiko-braun It does not. turning the `Filter old results` on should avoid processing an entity more then 1 time, disabling this enables processing of entities every time the integration runs (even when the entities have already been processed), which in some cases may not be favourable.

**Comment by phantomjinx** [comment]
@jsafarik 
So looking at this in some detail...

Both Olingo4Consumer and Olingo4Producer having the filtering capability.
Oling4Consumer (upstream)
- Could be [fixed](https://github.com/apache/camel/blob/master/components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java#L102) so that if the result has been filtered then [polling stops](https://github.com/apache/camel/blob/camel-2.21.x/camel-core/src/main/java/org/apache/camel/impl/ScheduledPollConsumer.java#L177).

Olingo4Producer
- Cannot see how to stop the [exchange](https://github.com/apache/camel/blob/master/components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Producer.java#L67) if two messages are sent with the same predicate and the second is filtered out.

In both cases, the read customizer ([From](https://github.com/syndesisio/syndesis/blob/master/app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataReadFromCustomizer.java) & [To](https://github.com/syndesisio/syndesis/blob/master/app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/ODataReadToCustomizer.java)) is initiated after the OData-Read component & both default to their [Abstract class parent](https://github.com/syndesisio/syndesis/blob/master/app/connector/odata/src/main/java/io/syndesis/connector/odata/customizer/AbstractODataCustomizer.java#L93). As can be seen, if the body is null then an empty json document is returned, the equivalent of an empty json type message.

Therefore, at this stage I am not sure that the OData-Read is actually resulting in anything that is incorrect. An empty message is passed to the next component in the route.

So I have questions to try and answer:
- Can the data mapper make a mapping between an empty json object using a schema in order to generate an object of the form { MiddleName: null } ??
- Other than the polling in the Consumer code above, is it generally possible to stop an exchange message if its empty ??

**Comment by jsafarik** [comment]
I wanted to try a workaround by using a Basic filter, which didn't work because of https://github.com/syndesisio/syndesis/issues/6326. 

This is not (from point of a user) a optimal solution even if the workaround with `Basic filter` worked, but if there would not be another way to fix this, then it should be documented (best would be to include this in info about `Filter old results` in the OData read action) to use a Basic filter to stop the integration when the read results is just empty json.

![image](https://user-images.githubusercontent.com/46523434/62604695-df580a80-b8f8-11e9-97b8-2976ae684233.png)

From this screenshot it seems that the read data is indeed an empty json and data mapper is able to construct the key:value pairs using the provided schema of the processed entity.

**Comment by jsafarik** [comment]
So I've tried some more things and this is happening only when the reading is done including specification of `Entity Key Predicate`. When reading whole collection, the integration stops at the beggining as supposed. It would be super awesome to have this behavior the same when reading both the collection of entities as well as just one entity using `Entity Key Predicate`. I have to yet try to not specify the `Entity Key Predicate` but read just one entity using a query (I guess it should work because the one entity should be in array and not just a JSON object, but will confirm just in case..).

**Comment by phantomjinx** [comment]
@jsafarik 
Yes that is correct. If you look at [Olingo4Component](https://github.com/apache/camel/blob/master/components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java#L102), an empty entity collection is catered for & returns 0, stopping the polling and returning no messages to the exchange. Sadly, I missed out `result[0] == null` when I added that in which is what happens with a keyPredicate.
So simple to change upstream but obviously will take some time to bring it back around to master.

**Comment by phantomjinx** [comment]
Upstream change that fixes olingo4 consumer
https://issues.apache.org/jira/browse/CAMEL-13861

**Comment by phantomjinx** [comment]
Requires new camel build snapshot to be built and syndesis to have dependency upgraded.

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11395**
