### ISSUE TITLE
Unable to deploy from master due to malformed config.json

### ISSUE THREAD

**Issue by asmigala** [syndesisio/syndesis#6314]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Deploying syndesis from master results in a non-functional UI, only shows the `Something is wrong` page.

As a workaround, one can edit the `syndesis-ui-config` map and editing the `config.json` key there to have `"enabled": 0` instead of just `"enabled:"`

Furthermore, any change to the `syndesis-ui-config` is reverted by the operator, so for the above workaround to actually help, one needs to scale down the operator to 0 first.

**Comment by asmigala** [comment]
> Furthermore, any change to the syndesis-ui-config is reverted by the operator

is this something that needs a separate issue or is that the expected behaviour?

**Comment by zregvart** [comment]
It's the expected behaviour.

With the operator, any changes made to any resource it manages, including the ConfigMaps should be lost by the operator reverting them to the state derived from the Syndesis custom resource. If there's a setting in the ConfigMaps or DeploymentConfigs or anything similar we have the need to change it should be present on the Syndesis custom resource and propagated to the appropriate resource by the operator.

**Comment by mcada** [comment]
@heiko-braun this should be resolved asap as it is blocking all QE automation
