### ISSUE TITLE
[jsondb] Improve performance by adopting a similar storage model as k8s update a whole document, but allow sub resources on the document.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#6444]
## This is a...

jsondb stores its json documents one DB record per json leaf node.  That means large json documents require lots of DB records to represent the document.  Updates of the document are equally troubling because we need to delete all the records for the document first. (to make sure delete leaf nodes that do not exist in the new doc).

Instead we could store the whole sub graphs of the json document in a single record.  This should reduce the load the DB.   We should also support defining that some json documents have sub resources which are stored a a separate record so that frequently modified sub fields do need us to update the larger parent document.

I think we just need a list of regexes or globs which matched against the json paths of the nodes being updated to identify which paths are the roots that gets stored as whole documents.

Examples: 
* match `/*/*` because we want `/integration/i777`, `integration/i778`, and `connection/333` all to be separate json records.
* match `/integration/*/status` because we want the status object under all integrations to be stored a seperate json document from the parent document.

This would only affect how jsondb store it's data in the DB.  It would not affect any of the current access APIs to access, delete, or update it's modes.  So you could post update to direct json document leafs.  The update logic would need to figure out which is the deepest root document that it needs to update.

**Comment by phantomjinx** [comment]
Linked to #6203

**Comment by phantomjinx** [comment]
After creation of 1 integration:

```
PATH                        Records
/integrations                   274
/integration-bulletin-boards      9
/connection                      53
/connectors                    9424 (already present)
/connector-templates            318 (already present)
-----------------------------------
                              10078

PATH (Excluding child paths listed)                                          Records
/integrations/:i-Lmz2ZXFGtg39qcKbpLmz/...                                         59
/integrations/:i-Lmz2ZXFGtg39qcKbpLmz/flows/[0/steps/[0/connection/...            11       
/integrations/:i-Lmz2ZXFGtg39qcKbpLmz/flows/[0/steps/[0/connection/connector     204
------------------------------------------------------------------------------------
                                                                                 274

**Comment by phantomjinx** [comment]
Successfully reached the point of traversing json objects to see if they contain a path that matches a given pattern. If so, I remove the json object and replace with a stub object containing a target url. So couple of things:

1. Is it the case that only objects with an existing id attribute will ever be separated out into their own json record? If not, then what would be the recommended method for generating new ids for the path/target url of the json record?

2. The [getInsertBatch()](https://github.com/syndesisio/syndesis/blob/master/app/server/jsondb/src/main/java/io/syndesis/server/jsondb/impl/SqlJsonDB.java#L426) method inside SqlJsonDB assumes an insert but for the json records to be broken out I find myself a [layer lower](https://github.com/syndesisio/syndesis/blob/master/app/server/jsondb/src/main/java/io/syndesis/server/jsondb/impl/JsonRecordSupport.java#L132) (only have the JsonConsumer). In that case rather than explicitly trying to test for the existence of paths/json records prior to the insert, any objections to using an [upsert](http://www.postgresqltutorial.com/postgresql-upsert/) instead?

@chirino @zregvart

**Comment by zregvart** [comment]
I really don't think that JSONDB merits any further investment. I think we should migrate to a relational database schema.

**Comment by phantomjinx** [comment]
Closing as no further work to be sought.
