### ISSUE TITLE
cannot import an integration from another instance

### ISSUE THREAD

**Issue by pwright** [syndesisio/syndesis#6466]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Documentation issue or request
</code></pre>

## Description

I tried to import an integration that was exported from an instance owned by a colleague.
It never got past 'Assembly' stage (2nd time I left it for a few hours)

1. is this a known restriction?
2. how should i debug?

**Comment by zregvart** [comment]
Hi thanks for reporting this. Did you notice any warnings issued after the import or on the screens opening the integration.

What usually happens is that the passwords for connections that are embedded within the integration export need to be re-entered after the import. This is due to the encryption of those passwords that doesn't allow the secrets of the integration to traverse instances.

You can go to the OpenShift console and check the integration build pod for errors or if the build succeeded the integration pod's logs to look for errors.

**Comment by finp** [comment]
@zregvart  that makes sense, so I do have Slack api and token in a connection. 
If I just update the keys and save the connection, the integration should rebuild and work?

**Comment by zregvart** [comment]
@finp yes, you can update the connection, and re-publish, you might get an warning that you need to edit and save the integration before publishing, I'm not exactly sure when is this needed but something to look out for.

**Comment by finp** [comment]
thanks, again @zregvart 

Given that there are dozens of instructions (but not nothing about keys) **after** you click Import [1], I wonder if the button is mislabeled? 
My impression is that importing is a subtle art, and that **Start Import** would reflect the process better and prompt idiots like me to check the docs for the full instructions ;)

[1] https://github.com/syndesisio/syndesis/blob/master/doc/integrating-applications/topics/p_importing-integrations.adoc

NOTE: Still haven't successfully exported/imported
