### ISSUE TITLE
Simple Syndesis build wipeout everything on minishift

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#6490]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I do a normal build of Syndesis e.g. using `syndesis build -f --clean` and when I am connected to a local minishift project at that time (`oc login -u developer`) the build wipeout everything I have on that minishift project.

You end up having just the operator deployment and nothing else in that project. Before that I had a full Syndesis installation with server, meta, db, ui, ... running on that minishift.

**Comment by phantomjinx** [comment]
So executed the command today with fully populated syndesis project (on minishift).
- Confirm that all original image instances are still present
- New syndesis operator image built and instance now running

The latter is perhaps interesting in that it seems a little surprising that `syndesis build` should cause an effect on the syndesis project since the command is wholly local concerning compiling source files. When `-i` is added then that is an explicit request to turn the compilation into images and upload them but not sure there sure be anything implicit about the `syndesis build` that causes any interaction with the operator or any other image.

**Comment by phantomjinx** [comment]
So looking at the build script, the [do_operator](https://github.com/syndesisio/syndesis/blob/master/tools/bin/commands/build#L187) function does require building on openshift rather than just a local compile. So that is at least expected.
