### ISSUE TITLE
Incorrect font type and styling for definition list on multiple pages 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#6535]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Not sure how this happened, but the label names in the following screenshots should be in Open Sans and without italic styling. 

Seems like this is introduced from [this commit](https://github.com/syndesisio/syndesis/commit/b8ecfbffce4b9b4c7a5cbdfb80680ee5b10cd44b). 

cc: @seanforyou23 @mcoker @gashcrumb 

![image](https://user-images.githubusercontent.com/24943812/64373944-c1adbc00-cff0-11e9-9049-31ee5288fafe.png)
![image](https://user-images.githubusercontent.com/24943812/64374003-e6099880-cff0-11e9-8d8b-026137492bae.png)
![image](https://user-images.githubusercontent.com/24943812/64374185-46003f00-cff1-11e9-9b47-74fbaaff87e1.png)

**Comment by mcoker** [comment]
Hey @elvisisking, I looked into this and looks like the offending lines are here - https://github.com/syndesisio/syndesis/blob/master/app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewOutputToolbar.css#L27-L38

Without scoping those styles to a class that's unique to this page (ie, `.view-output-toolbar .pf-c-content dt {}`) or adding a class to the `dt` you want to style (ie, `.view-output-toolbar__titleElementToStyle`) and styling that class intead of the global `.pf-c-content dt`, these styles are going to apply to any use of `.pf-l-toolbar`, `.pf-c-content dl`, and `.pf-c-content dt` across the whole app.

I'm unfamiliar with data virtualization and am not sure how to find this toolbar in the UI to verify the current behavior and implement a fix. Can you point me in the direction of how to bring this up in the UI? And are there any designs to reference for how this part of the UI should ideally look? Alternatively if my explanation above made sense and you have a good idea of how to fix this, you can grab this one and refactor that bit of CSS so that the declarations only apply to the view output toolbar and don't impact other parts of the app.

**Comment by elvisisking** [comment]
That does make sense @mcoker. Actually the `ViewOutputToolbar` is no longer used and should be removed. I'll take care of that. Thanks.

**Comment by mcoker** [comment]
Thanks @elvisisking!

**Comment by elvisisking** [comment]
Closing as the PR has been merged into master branch.
