### ISSUE TITLE
Create Syndesis Standalone

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#6556]
This would be a downloadable zip file that people can download and then startup as a standalone Java process. It would run all design time components. It would facilitate the adoption in the Community as it would be much simpler to get going.

WIP: https://github.com/KurtStam/syndesis/tree/standalone/app/standalone

**Comment by KurtStam** [comment]
- [ ] Take care of authentication running w/o auth proxy, setting the headers
- [ ] Switching to H2 DB with PostgreSQL compatible mode
- [ ] Adding correct application.yml configuration to both server & meta process
- [ ] Have the server manage the meta process (startup/restart/shutdown)
- [ ] No metrics
- [ ] Noop for OpenShift calls
- [ ] Run on random ports?

**Comment by lburgazzoli** [comment]
I feel this issue need a little bit more work in term of defining the scope, the success criteria and some UX consideration as to me those are not really clear i.e.:

- a user looking for an editor would probably go for something simpler, like a VSCode extension and the possibility to store its integration files and projects in a source core repository (see [bpmn-vscode-extension](https://medium.com/kie-foundation/bpmn-vscode-extension-released-alpha-1782ddaa2a4e)) with the ability to deploy such integration straight to k8s 
- a user willing to test syndesis would need to have a k8s cluster somewhere in any case to run the integrations so it would probably better to invest in an easier way to install Syndesis on k8s than having a partial platform running off-line 
- as a developer I would certainly not download a zip as a getting starter experience :)

**Comment by KurtStam** [comment]
@lburgazzoli. This feature has been deemed critical for the Syndesis community efforts. This work will have no direct relance to the product relevance, but it will allow people to onboard with Syndesis w/o having to install cloud infrastructure. Success is defined by being able to have the UI be functional at a bare minimum level. The Syndesis community agreed on this. You're welcome to join the community meetings.

**Comment by Delawen** [comment]
Duplicates  #6200 ?

**Comment by lburgazzoli** [comment]
don't think so, this issue is about running without k8s at all

**Comment by Delawen** [comment]
Oh, right! it is even more decoupled. Good.

**Comment by kevinmershon** [comment]
+💯  for this. Syndesis looks quite promising but requiring it to be deployed on OpenShift is **greatly** holding it back from adoption.

As a non-devops engineer looking to trial Syndesis on GCP for a replacement/upgrade for an ETL pipeline, I've ran into so many problems at this point that I'm ready to recommend against Syndesis in our org. I wanted to put together a 5-minute realworld demonstration of an FTP scrape to DynamoDB pipeline, but I have to run it in GCP because of our infrastructure firewalls. But I can't, because after 3 days of researching and trial/error, I've learned it requires a $50/month OpenShift license to Red Hat on top of cloud server costs, that I do not have and cannot get authorization at my corporate level to obtain.
