### ISSUE TITLE
Should we disable dependency checks?

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#656]
Seems to have broken a perfectly valid [build of `master`](https://circleci.com/gh/syndesisio/syndesis/1497). If we disable it perhaps #643 makes more sense. And we can look into having dependency checks run only if `pom.xml`s are changed?

```
[INFO] --- maven-dependency-versions-check-plugin:2.0.4:check (default) @ runtime ---
[INFO] Checking dependency versions
[INFO] artifact org.seleniumhq.selenium:selenium-support: checking for updates from central
./app/build.sh: line 337: echo: write error: Broken pipe
Too long with no output (exceeded 10m0s)
```

**Comment by rhuss** [comment]
All for disabling it now. This will probably harm us when we switch on later (because we have to fix stuff *then*) but maybe let's have just a good time with a smooth CI for some days ;-)

Also, I guess before we should tackle dependencies checks we should tackle other basepom checks in connector and runtime (I think) where they are stilled switched on in the pom.xml

**Comment by zregvart** [comment]
The check is now disabled, lets see if we have the need to enable it again and then work with any issues that arise.

https://github.com/syndesisio/syndesis/blob/cecfaa3b26f5c68c930d14f5b0d7b4f2103000bc/app/pom.xml#L71
