### ISSUE TITLE
Env.ROUTE_HOSTNAME is missing by operator eject

### ISSUE THREAD

**Issue by lgarciaaco** [syndesisio/syndesis#6591]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When the the syndesis binary is called with eject command, `.Env.ROUTE_HOSTNAME`  is missing and resources using it are not generated properly:
```
./dist/linux-amd64/operator eject --operator-config build/conf/config.yaml | grep 'no value'
        https://<no value>\ncache:\n  cluster:\n    name: SyndesisCluster\n  max:\n
      host: todo-<no value>
```

**Comment by lgarciaaco** [comment]
@asmigala after merging, please make sure the CR contains the variable and that should make it.
```
[lgarciaa@lgarciaa operator]$ oc get syndesis
NAME      PHASE      VERSION
app       Starting   latest
[lgarciaa@lgarciaa operator]$ oc get syndesis -o yaml | grep routeHostname
    routeHostname: syndesis-syndesis.apps.lgarcia.rhmw-integrations.net
[lgarciaa@lgarciaa operator]$ ./dist/linux-amd64/operator eject --app app --operator-config build/conf/config.yaml | grep 'no value'
[lgarciaa@lgarciaa operator]$
```

**Comment by asmigala** [comment]
@lgarciaaco how do I specify the CR when running the operator as a binary (not in openshift)?

**Comment by lgarciaaco** [comment]
you have to have connection to an openshift cluster when running with `--app`. In the selected namespace create a syndesis CR.

**Comment by asmigala** [comment]
I see, so there's no way to generate the resources locally, without openshift connection? 

If you're not cluster admin, you cannot create the CRD and thus cannot deploy the CR needed to eject.

**Comment by lgarciaaco** [comment]
@asmigala what is the use case yo have in mind? This is not a replacement for the templates we used as installation method before. This is for "hopefully" a one time installation in our eval clusters, where if needed we can afford to manually change those values.

**Comment by avano** [comment]
it was originally my intention to use eject to deploy images from multiple sources - some from docker hub and some for quay (for PR jobs, perhaps until https://issues.jboss.org/browse/ENTESB-11623 is done in some way)

If it is really an "one time installation" then it is okay-ish, however if it should be another installation option, then it should be more polished (cc @heiko-braun)

just FYI, here is what needs to be done to successfully deploy syndesis with the eject resources:

1) eject resources in some yaml file
2) substitute `host: null` and `<no value>` for your desired route in the yaml file
3) create `syndesis-oauth-client` because it is missing in the resources
4) grab token from `oc sa get-token syndesis-oauth-client` and substitute it in the resources for the value in `OPENSHIFT_OAUTH_CLIENT_SECRET=...` and `--client-secret=...`
5) create the resources from the yaml file

**Comment by lgarciaaco** [comment]
@avano this is definitely not another installation option, we are trying to shrink the installation methods not to expand them :-). But if you find long tern benefits from refining this solution, I am more than happy to improve it so it fits your needs guys Lets talk about it next week.

**Comment by lgarciaaco** [comment]
`eject` is replaced by `install standalone`. This issue is obsolete, closing

https://github.com/syndesisio/syndesis/pull/6669
