### ISSUE TITLE
Start Spreading the word about Syndesis

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#6594]
* a. Which conference should we target?
* b. Do local events - reach out internal and external
* c. Blogs
* d. Develop Content: QuickStart and Real World Scenario
* e. Developer Handbook maybe stale
* f. Adopt Camel Website Infrastructure for the website?
* g. Publish Syndesis Docs on Syndesis

**Comment by Delawen** [comment]
I assigned this myself but I would appreciate help on the Developer Handbook, checking the infrastructure for the website and Real World Scenarios for this.

**Comment by Delawen** [comment]
List of conferences that may be of interest (will keep this comment updated with more findings):

 * [FOSDEM](https://fosdem.org): Open Source focused. Good place to find other developers.
 * [CCC](https://www.ccc.de/en/): Huge hacking conference, though not sure we fit there.
 * [FullStack Fest](https://2019.fullstackfest.com/): Latest trends in technology in general.
 * [Libre Planet](https://libreplanet.org/2019/): The conference from the FSF.

Most of my references are related to geospatial, which I will keep out of the list for the moment. So any more suggestions are welcome.

**Comment by Delawen** [comment]
About local events and blogs, do we write/have some guidelines/rules or do we do it with our personal style? 

Meaning: do we want to have a marketing/design plan to do homogeneous reaching? 
Homogeneous reaching may sound like business, but could be useful to build the sense of community. It's not clear which is best for open source projects.

**Comment by kahboom** [comment]
@Delawen - In a sense I think it makes sense to approach like a nonprofit org, they still need to have marketing and branding to bring awareness. We do have some of this in place already, but I can put together some branding guidelines (color palette, logo) and presentation templates if you'd like, maybe throw them in a Google Drive dir or even on the website? Maybe a simple internal doc or spreadsheet for tracking the actual efforts and their impact.

As for the Developer Handbook, I don't know how everyone feels about migrating the docs to the website repo if I can be sure that asciidoc can work fine on there (that was the big apprehension before), or if we still are considering setting up a hook that pushes the changes from the syndesis repo to the website repo. I was discussing this with Tova as well, because there was a similar consideration for the user docs, but that's for another discussion I think.

I have this link on my website for a website that has open source and crowdfunded conferences, if it could be helpful: https://confs.tech/

**Comment by Delawen** [comment]
For presentation templates, they are very helpful, although... I use revealJS and I guess other people will use other libraries. Try to be as open as possible (is the way that I have had less problems with on different environments).

**Comment by Delawen** [comment]
> I have this link on my website, it's a directory that lists open source and crowdfunded conferences, if it could be helpful: https://confs.tech/

Love this!

**Comment by kahboom** [comment]
Keep this open until we decide on a way to track progress.
