### ISSUE TITLE
Dependabot PRs out of control 

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#7197]
@zregvart we have over 30 PRs now. This is out of control and will screw with getting people on board doing reviews. How do we act on these PRs and if we can't act how do we document that so we can close them?

**Comment by gashcrumb** [comment]
I was gonna start going through those UI ones tomorrow.  I'd say it'd be good if folks maybe assigned these PRs and kinda take ownership of getting 'em merged ultimately, that's probably what I'll do as I go through the ones targeting `ui-react`

**Comment by gashcrumb** [comment]
It would be kinda nice if dependabot could batch it's updates into one PR but I had a peek at the site and I dunno if it can work that way.

**Comment by gashcrumb** [comment]
So the UI ones all had built fine, I opted to merge them as most of those were transitive dependencies.  There's a bunch for various Java dependencies that have failed to build.  I'd say the next step on all of those is to investigate the build failures, either re-run the checks because it's just some temporary failure, or there's some code changes required because it's a direct dependency change and introduced some incompatibility.  I'd say again the best way to treat these dependabot PRs is to treat them just like issues, assign an owner to steward the PR and make the changes to get it merged.

**Comment by zregvart** [comment]
My take is that the dependabot is not the issue here, if the build took much less time (say 5-10min) we would hardly notice those. The pull requests created by the dependabot are nicely labeled, and that allows you to filter them out:

[is:pr is:open sort:updated-desc -label:dependencies ](https://github.com/syndesisio/syndesis/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+-label%3Adependencies+)

**Comment by zregvart** [comment]
The benefit of staying up to date with dependencies, especially with respect to security ([open](https://github.com/syndesisio/syndesis/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Asecurity)/[closed](https://github.com/syndesisio/syndesis/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3Asecurity+is%3Aclosed)) updates should be of paramount interest to the project.

**Comment by KurtStam** [comment]
@zregvart yes I agree with all of that, however in the meantime it's still an issue. Less now that a lot of them have been taken care of but at a minimum we should comment on the PR as to what needs to happen for them to be fixed, and if the fix is going to take a long time then we should be able to park the issue and open a GH issue.

**Comment by gashcrumb** [comment]
Aren't PRs just issues with a special flag at the end of the day?

Anyways, yeah, I've 3 now for the UI that are non-trivial upgrades requiring additional work and have commented on one of them what's kinda required.

**Comment by zregvart** [comment]
Anything actionable that we can do here? Otherwise I'd move this discussion over to the Google group?
