### ISSUE TITLE
Reduce UI Third-Party Dependencies

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis#808]
A few we discussed:
- Restangular
- ng-dynamic-forms
- File uploader
- jQuery
- Another one I can't remember atm

This is one component of a larger concern discussed in the retrospective for Sprint 21, which is that of the UI architecture and not having enough time to improve on this area for sustainability.

**Comment by chirino** [comment]
I think each of these third party dependencies need to be analyzed for the pros and cons.

**Comment by chirino** [comment]
And might be a better idea to create one is super dependency to avoid needing an epic

**Comment by deeleman** [comment]
> Another one I can't remember atm

@kahboom I would add jQuery to that list. It's currently used just once to force equal heights on certain PF card widgets and I have not seen that working at all. It's actually absurd to mix up Angular and jQuery in the same project. 

> I think each of these third party dependencies need to be analyzed for the pros and cons

I can only see two reasons why a frontend project built on top of a major SPA framework (being it either Angular, React, Vue, Ember, you name it) might need to resource to a 3rd party library or external dependency to do stuff:

1. The functionality provided by such 3rd party library is neither covered by the framework itself nor by the native API of the underlying scripting language.
2. The functionality is covered by the framework itself but requires a ludicrous amount of code and boilerplate to for achieving the same implementation, or perhaps it just features a too verbose API which turns implementation into a PITA.

In regards of the 4 aforementioned deps, none of those fulfill the criteria above:

### Restangular

Angular comes already with a powerful Http client that allows to model all verbs required for interacting with a REST API thru XHR. In fact, Restangular is built on top of such API with a little nuance though: Restangular makes use of an outdated (and deprecated) version of the API.

Angular introduced a new version of the Http API back in v4.4.5, providing additional features that we will want to leverage in the near future. Restangular's abstraction does not even provide such functionalities and requires an insane amount of code for formalizing a simple Http call. Probs this is also the by-product of the way it was integrated into Syndesis, which turns Restangular injection and execution into a pain. Restangular shines amongst other alternatives when it comes to consume complex REST endpoints imperatively by composition (eg `/users/{user_id}/orders/{order_id}/product/{product_id}/etc`), but we rarely (or even never) have bumped into this case scenario and that functionality can be easily implemented by us with way much less code.

My estimate is that we could build our very own Http wrapper in less than a day and then we'll require no more than 3 days to remove replace Restangular by it.

### jQuery

jQuery is a valuable piece of software when it comes to provide a lean interface to the DOM API with cross-browser polyfills, plus a convenient API for handling HXR calls.

Angular does this already. 

On the other hand it is time to think on application performance and download times, something that adding additional dependencies will impact negatively. Let's spare us from those extra 100Kb and the memory leaks that jQuery can cause.

Removing jQuery and related plugins requires 10 minutes and I'm pretty confident it will have no impact on the app. Should it have it because of that equal-height requirement, we should implement an Angular directive instead, which is the wat to go in these case scenarios for an application like ours (it's needles to say that this is an actual responsibility of the ng-patternfly framework).

### File uploader

I'll spare you the boring parts, but it takes no more than 20 lines of code to put together a full blown up file uploader in Angular, with no plugins. If we implement it along with the new `HttpClient` progress observable properties, we can implement our own customised progress bar or whatever visual widget we fancy. And then we can take advantage of all the goodies from the new [XHR2 API](https://caniuse.com/#feat=xhr2), without having to mind about how updated or supported that library is. Remember than introducing an external dependency also entails having to keep an eye on its roadmap and reported bugs, something that has not been tackled so far.

I need one day to implement our very own multipart uploader, based on native APIs, with upload progress subscriptions.

### ng-dynamic-forms

Building custom dynamic forms in Angular can be quite painful. It is relatively easy to model forms imperatively, but when it comes to add validation and UI config, things might become a bit hairy. That alone would justify the use of this library. I do not hold personal experience on its use, but it seems that @seanforyou23 and @dhirajsb have strong reasons to question its utility. I'd like to research a bit more on the matter to see what do we really need in that sense. I'm pretty confident we can come up with a better replacement if need, being it either another library or our own implementation, customised to suit our particular needs.

This is the only dependency whose phasing out will require a more comprehensive research IMO.

**Comment by deeleman** [comment]
Ah, last but not least, there is something we need to bear in mind from now on: Angular will release a new MAJOR version every 6 months, being Angular v6 already lined up for release on April 2018 as the latest, followed by Angular 7 sometime near October.

3rd party dependencies can hinder our own upgrade roadmap, and we cannot afford that to happen. That's why we were forced to re-engineer the way AtlasMap is built for npm and I also recall that one of the aforementioned dependencies above broke our build when upgrading to Angular 5. 

At the risk fo coming off too strong, let me point out this: If we do not manage to accomplish a fully working release on Angular 5 in the forthcoming months, Syndesis will become a handicapped product by mind-2018 and might be DOA by the end of 2018. 

This is why all this 3rd party dependencies issue should matter so much.

**Comment by kahboom** [comment]
@chirino - Wdyt about me creating an issue for each of these? So that we could potentially phase out the ones that are most obstructive and assess one at a time? Making each of those issues a dependency of this one. Is that what you mean?

@deeleman - I agree and think we don't need the majority of them; they are for fast development, but we do have a lot of features planned for the future (as far as I know), so I do think taking a bit more time to phase some of these out would be worth it. I also think that's why so many people voted for this in the retrospective--each time a backend dev or just anyone in general had to use one it was more hassle than convenience.

**Comment by chirino** [comment]
@kahboom: Yeah we should create individual issues and close this one out.  I personal think epics are bit nasty since they stay open forever and make it harder to track that we really are making progress.

**Comment by chirino** [comment]
@deeleman it will be easier to comment/debate each dependency once they have their own issues.  Please copy your overview for each into those issues. They were great!

**Comment by deeleman** [comment]
Sure.

Just for the record, our brand new [ApiHttpClient](https://github.com/syndesisio/syndesis/pull/837/files#diff-4ba4ed964768bcb2a871b86075766461) allows for interacting with the API through a simple interface including file upload (and observable progress events) functionality.

This will allow for replacing Restangular and NgxFileUploader in the near future.

**Comment by kahboom** [comment]
@deeleman - I've created the individual issues as @chirino suggested. If you get the chance, please copy and paste your comments into those issues (sorry!), so that it's easier to follow each discussion. My fault, I should have done individual issues to begin with.
