### ISSUE TITLE
script extension breaks

### ISSUE THREAD

**Issue by lucamaf** [syndesisio/syndesis#8540]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I imported the script extension https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-extension-script but when trying to build the integration I can see the following in the Build log:

`[ERROR] 'dependencies.dependency.version' for org.codehaus.groovy:groovy-all:jar is missing. @ line 129, column 17
`

and hence the build fails

**Comment by squakez** [comment]
Thanks @lucamaf . Can you confirm you've both built the extension from `master` branch and importing in a syndesis built from `master` branch too? if not, which are the versions?

**Comment by lucamaf** [comment]
built from master and importing in fuse online version 7.6

**Comment by squakez** [comment]
Thanks. Since a few weeks, we've [aligned the branches for syndesis application and syndesis extensions](https://github.com/syndesisio/syndesis-extensions/issues/85). Ideally you should try to build from the same branch you're targeting to use. If I am not wrong, Fuse 7.6 should correspond to upstream 1.9. Can you try the same scenario but building extension from [1.9.x branch](https://github.com/syndesisio/syndesis-extensions/tree/1.9.x/syndesis-extension-script) instead?

**Comment by lucamaf** [comment]
using a specific branch of the code solved the issue, thank you, although not sure which version corresponds to version 7.7, since I still see only branch 1.9.x

**Comment by squakez** [comment]
Yeah, we may have forgotten to add `1.10.x` and `1.11.x`. In any case since extensions had no changes, picking `1.9.x` is good enough. I'll close this issue and open a new one to add the missing branches. Thanks for the feedback!

**Comment by lucamaf** [comment]
sorry but have to reopen, actually the rest of the extensions work fine but the script one is still giving me issues when I use that in an integration:
`[ERROR] 'dependencies.dependency.version' for org.codehaus.groovy:groovy-all:jar is missing. @ line 129, column 17`

**Comment by squakez** [comment]
@lucamaf I've created an issue in extension repository to follow up and solve there.
