### ISSUE TITLE
[Operator] Syndesis install --dev failing

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8743]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Whenever I try to execute a new installation with `syndesis-operator install --dev` after setting up cluster resources and users privileges for developer role, the procedure stuck with the operator pod installed but hanging to scale from 0 to 1. Same if I install `operator` only and `app` separately.

I can run the normal installation procedure `syndesis-operator install` without any problem. In fact, as a workaround, I am using that and then adding an image change trigger such as `oc set triggers dc/syndesis-server --from-image syndesis-server:latest -c syndesis-server` needed for local development purposes.

**Comment by claudio4j** [comment]
The `--dev` flag is for installing `syndesis-operator` only, because it sets the `DEV_SUPPORT=true` flag on `deploy/syndesis-operator`, and changes the internal `syndesis-server.yaml` template to use the latest image, see
https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/generator/assets/infrastructure/04-syndesis-server.yml.tmpl#L23

when the *syndesis/app* CR is installed, it considers the `DevSupport` parameter and sets the image to latest.

So, what I recommend is to `syndesis-operator install` as you did, and later on set `oc set env deploy/syndesis-operator DEV_SUPPORT=true` or set the triggers.

**Comment by squakez** [comment]
Adding an additional finding when trying to install operator via `syndesis-operator install operator --dev`. The error reported is when the cluster try to pull `syndesis-operator:latest`: it does not find it.
