### ISSUE TITLE
How to pass header using DataMapper

### ISSUE THREAD

**Issue by kovel** [syndesisio/syndesis#9206]
How to pass header using DataMapper? After long time of debugging it looks like it filters all headers (custom and standart HTTP).

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

**Comment by zregvart** [comment]
This is not possible within Syndesis right now, see #6286. In general the data shape generated by the connector metadata support should contain every property that the connector supports. You can set a header using an extension, such as [syndesis-extension-manage-headers](https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-extension-manage-headers), but in general adding custom headers to messages might not work, depending on the connector or step creating new messages from scratch or copying them from the existing message on the exchange -- there is no contract around that other than the data shape.

For HTTP, look at the custom API clients and API provider support based on OpenAPI definition, that definition is parsed and any header defined in there will be available through the data shape. For all HTTP interactions we whitelist the headers that are part of the data shape, so that any sensitive data is not exposed or ingested. See [SyndesisHeaderStrategy](https://github.com/syndesisio/syndesis/blob/b5471e2152e43ddf3546a2187b3adb686b5de075/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/util/SyndesisHeaderStrategy.java).

**Comment by zregvart** [comment]
Haven't heard back, considering this answered, please reopen or create new issue.
