### ISSUE TITLE
API connector: canceling wizard on previous error returns to empty page

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#943]
Update: this behaviour happens only if there's an error in wizard, like unrecognized Basic auth issue https://github.com/syndesisio/syndesis/issues/944

Hitting `Cancel` button (+ confirming the modal) should redirect back the list page probably. Currently it goes to empty page for path `customizations/api-connector/create/swagger-connector`.

![screen shot 2018-01-08 at 10 02 32](https://user-images.githubusercontent.com/5637792/34664218-14278df8-f45b-11e7-9751-0bfc77dd84f7.png)

**Comment by deeleman** [comment]
> Update: this behaviour happens only if there's an error in wizard, like unrecognized Basic auth issue #944

Exactly. The issue here is that the missing auth information in the API response is not handled by the auth step, causing the error already reported at #944. The workaround for this will entail ensuring that the components involved degrade gracefully when no proper information is returned. Then we will cater #944 in a separate step.
