### ISSUE TITLE
Cannot modify directly an API client connector on Syndesis

### ISSUE THREAD

**Issue by thnguyendn** [syndesisio/syndesis#9774]
## This is a suggestion in order to improve the process of managing an integration in Syndesis

<pre><code>
[ x ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have already an integration that works correctly in Syndesis as shown below.

![image](https://user-images.githubusercontent.com/12558275/138696847-c68a15c9-d3fb-40ae-8bff-9a56667fcdcd.png)

However, whenever I modify my API client connectors (only minor changes such as adding one new API endpoint or modifying the name of a query parameter inside of an API endpoint), I have to either re-import the new modified API connector completely, or remove the actual one and re-import the new modified one. We cannot easily integrate the new version.

Therefore, I wonder if we could have a new functionality which allows us to modify directly the actual API client connector and takes into account new modifications, in order to avoid this re-import. Regarding the graphical interface, a button labelled "Edit" next to buttons "Details" and "Delete" may be practical...

![image](https://user-images.githubusercontent.com/12558275/138697521-a4470f58-5b88-4dd1-860b-9305d1a2fca2.png)

**Comment by zregvart** [comment]
We don't support changing the API client connector's definition because that could lead to issues within integrations that are already using the custom API connector. For example if a integration uses an operation that was removed or significantly changed so it's no longer compatible with the action that uses it in an integration.
If we go with this and allow changing the definition of custom API connectors we would also need to address that problem. Any thoughts on what should that be?
