### ISSUE TITLE
Syndesis Help hyperlink does not work

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis#998]
The link at the end of "Find out more at Syndesis Help" isn't working.

![dead_link](https://user-images.githubusercontent.com/8625482/34762478-e3fb40b0-f622-11e7-9f48-891514c80717.png)

**Comment by dsimansk** [comment]
@honghuac thanks!

**Comment by zregvart** [comment]
@TovaCohen @fbolton @nichmoore I guess this should point to https://github.com/syndesisio/syndesis/blob/master/doc/developing_customizations/master.adoc do we have a rendered version we should point to?

Not sure if we should be pointing to docs hosted at https://access.redhat.com/documentation/ from Syndesis, that is should this be done only in productized builds and we need to render the documentation from syndesis.io domain?

Simplest solution would be to remove this link, @syndesisio/uxd how horrible would that be?

**Comment by dongniwang** [comment]
I would argue to keep the link and point it to appropriate content since without it, we are kind of leaving users in the dark.

**Comment by fbolton** [comment]
I'm leaning toward the simplest solution of removing the link. Otherwise, it sort of opens a can of worms. We would need to think about:

1. Publishing the docs on the Syndesis community web site (which we don't do right now).
2. How to conditinalize/swizzle URLs between upstream doc targets and product doc targets.

These are things that we probably _should_ start thinking about. But we are probably not going to get them sorted out very quickly.

Hence, my preference for the simplest solution.

**Comment by TovaCohen** [comment]
For TP3, since it is Red Hat only, could we link to the customer portal with this link:

https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/integrating_applications_with_ignite/#adding-extensions 

And then think about what Fintan mentioned for TP4 and GA?
There is no content yet in  https://github.com/syndesisio/syndesis/blob/master/doc/developing_customizations/ so there is no point pointing there.

**Comment by zregvart** [comment]
@syndesisio/ui-api & @cunningt would we be happy to to a bit of branding for the help link or would we push this to TP4?
